### ISSUE TITLE
VB -> C# : Default parameter "Value" differs in case between VB and C#

### ISSUE THREAD

**Issue by RachelDavids** [icsharpcode/CodeConverter#102]
### Input code
```VB
public Enum TestState
one
two
end enum
public class test

private _state as TestState
	Public Property State As TestState
		Get
			State = _state
		End Get
		Set
			If Not _state.Equals(Value) Then
				_state = Value
			End If
		End Set
	End Property
end class
```

### Erroneous output
```C#
public enum TestState
{
    one,
    two
}

public class test
{
    private TestState _state;
    public TestState State
    {
        get
        {
            State = _state;
        }
        set
        {
            if (!_state.Equals(Value))
                _state = Value;
        }
    }
}
```

### Expected output
```C#
public enum TestState
{
    one,
    two
}

public class test
{
    private TestState _state;
    public TestState State
    {
        get
        {
           return _state;
        }
        set
        {
            if (!_state.Equals(value))
                _state = value;
        }
    }
}
```

### Details
Product in use: e.g. web converter

Version in use: e.g. 5.6.3

Technically two issues here, will raise second one if deemed necessary.
The first I spotted was the incorrectly cased "Value" instead of "value" in the setter.

Secondly VB allows usage of "MethodName" in place of "return", but I'm not entirely certain about the best way to deal with this especially when it is used in multiple places.

**Comment by GrahamTheCoder** [comment]
Thanks, that looks reasonably straightforward to fix hopefully
I've pulled the second issue you mention out of "known limitations" and created an issue for it #103
