### ISSUE TITLE
typeof() in C# is not correctly converted to VB

### ISSUE THREAD

**Issue by SanKulPune** [icsharpcode/CodeConverter#1028]
### Input code
```csharp
options.AddAllowedClass(typeof(BlockReference), false)
```

### Erroneous output
```vbnet
options.AddAllowedClass(TypeOf(BlockReference), False)
```

### Expected output
```vbnet
options.AddAllowedClass(GetType(BlockReference), False)
```

### Details
* Product in use: CodeConverter
* Version in use: Free Online
* -

**Comment by GrahamTheCoder** [comment]
Thanks, I have updated the issue description to match.
When I paste just the input you gave into the Web converter and convert to vb, I do get the expected output with GetType. Could you share a bit more context of you have other surrounding code, or a screenshot if you're seeing exactly that output from the converter.

Please ensure you are using the converter here:
https://icsharpcode.github.io/CodeConverter/
(and not just some other one using an ancient version of our library)

Thanks!
