### ISSUE TITLE
VB -> C#: ClashingMemberRenamer incorrectly renames Enum types

### ISSUE THREAD

**Issue by Yozer** [icsharpcode/CodeConverter#1035]
### VB.Net input code
```vbnet
Public Enum Column
    Column
    ColumnPosition
End Enum
```

### Erroneous output
```C#
public enum Column
{
    ColumnField,
    ColumnPositionField
}
```

### Expected output
```C#
public enum Column
{
    Column,
    ColumnPosition
}
```

### Details

There is a logic to convert any enum members that are prefixed with the enum name.
I found [this ](https://github.com/icsharpcode/CodeConverter/issues/420#issuecomment-596098221)old issue which mention that this is not allowed in C#:
But I wasn't able to find anything in language specification that would not allow such naming (even if enum member is equal to enum itself).
[Sharplab.io](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYwCYgNQB8ACATAIwCwAUPsQJwAUqAhgLYCmA9gGa0DCbANsiaoAdLwFCAlBIDcFKnTGCRioQFFhAFTYBlOIgCWqAOa0ps8nIDMAAhapB1lagoBvCtY+P+SmO89PVCgBfIA==)

I found a recommendation but it results in a warning, not error:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1712

* Product in use: e.g. [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/) / **VS extension** / both
* Version in use: e.g. 5.6.3 or a commit hash https://github.com/icsharpcode/CodeConverter/commit/2ea789bc9c3123c8caa23ea1989bd6c65675354b
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
It's definitely possible that I had some setting which showed that warning you mention as an error for enums
