### ISSUE TITLE
VB -> C#: Problems with nullable comparisons and the null-coalescing operator

### ISSUE THREAD

**Issue by Sympatron** [icsharpcode/CodeConverter#1038]
### VB.Net input code
```vbnet
Function F(a As Net.IPAddress) As Boolean
	Return If(a?.ScopeId = 0, True)
End Function
```

### Erroneous output
```C#
public bool F(System.Net.IPAddress a)
{
    return (a?.ScopeId) is { } arg1 && arg1 == 0 ?? true;
}
```

### Expected output
```C#
public bool F(System.Net.IPAddress a)
{
    return (a?.ScopeId is {} arg1) ? (arg1 == 0) : true;
}
```

### Details
* Product in use: all
* Version in use: 9.2.3
* Did you see it working in a previous version: no

The problem here is that `Boolean? == Boolean` returns `Boolean?` in VB.NET, but just `bool` in C#. To work around this a temporary needs to be added in this case.
I did not dig too deep into this, but I suspect there might be a few places where this inconsistency between the languages can be a problem.

I think the more general conversion is this case would be:
```vbnet
a <op> b
```
to
```C#
((a is {} arg1) && (b is {} arg2)) ? (bool?)(arg1 <op> arg2) : null
```
if `a` and `b` are nullable and `<op>` is a relational operator. This can be simplified if `a` or `b` are non-nullable or reusable.
I think this can be skipped if the result is converted to `Boolean` implicitly anyway for example is a standard `If`-Clause, but for the null-coalescing operator this will otherwise not yield the correct result.

Note: This is just a minified example not actual production code.

**Comment by Sympatron** [comment]
The relevant code is [here](https://github.com/icsharpcode/CodeConverter/blob/fd6e10a860af1ea8f16df2ed062b9f9e2b991615/CodeConverter/CSharp/VisualBasicNullableExpressionsConverter.cs#L204-L243) I think.

**Comment by GrahamTheCoder** [comment]
Thanks for the report with great examples. Yep that's the code. As you've noticed there are quite a few cases to consider, but hopefully we can get it working with a couple of careful tests/tweaks

**Comment by Sympatron** [comment]
Wow, that was fast. I was just about to file a PR, because I found the same reason. Thanks for the quick fix.

**Comment by GrahamTheCoder** [comment]
Ah, you just posted at a very convenient time for me to look into it, sorry to steal your thunder!
If you want to do the special case, you'll need to look at VisitBinaryConditionalExpression
One way to do it would be to generate the same as now (ensuring the LHS ends up with IsNotNullableAnnotation), then check for that annotation on the LHS of a contained TernaryExpression and replace the side that doesn't have it with the conversion of `binaryConditionalExpression.Right`
