### ISSUE TITLE
C# -> VB: Add addresssof when passing method group

### ISSUE THREAD

**Issue by gmcfarlane** [icsharpcode/CodeConverter#1039]
### Input code
```csharp
public sub foo(){

  v_.MasterRowGetLevelDefaultView += new DevExpress.XtraGrid.Views.Grid.MasterRowGetLevelDefaultViewEventHandler(this.MasterRowGetLevelDefaultView);
}    
```

### Erroneous output
```vbnet
Public Function foo() As [sub]
    v_.MasterRowGetLevelDefaultView += New DevExpress.XtraGrid.Views.Grid.MasterRowGetLevelDefaultViewEventHandler(Me.MasterRowGetLevelDefaultView)
End Function
```

### Expected output
```vbnet
Public Function foo() As [sub]
    v_.MasterRowGetLevelDefaultView += New DevExpress.XtraGrid.Views.Grid.MasterRowGetLevelDefaultViewEventHandler( addressof Me.MasterRowGetLevelDefaultView)
End Function
```

simply needs  addressof as a parameter to the addHandler method. 
love the tool.  

### Details
* Product in use: e.g. [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by Sympatron** [comment]
I agree that `AddressOf` is missing in this case. But it still won't compile, because `+=` does not work for VB.NET.

**Comment by gmcfarlane** [comment]
Hey thanks for the reply 
 
It turns out that the specific function i was using may have been a function provided by the package. 
 
I took a minute to go write you a message, THEN went and tried to compile the code...
vb requires this code to add a handler.  
 
AddHandler gv_.MasterRowGetLevelDefaultView, AddressOf Me.MasterRowGetLevelDefaultView
 
 
its easy enough for me to self- correct these lines.  More often than not , I let the UI declare the handlers by adding the syntax after the routine's signature. 
 
 
the converter is a great tool. A company i used to work at used telerik tools and i really liked them, found this by accident poking around the site. 
 
Whether or not you choose to pursue this minor bug is completely up to you. I wanted to do my small small part by reporting a finding! 
 
 
greg
 
 
 
-----Original Message-----

**Comment by GrahamTheCoder** [comment]
Thanks both. I assume the Web converter was used here which only references a few core dot net libraries, so will never be able to distinguish the thing being assigned here is an event and just makes a best effort. 

If you use the extension in visual studio on compiling code, you'll generally get a far better conversion. I'd expect AddHandler to be added
It may also be that addresof is added, or that neither are. Would have to try it.
