### ISSUE TITLE
VB -> C#: `Handles` and `WithEvents`

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#104]
`Handles` and `WithEvents`

Should look at the compiled code for this, but see if there's an optimization possible to have less generated code in the simple case.

Might need an extra field fro the `WithEvents` fields, or even a property if new things are assigned and need to have handlers added automatically.

**Comment by RachelDavids** [comment]
@GrahamTheCoder - I've fallen foul of this whilst writing an FxCop rule ... be aware that the VB compiler generates an intermediate property which Attaches/Detaches the handlers (easily viewed in ILSpy or dotPeek) especially for those cases where the variable in question is not part of the construction, or may even be overwritten.

**Comment by GrahamTheCoder** [comment]
Thanks, I was aware of the generated variable, but was hoping it'd be possible to avoid. If you have a particular example of overwriting or where it's not part of the construction that I should use as a test for the implementation that'd be really useful.

**Comment by RachelDavids** [comment]
My FxCop rule was designed to detect "WithEvents" without any "Handles" and this is how I became aware of the problem. No documentation other than my usage of ILSpy/dotPeek ro view the sources.
as for non-construction use, we have a form which allows for addition of multiple records, each of which is validated (one by one) and needs event handlers for the UI to respond to the business rules. The AddNew button would replace the variable with a new object. Possibly you could search for assignment outside of (class) construction
