### ISSUE TITLE
VB -> C#: escaped label names keep the brackets

### ISSUE THREAD

**Issue by TymurGubayev** [icsharpcode/CodeConverter#1044]
### VB.Net input code
```vbnet
    Sub S()
        GoTo [finally]
[finally]:
        GoTo [Step]
[Step]:
    End Sub
```

### Erroneous output
```C#
        public void S()
        {
            goto [finally];
        [finally]:
            ;

            goto [Step];
        [Step]:
            ;

        }
```

### Expected output
```C#
public void S()
{
    goto @finally;
@finally:
    ;

    goto Step;
Step:
    ;

}
```

### Details
* Product in use: VS extension
* Version in use: 2e3da7eb0abad1fddd4976a7a8735e3d926b84ff
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the report! Should be a pretty straightforward fix in ConvertIdentifier if anyone wants to try ☺

**Comment by msant01s** [comment]
I would like to try. this would be my first time.

**Comment by GrahamTheCoder** [comment]
Great! Take a look at previous commits/PRs and https://github.com/icsharpcode/CodeConverter/blob/2e3da7eb0abad1fddd4976a7a8735e3d926b84ff/.github/CONTRIBUTING.md as a starting point.
Feel free to ask questions, or create a draft PR with any progress if you want to discuss details.

**Comment by msant01s** [comment]
I have the code pulled down, and I am trying to add a test case, but when I run the test case it fails. Saying they are deferent but i can not see the deference. 

 ICSharpCode.CodeConverter.Tests.CSharp.ExpressionTests.ExpressionTests.TODOSwitchstatmentTestAsync
   Source: ExpressionTests.cs line 2671
   Duration: 57.4 sec

  Message: 
System.Exception : Assert.Equal() Failure
Expected: 
          internal partial class TestClass
          {
              private void TestMethod()
              {
                      goto [finally];
                  [finally]:
                      ;
          
                      goto [Step];
                  [Step]:
                      ;
          
                  }
          }
Actual:   
          internal partial class TestClass
          {
              private void TestMethod()
              {
                  goto [finally];
              [finally]:
                  ;
          
                  goto [Step];
              [Step]:
                  ;
          
              }
          }


------------------------------------

diff:

internal partial class TestClass
{
    private void TestMethod()
    {
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxx xxxxxxxxx  xxxxxxxxxxxxxx     xxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

------------------------------------




------------------------------------


source:
Class TestClass
    Private Sub TestMethod()
        GoTo [finally]
[finally]:
        GoTo [Step]
[Step]:
    End Sub
End Class

---- Assert.Equal() Failure
Expected: 
          internal partial class TestClass
          {
              private void TestMethod()
              {
                      goto [finally];
                  [finally]:
                      ;
          
                      goto [Step];
                  [Step]:
                      ;
          
                  }
          }
Actual:   
          internal partial class TestClass
          {
              private void TestMethod()
              {
                  goto [finally];
              [finally]:
                  ;
          
                  goto [Step];
              [Step]:
                  ;
          
              }
          }

  Stack Trace: 
OurAssert.WithMessage(Action assertion, Func`1 getMessage) line 50
OurAssert.Equal(Object expectedText, Object actualText, Func`1 getMessage) line 42
OurAssert.EqualIgnoringNewlines(String expectedText, String actualText, Func`1 getMessage) line 37
ConverterTestBase.AssertCodeEqual(String originalSource, String expectedConversion, String actualConversion) line 166
ConverterTestBase.AssertConvertedCodeResultEquals(String convertedCodeFollowedByExceptions, String expectedConversionResultText, String originalSource) line 161
<AssertConvertedCodeResultEqualsAsync>d__21`1.MoveNext() line 153
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TaskAwaiter.GetResult()
<TestConversionVisualBasicToCSharpAsync>d__17.MoveNext() line 116
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TaskAwaiter.GetResult()
<TODOSwitchstatmentTestAsync>d__84.MoveNext() line 2673
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
<>c__DisplayClass4_0.<Equal>b__0() line 42
OurAssert.WithMessage(Action assertion, Func`1 getMessage) line 48

**Comment by msant01s** [comment]
I have looked at this a couple of times, and i am not seeing where i can fix this.  I have been looking at the ConvertIdentifier in the CommonConversions

**Comment by GrahamTheCoder** [comment]
Not to worry, it's always tricky to pick up a new code base.

As a starting point, have you tried:
* Create a test case based on the issue description
* Put a conditional breakpoint in convertidentifier that stops when there are square brackets in the identifier
* Debug that test

If you've done that and it doesn't hit the breakpoint, push the branch to a fork and I'll have a look. Hope that helps!

**Comment by GrahamTheCoder** [comment]
Sorry my hint on where to start was incorrect 😔
It turns out that in visual basic, labels are their own type (not an identifier) hence ConvertIdentifier is not used directly.

In terms of how to find where to look, you can either step through the code conversion from the top (VisitCompilationUnit), or you can put a breakpoint in a method that's very likely to be hit. 

If you look at the syntax tree of the input code you can see the names of the problematic part. There will be a "Visit..." method for most syntax types. If one doesn't exist, just pick the next one up the tree, and step in from that point.
![image](https://github.com/icsharpcode/CodeConverter/assets/2490482/5ff25972-b795-447b-861f-1fe955ca4d3c)
(source: https://sharplab.io/#v2:DYLgbgRgNALiCGBnGUAmIDUAfACgVwmAEsBjAAgGFglEyBpAUwE8B3AewCdUA5eAWwYBYAFBkxZAMoFJACgCUI8UrIBxNgBU2ZANoAzIgDt4wYEwC6IvYeOmzIRcrFrNOiTAYAHC8O1vPdhzEAUQNUSQIRELCqGiA===)

https://github.com/icsharpcode/CodeConverter/blob/0647b8d2056b1a7d0fc110290caff50b55cdc3f3/CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs#L728-L737
