### ISSUE TITLE
VB -> C#: `With Me` generates incorrect code (CS1605)

### ISSUE THREAD

**Issue by TymurGubayev** [icsharpcode/CodeConverter#1052]
### VB.Net input code
```vbnet
Public Class TestWithMe
    Private _x As Integer
    Sub S()
        With Me
            ._x = 1
        End With
    End Sub
End Class
```

### Erroneous output
```C#
    public class TestWithMe
    {
        private int _x;
        public void S()
        {
            {
                ref var withBlock = ref this; //CS1605: Cannot use 'this' as a ref or out value because it is read-only
                withBlock._x = 1;
            }
        }
    }
```

### Expected output
I think we can omit `ref` for reference types. Unfortunately, the `With Me`-syntax is valid for structures as well... So, maybe in that case don't create the `withBlock`-Variable and use `this` instead?

```C#
    public class TestWithMe
    {
        private int _x;
        public void S()
        {
            {
                var withBlock = this;
                withBlock._x = 1;
            }
        }
    }
```

### Details
* Product in use: VS extension
* Version in use: ae25cdc920df68755fb233934028091c97b42853
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
As the error message implies, the best solution to this would be one that detected whether the identifier referred to a readonly symbol in general (e.g. a readonly field). There's actually a special separate compiler error for trying to use a loop iteration variable in this way for example too:

```csharp
using System.Collections.Generic;

public struct TestWithMe
{
    private int _x;
    public static void Main()
    {
        new TestWithMe().M();
    }

    public void M()
    {

        var x = new List<TestWithMe>();
        foreach(var y in x){
            ref var withBlock =  ref y; // CS1657: Cannot use 'y' as a ref or out value because it is a 'foreach iteration variable'
            withBlock._x = 1;
            System.Console.Write(_x);
        }
    }
}
```

**Comment by TymurGubayev** [comment]
a similar problem arises if the `withBlock` is used inside a lambda created to resolve constants passed to ByRef parameters.

**Comment by TymurGubayev** [comment]
I've just noticed, output code in https://github.com/icsharpcode/CodeConverter/issues/1049 is actually missing the `ref` and so is semantically incorrect (the struct that's changed is the local copy instead of the instance in the special array thing):

Current output:
```cs
{
    var withBlock = lst[i];
    withBlock.SomeField = 5;
    s = withBlock.Text;
}
```
Should've been:
```cs
{
    var withBlock = lst[i];
    withBlock.SomeField = 5;
    s = withBlock.Text;
}
```
Because `lst[i]` is a struct and the indexer is `public ref T this[int i]`. Interestingly, an array instead of the special list class gets the `ref`-treatment.
