### ISSUE TITLE
VB -> C#: Non-Optional parameters can't follow optional ones

### ISSUE THREAD

**Issue by TymurGubayev** [icsharpcode/CodeConverter#1057]
### VB.Net input code
```vbnet
Sub S(Optional a As Integer = 0, Optional ByRef b As Integer = 0)
End Sub
```

### Erroneous output
```C#
public void S(int a = 0, [Optional, DefaultParameterValue(0)] ref int b) //CS1737: Optional parameters must appear after all required parameters
{
}
```

### Expected output
Using the `OptionalAttribute` instead on preceding parameters fixes the issue.

```C#
public void S([Optional, DefaultParameterValue(0)] int a, [Optional, DefaultParameterValue(0)] ref int b)
{
}
```

### Details
* Product in use: VS extension
* Version in use: ae25cdc920df68755fb233934028091c97b42853
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Ah, yes, makes sense. There are some cases where an attribute can't be used such as a vb date I think but should generally work
