### ISSUE TITLE
Output indicates successful conversions of each .vb file, but no .cs files are created

### ISSUE THREAD

**Issue by mjvisintin** [icsharpcode/CodeConverter#1058]
I select the Convert to C# and the output indicates successful conversions but no .cs files are added to the project or found on the machine....

Thanks,

Michael

Building project 'KHRateQuoteWinLib.vbproj' prior to conversion for maximum accuracy...

--------------------------------------------------------------------------------

Begin converting KHRateQuoteWinLib at 15:32:55...

Phase 1 of 2:
* clsFedexAddressValidation.vb - conversion started
* RateService.vb - conversion started
* clsGetFedexRateQuote.vb - conversion started
* clsGetKHWebRateQuote.vb - conversion started
* clsFedexAddressValidation.vb - conversion succeeded
* My Project\MyNamespace.Static.1.Designer.vb - conversion started
* My Project\MyNamespace.Static.1.Designer.vb - conversion succeeded
* clsYellowRateQuote.vb - conversion started
* clsYellowRateQuote.vb - conversion succeeded
* My Project\MyNamespace.Static.2.Designer.vb - conversion started
* ModGlobals.vb - conversion started
* My Project\MyNamespace.Static.2.Designer.vb - conversion succeeded
* ModGlobals.vb - conversion succeeded
* My Project\Settings.Designer.vb - conversion started
* My Project\Settings.Designer.vb - conversion succeeded
* My Project\Resources.Designer.vb - conversion started
* My Project\Resources.Designer.vb - conversion succeeded
* ModSharedFuncs.vb - conversion started
* ModSharedFuncs.vb - conversion succeeded
* My Project\MyNamespace.Dynamic.Designer.vb - conversion started
* My Project\MyNamespace.Dynamic.Designer.vb - conversion succeeded
* My Project\AssemblyInfo.vb - conversion started
* My Project\AssemblyInfo.vb - conversion succeeded
* My Project\MyNamespace.Static.3.Designer.vb - conversion started
* My Project\MyNamespace.Static.3.Designer.vb - conversion succeeded
* My Project\Application.Designer.vb - conversion started
* My Project\Application.Designer.vb - conversion succeeded
* clsGetKHWebRateQuote.vb - conversion succeeded
* RateService.vb - conversion succeeded
*

**Comment by mjvisintin** [comment]
I note that phase 2 had not started.
I also noted phase 2 timed out.
I have upped the timeout period and I will close out this ticket.
Sorry for any inconvenience.
Michael

**Comment by mjvisintin** [comment]
closing issue.

**Comment by GrahamTheCoder** [comment]
What did you set the timeout to? Just wondering if I should tweak the default

**Comment by mjvisintin** [comment]
I could have left it at 15 minutes, I just forgot to wait until it finished….

Sometimes phase 2 starts a bit later….

I set it to 30 minutes.

I have used this tool many times and just gave it an excellent rating on github.

Thanks,

Michael

**Comment by GrahamTheCoder** [comment]
Thanks, always good to hear the tool is helping people ☺

**Comment by mjvisintin** [comment]
Oh, you bet!

I came up in the C, C++ era, so I am used to reading C#.

However, I can code as fast as I can type in VB.NET, so I don’t have to think about designing.

So I write it in VB and use your conversion and then thereafter I do the modifications in C#.

Your tool may be keeping me lazy!!!

I should start writing from scratch in C#!!!!

Thanks again!

Michael
