### ISSUE TITLE
VB -> C#: Case `Empty` is not translated to `string.IsNullOrEmpty()`

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#1104]
### VB.Net input code
```vbnet
Dim Sprossenart As String
Dim Hoehe As String
    
Select Case Sprossenart
    Case Empty, "ohne"
        Hoehe = 0
End Select
```

### Erroneous output
```C#
var Sprossenart = default(string);
string Hoehe;

switch (Sprossenart ?? "")
{
    case var @case when @case == Empty: // <---- CS0103: The name 'Empty' does not exist in the current context
    case "ohne":
        {
            Hoehe = 0.ToString();
            break;
        }
}
```

### Expected output
```C#
var Sprossenart = default(string);
string Hoehe;

switch (Sprossenart ?? "")
{
    case var @case when string.IsNullOrEmpty(@case):
    case "ohne":
    {
        Hoehe = 0.ToString();
        break;
    }
}
```

### Details
* Product in use: [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/)
* Version in use: 9.2.5.0

**Comment by GrahamTheCoder** [comment]
If you ctrl click on Emptyin the vb net example within visual studio, what does it resolve to there?

**Comment by Saibamen** [comment]
I'm using VB6 SP6

![image](https://github.com/icsharpcode/CodeConverter/assets/905878/30c48e3c-e455-4772-9d70-753ba65dcbff)

**Comment by GrahamTheCoder** [comment]
If you upgrade to vb.net first, does it work from the upgraded result?

**Comment by Saibamen** [comment]
Visual Basic 2008 Express Edition upgraded the code to this:

```vbnet
Option Strict Off
Option Explicit On
Module SubMainModule
	
	Public Sub Main()
		Dim strTest As String
		
		strTest = CStr(0)
		
		Dim Sprossenart As String
		Dim Sprossenhoehe As String
		
		Select Case Sprossenart
			Case CStr(Nothing), "ohne"
				Sprossenhoehe = CStr(0)
		End Select
		
		Debug.Print("Test")
		MsgBox("Test", 0, "Main")
	End Sub
End Module
```

But I'm not able to run the converted project because of this error:

![image](https://github.com/icsharpcode/CodeConverter/assets/905878/c98041d6-0a5e-4643-a2f1-7b7a2e6cfaf4)

**Comment by Saibamen** [comment]
ping @GrahamTheCoder

**Comment by GrahamTheCoder** [comment]
I ran the code you just gave through the we converter. It compiles and runs the same as the code you gave:
https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwLACgCWVgFMxQCGANgAQACAjAGykAOhYwmJFATKQMoQBGAsoWx8A9nAjFcGAN4YMpeezZyFM9AvWkAboy50wwgM4HcRJqQC8pOLgBmhccAAUVAAwBKANzKNFSi9IAEsK4ABa4XujeGgYA7pjAAMYhpI6ceobGpsCkAPw5pABEBW5R6qo+PgmExlo65ORVNTFhUBQN1bgWlkUgpRWNnQXCIVC4Bb1qFVPlU7PyQaGdli4AdAAqwpzAYNgA5o6efXPqPGC4hADWEccaAL5HpPeT8k+3QA===

Is there an issue here I can't see?

**Comment by Saibamen** [comment]
If this works for VB.NET -> C#, this is ok
