### ISSUE TITLE
VB -> C#: Error translating Not (x IsNot Nothing)

### ISSUE THREAD

**Issue by mom-bbtsoftware** [icsharpcode/CodeConverter#1113]
### VB.Net input code
```vbnet
If Not (x IsNot Nothing) Then

' same meaning as: If x Is Nothing Then
```

### Erroneous output
```C#
if (x is not null)
```

### Expected output
```C#
if (x is null)
```

### Details
* Product in use: [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/) VS extension
* Version in use: 9.2.5 (latest release)

**Comment by mom-bbtsoftware** [comment]
![grafik](https://github.com/icsharpcode/CodeConverter/assets/122623555/3043d0bd-d0d0-4102-bbe3-c35f594ad9af)

**Comment by GrahamTheCoder** [comment]
Yikes. Thanks for the report, I can guess how that happened. Should be an easy fix.
