### ISSUE TITLE
Both SingleAbstractMethod tests have invalid code

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#112]
Abstract members cannot be private.

To Fix:
SingleAbstractMethod in CSharp\StandaloneMultiStatementTests.cs
SingleAbstractMethod in VB\StandaloneMultiStatementTests.cs

Use a different visibility modifier other than private for both C# and VB methods.

**Comment by GrahamTheCoder** [comment]
Thanks for looking at these (i.e. this and #111). This is precisely why I added the [feature flagged code](https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/Shared/ProjectConversion.cs#L94) which detects compilation errors. I'm planning to go through the whole set sometime soon as part of #60, so no need to flag issues for individual ones.
I'm going to start on the VB -> C# tests, so let me know if you want to work on a PR for the C# -> VB half (or any subset of them).

**Comment by RussellSmith2** [comment]
I found this issue along with #110 and #111 by extracting the code out of each of the test parameters and putting each into its own file and namespace in an empty project.  If it had a namespace I modified it so each namespace was unique. I also added wrapping classes and methods as needed to the test code.

I believe it was after finding #100 by converting the projects own code files that I noticed that same issue was in the tests as well.

My "Test Source" project is showing many errors like needing the implements statements on methods and properties, custom events requiring the Custom keyword and RaiseEvent accessor, and needing an implements statement on out parameters.  And that is just the VB errors because they show in the error list where, right now, to find the C# ones I have to open a file with an error.

**Comment by GrahamTheCoder** [comment]
Ah I see. The code I mentioned just tests that the code compiles in the same context it's converted. That means things like missing references are flagged up too, and when they're edited it's easy to retest. I did actually consider making the tests run from their own project like the one you've created, but I'm worried it'd be too easy to tangle many test cases together and lose track of what's being tested at each point.

In terms of having to open the C# file to see the error, do you have Build + Intellisense selected in the error list?
![image](https://user-images.githubusercontent.com/2490482/39118319-0c7e7282-46e1-11e8-8d69-fef91363bbe0.png)
I'm surprised if errors aren't shown after attempting to build the project.

**Comment by RussellSmith2** [comment]
Yes.  VB doesn't need to be compiled to start showing the errors so they appear without doing anything. The C# may start showing if I tried to compile I just never did because it would fail.  Plus I could of excluded the VB files from the project and then compiled.  I just started looking into the VB errors since they were already there.

**Comment by RussellSmith2** [comment]
I used unique namespaces to keep the test code separate so there weren't naming conflicts.  It does result in some big ugly namespaces but since this code isn't going to be used for anything other than to confirm it is valid code its not a big deal.

Example:
namespace VisualBasicToCSharp.Expressions.Await.CS
Namespace VisualBasicToCSharp.Expressions.Await.VB

To keep the files sorted each test file got its own directory and each assertion in a test method is in its own file.
