### ISSUE TITLE
Tests are failing if the current culture is not en-US 

### ISSUE THREAD

**Issue by LucTremblay** [icsharpcode/CodeConverter#1145]
Hello,

If the current computer culture is not en-US  a lot of asserts will fail, because the language of the error might not be english. 

Here is a example of a failing test:

Expected a message in english
```
Expected: using System;
          
          internal partial class TestClass
          {
              private void TestMethod()
              {
                  if (MyEvent is not null)
                      MyEvent(this, EventArgs.Empty);
              }
          }
          1 source compilation errors:
          BC30451: 'MyEvent' is not declared. It may be inaccessible due to its protection level.
          1 target compilation errors:
          CS0103: The name 'MyEvent' does not exist in the current context

```

The message is in french
```
Actual:   using System;
          
          internal partial class TestClass
          {
              private void TestMethod()
              {
                  if (MyEvent is not null)
                      MyEvent(this, EventArgs.Empty);
              }
          }
          1 source compilation errors:
          BC30451: 'MyEvent' n'est pas déclaré. Il peut être inaccessible en raison de son niveau de protection.
          1 target compilation errors:
          CS0103: Le nom 'MyEvent' n'existe pas dans le contexte actuel
```

A simple fix could be to set the DefaultThreadCurrentUICulture, in the base class of the unit tests seems to fix the issue:
https://github.com/icsharpcode/CodeConverter/compare/master...LucTremblay:CodeConverter:defaultThreadCurrentUICulture

`CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.InvariantCulture;`
or
`CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("en-US")`

**Comment by GrahamTheCoder** [comment]
Good point, please PR with invariamt culture if that works, thanks!
