### ISSUE TITLE
AddParens only if it is not already a ParenthesizedExpressionSyntax

### ISSUE THREAD

**Issue by LucTremblay** [icsharpcode/CodeConverter#1146]
Hello

While debugging the code, we can see a lot of unneeded parenthesis are added to the converted code.

A lot of parenthesis are directly over another set of parenthesis and they seems to be added by the AddParens method.

Those extra parenthesis seems unneeded and makes debugging harder (to me at least).

The fix is simple and it also could help a bit to speed up the simplification phase, what do you thing?
https://github.com/icsharpcode/CodeConverter/commit/1ed28ce34e4cd0f43aa3622bc934143d4fc8ea8f

```
    public static ExpressionSyntax AddParens(this ExpressionSyntax expression)
    {
        if (expression is ParenthesizedExpressionSyntax)
            return expression;
        return SyntaxFactory.ParenthesizedExpression(expression);
    }
```

**Comment by GrahamTheCoder** [comment]
Feel free to PR, just check if another similar method already exists.
