### ISSUE TITLE
VB -> C#: Switch not viable for Select Case

### ISSUE THREAD

**Issue by MrGadget1024** [icsharpcode/CodeConverter#118]
### Input code
```VB
	Function CanDoWork(Something As Object) As Boolean
		Select Case True
			Case Today.DayOfWeek = DayOfWeek.Saturday Or Today.DayOfWeek = DayOfWeek.Sunday
				' we do not work on weekends
				Return False
			Case Not IsSqlAlive()
				' Database unavailable
				Return False
			Case TypeOf Something Is COAuthentication
				' Do something with the Object
				Return True
			Case Else
				' Do something else 
				Return False
		End Select
	End Function

	Private Function IsSqlAlive() As Boolean
		' Do something to test SQL Server
		Return True
	End Function
```

### Erroneous output
```cs
class SurroundingClass
{
    public bool CanDoWork(object Something)
    {
        switch (true)
        {
            case Today.DayOfWeek == DayOfWeek.Saturday | Today.DayOfWeek == DayOfWeek.Sunday:
                {
                    // we do not work on weekends
                    return false;
                }

            case !IsSqlAlive():
                {
                    // Database unavailable
                    return false;
                }

            case Something is COAuthentication:
                {
                    // Do something with the Object
                    return true;
                }

            default:
                {
                    // Do something else 
                    return false;
                }
        }
    }

    private bool IsSqlAlive()
    {
        // Do something to test SQL Server
        return true;
    }
}
```

### Expected output
```cs
class SurroundingClass
{
	public bool CanDoWork(object Something)
	{
		if (DateTime.Today.DayOfWeek == DayOfWeek.Saturday | DateTime.Today.DayOfWeek == DayOfWeek.Sunday)
		{
			// we do not work on weekends
			return false;
		}
		else if (!IsSqlAlive())
		{
			// Database unavailable
			return false;
		}
		else if (Something is COAuthentication)
		{
			// Do something with the Object
			return true;
		}
		else
		{
			// Do something else 
			return false;
		}
	}

	private bool IsSqlAlive()
	{
		// Do something to test SQL Server
		return true;
	}
}
```

### Details
web converter 5.6.3

**Comment by GrahamTheCoder** [comment]
Thanks for the report with repro. I'll take a look now. As of reasonably recently, C# actually can handle these conditions within a select. The code converter already handles lots of cases this way, but obviously one has been missed.

So I'll aim for the output to be:
```
class SurroundingClass
    {
        public bool CanDoWork(object Something)
        {
            switch (true)
            {
                case object _ when DateTime.Today.DayOfWeek == DayOfWeek.Saturday | DateTime.Today.DayOfWeek == DayOfWeek.Sunday:
                {
                    // we do not work on weekends
                    return false;
                }

                case object _ when !IsSqlAlive():
                {
                    // Database unavailable
                    return false;
                }

                case object _ when Something is int:
                {
                    // Do something with the Integer
                    return true;
                }

                default:
                {
                    // Do something else 
                    return false;
                }
            }
        }

        private bool IsSqlAlive()
        {
            // Do something to test SQL Server
            return true;
        }
    }
```

**Comment by MrGadget1024** [comment]
Unfortunately that'd only work if we're needing the conversion for latest C#.  If we need it for a certain game engine that's stuck on an older version of C# / Mono this won't be helpful.

**Comment by GrahamTheCoder** [comment]
Ah, that's unfortunate. Can you explain a little why you're stuck on an old compiler version? What breaks if you upgrade? Are you running some custom compiler extensions for the game engine maybe? The purely syntactic features like the style I used above can generally be targeted at older frameworks if that's the real issue.

**Comment by MrGadget1024** [comment]
Unity 2017.4.x is locked into the C# 6.0 compiler which doesn't have the language features needed here, e.g. pattern matching.  This is their LTS (long-term stable) version.  Unity 2018.1 has a customized Roslyn compiler that supports C# 7.2, but Unity 2018.x is very new and very much under heavy development.

**Comment by GrahamTheCoder** [comment]
Ah yes I had a quick look at [their forums](https://forum.unity.com/threads/c-7-support.512661/) and it seems like there isn't an LTS way to use C# 7 yet. That does indeed suck 😞 

If you look at where I just [made this fix](https://github.com/icsharpcode/CodeConverter/commit/225a383b9dbcfc31bdd6dca4fa80fb69c4242986) you can probably figure out how to turn it into an if-else structure (it's easy to build/run the converter locally). Another possibility is using a refactoring tool to turn them into if statements in the VB prior to conversion - Telerik's JustCode mentions the opposite refactoring in its [documentation](http://docs.telerik.com/help/justcode/quick-hints-convert-if-to-switch-statement.html), it's just possible it has both. Hope that helps!
