### ISSUE TITLE
C# -> VB: interface conversion not occuring correctly

### ISSUE THREAD

**Issue by MatthewDancz** [icsharpcode/CodeConverter#125]
### Input code
```C#
    public class ToBeDisplayed : iDisplay
    {
        public string Name { get; set; }

        public void DisplayName()
        {
            Console.WriteLine(Name);
        }
    }

    public interface iDisplay
    {
        string Name { get; set; }
        void DisplayName();
    }
```

### Erroneous output
```vbnet
 Public Class ToBeDisplayed
        Implements iDisplay

        Public Property Name As String

        Public Sub DisplayName()
            Console.WriteLine(Name)
        End Sub
    End Class

    Interface iDisplay
        Private Property Name As String
        Sub DisplayName()
    End Interface
```

### Expected output
```vbnet
Public Class ToBeDisplayed
    Implements iDisplay

    Public Property Name As String Implements iDisplay.Name

    Public Sub DisplayName() Implements iDisplay.DisplayName
        Console.WriteLine(Name)
    End Sub
End Class

Interface iDisplay
    Property Name As String
    Sub DisplayName()
End Interface
```

### Details
Product in use: web converter v5.7.0.0 and Visual Studio 2017 v15.7.2

Thoughts: My thought is that the converter doesn't understand C# Get and Set methods for properties, but that doesn't explain why I receive compiler errors saying that my implementing class doesn't implement DisplayName() in the erroneous code.

**Comment by siegfriedpammer** [comment]
The only thing that's missing in the VB version is the implements clause... Other than that auto properties use that syntax in VB.

**Comment by MatthewDancz** [comment]
Oh okay, I don't use VB. I did notice that it wasn't bringing over the implements clause, and that iDisplay string property converted to a private Property from C# to VB. In C# all interface properties are considered public, and you cannot set the access modifier to anything other than that. Hopefully these are easy fixes.

**Comment by GrahamTheCoder** [comment]
The implements clause is there. The private modifier on the interface member is definitely incorrect, so I'll fix that. I've updated the expected output correspondingly

**Comment by siegfriedpammer** [comment]
In VB each member that implements an interface member needs to have a corresponding implements clause: see https://github.com/dotnet/vblang/blob/master/spec/type-members.md

So the expected output would be `Public Property Name As String Implements iDisplay.Name` for the property and `Public Sub DisplayName() Implements iDisplay.DisplayName` for the method, I believe...

Quote from the spec:

> Methods, events, and properties can implement interface members. To implement an interface member, a member declaration specifies the Implements keyword and lists one or more interface members.

**Comment by GrahamTheCoder** [comment]
@siegfriedpammer Ah thanks, didn't know that was required in VB. I've updated the expected output. I'll have a look at fixing both things sometime soon hopefully, though as always if someone else is keen to PR a fix, just post here before you get started.
