### ISSUE TITLE
Stop convert option getting in the way at the project level

### ISSUE THREAD

**Issue by splendid25** [icsharpcode/CodeConverter#131]
Is it possible to add an option to disable the plugin on a project item ? Or at least move down the button?
When I right click on a project, the first item of the context menu is : Convert to VB/C#
I often misclick on this first button instead of the usual first item : Build...

But I still want to be able to convert individual files as it is now.

Thanks

**Comment by GrahamTheCoder** [comment]
Thanks for the feedback. Instead of an option to disable, I might just try to put it in a more sensible location in that menu. It's obviously not the most important thing in most people's daily workflow so being first is a bit unnecessary.
