### ISSUE TITLE
VB -> C#: Number format specifier conversion

### ISSUE THREAD

**Issue by jhonzah** [icsharpcode/CodeConverter#146]
Format specifier not converted.

### Input code
```vbnet
Dim TestVar = 20.5!
```

### Erroneous output
```C#
var TestVar = 20.5!
```

### Expected output
```C#
var TestVar = 20.5F
```

### Details
When converting a whole winforms project dimensions and sizes in *.designer.vb files are not converted correctly due to this issue.

Product in use: VS 2017 Community 15.7.4,  VS extension 5.8.0.0

**Comment by CoderNate** [comment]
This should be fixed if #141 gets accepted.
