### ISSUE TITLE
Null path when converting project - workaround: restart VS

### ISSUE THREAD

**Issue by B0R1K** [icsharpcode/CodeConverter#173]
Not sure what other info to get for this...

![image](https://user-images.githubusercontent.com/2473977/45239533-9300e680-b2b3-11e8-9e49-5fa80acbc747.png)

**Comment by GrahamTheCoder** [comment]
Thanks for the report, I can imagine that would happen if you try to convert a brand new solution that hasn't been saved anywhere yet. If that's it, let me know and I'll  at least put in a better error message explaining.

**Comment by B0R1K** [comment]
no i am trying to convert an Existing project inside the Existing solution

**Comment by B0R1K** [comment]
after rebooting problem went away...

**Comment by GrahamTheCoder** [comment]
My fix for #243 should avoid this error happening again. Though there's a small chance that a project could be missed from the conversion in the case this previously happened. If that happens we can open a new issue for it.
