### ISSUE TITLE
vb.net -> C#: Replace Visual Basic library calls with equivalent things from the .NET framework

### ISSUE THREAD

**Issue by B0R1K** [icsharpcode/CodeConverter#174]
instead of using: 
`!Information.IsDBNull`

it should use 
`!DBNull.Value.Equals`

EDIT: See https://github.com/icsharpcode/CodeConverter/issues/174#issuecomment-461091117 for fuller listing

**Comment by GrahamTheCoder** [comment]
Request to substitute Vb, Cr and VbCrlf with their string equivalent: https://github.com/icsharpcode/CodeConverter/issues/228

**Comment by GrahamTheCoder** [comment]
Here are some that I came across when moving to things to .NET Standard:
* `Hex(byte)` to $"{byte:X2}"
* `My.Computer.FileSystem.DirectoryExists(fileName)` to `Directory.Exists(fileName)`
* `My.Computer.FileSystem.FileExists(fileName)` to `File.Exists(fileName)`
* `My.Computer.FileSystem.DeleteFile(fileName)` to `File.Delete(fileName)`
* `My.Computer.Info.OSFullName` to `Runtime.InteropServices.RuntimeInformation.OSDescription`
* `My.Computer.FileSystem.GetFileInfo(f)` to `new FileInfo(f)`
* `DateDiff(DateInterval.Day, aDate, aSecondDate)` to `(aDate - aSecondDate).TotalDays`
* `DateDiff(DateInterval.Hour, aDate, aSecondDate)` to `(aDate - aSecondDate).TotalHours`
* `DateDiff(DateInterval.Minutes, aDate, aSecondDate)` to `(aDate - aSecondDate).TotalMinutes`
* `My.Computer.FileSystem.SpecialDirectories.Desktop` to `Environment.GetFolderPath(Environment.SpecialFolder.Desktop)`
* `UBound(myArray)` to `myArray.GetUpperBound(0)`
* `Format$(value)` to `$"{value}"`
* `Format$(value, "0.0")` to `$"{value:0.0}"`
* `Replace(strOutPut, "&lt;", "<")` with `strOutPut.Replace("&lt;", "<")`
* `Len(str)` to `str.Length`
* `Left(x, 4)` to `x.Substring(0, 4)`
* `IsNumeric(x)` `to Integer.TryParse(x ,out var _)`

Some of these need some checking, and there are obvious other similar ones nearby too that I haven't bothered listing explicitly

**Comment by GrahamTheCoder** [comment]
When implemented, I'd like to do this as a separate (probably post conversion) pass.
The code from it should be independently runnable on any c# tree. 

Nice to have: Conservative vs aggressive mode, determining whether only aVB methods with a very close match are replaced, or ones that change the logic in more cases  too.

**Comment by GrahamTheCoder** [comment]
Another good example in #345

**Comment by tverweij** [comment]
@GrahamTheCoder 
"Another good example in #345"

Be carefull with this call.

See the following VB code
```
Public x As String = Nothing
Public y as String = IIf(x is Nothing, "123", q)

Public Function q()
  x = "ABC"
  exit x
End Function

```
The first line sets x to Nothing (null)
The second line checks is x is nothing, _then executes function q_, and then returns "123".
If the first condition was also a function this would have been executed first.

If I replace the IIf with an If (so 1 I) then code runs as:
The first line sets x to Nothing (null)
The second line checks if x is nothing, so it returns "123" - q is NOT executed.

So 
iif(x Is Nothing, 1, x.length) will cause a runtime error
While
if(x Is Nothing, 1, x.length) will not

**Comment by GrahamTheCoder** [comment]
For the ones that aren't equivalent, I've been thinking about implementing them as roslyn diagnostics for VB and/or c#. So they can be done more piecemeal before and/or after conversion (or the same code could run as part of conversion if an option was enabled).

**Comment by GrahamTheCoder** [comment]
Possible case in #587, need to ensure it has the same result on Linux

**Comment by GrahamTheCoder** [comment]
Test case: #691

**Comment by GrahamTheCoder** [comment]
#814 covers the simple cases. Here's what I'm aware is remaining:

```vbnet

' Microsoft.VisualBasic.Information
    LBound(anArray, rank) ' anArray.GetLowerBound(rank - 1) same checks are done but exception type will differ RankException -> IndexOutOfRangeException
    UBound(myArray, anInt) 'to myArray.GetUpperBound(myArray, anInt - 1) same checks are done but exception type will differ RankException -> IndexOutOfRangeException

' Microsoft.VisualBasic.Conversion
    Hex(4) '{arg:X}; or arg.ToString("X") whenever it's an integer type (sbyte, byte, int, uint, long, ulong)
    Fix(x) ' return x where x is short, long or integer
    Int(x) ' return x where x is short, long or integer
    Int(x) ' Math.Floor(x) where x is double
    Int(x) ' (float) Math.Floor(x) where x is float
    Int(x) ' Decimal.Floor(x) where x is decimal

'  Microsoft.VisualBasic.DateAndTime
    DateDiff(DateInterval.Day, aDate, aSecondDate) 'to (aDate - aSecondDate).TotalDays
    DateDiff(DateInterval.Hour, aDate, aSecondDate)' to (aDate - aSecondDate).TotalHours
    DateDiff(DateInterval.Minute, aDate, aSecondDate)' to (aDate - aSecondDate).TotalMinutes
    DateDiff(DateInterval.Second, aDate, aSecondDate)' to (aDate - aSecondDate).TotalSeconds
' TODO DateAdd and DatePart also have some simple cases

' Microsoft.VisualBasic.Strings
    Len(str)' to str?.Length ?? 0  (if it might be null)
    Left(str, 4) 'to x.Length <= 4  ? x.Substring(0, 4) : x;  where x is a string. For int etc. there are predefined lengths (in terms of bytes)
' TODO ^ Finish looking through this class for other examples like LCase and Join
```

Need a closer look:
```vbnet
    Format$(str)' to $"{value}"
    Format$(anInt, "0.0") 'to $"{value:0.0}"
    Replace(str, "&lt;", "<") 'with strOutPut.Replace("&lt;", "<") ' various oddities around nulls and optional args
```


Some examples looks too different:
```vbnet
    IsNumeric(str) 'to double.TryParse(x ,out var _)... not really viable because of hex/oct possibility
```
