### ISSUE TITLE
Incorrect translation of for loop from VB to C#

### ISSUE THREAD

**Issue by Magnus12** [icsharpcode/CodeConverter#177]
### Input code
```VB
Dim stringValue AS string = "42"

For i As Integer = 1 To 10 - stringValue.Length
   stringValue = stringValue & " " + Cstr(i)
   Console.WriteLine(stringValue)                
Next
```

### Erroneous output
```C#
string stringValue = "42";
for (int i = 1; i <= 10 - stringValue.Length; i++)
{
    stringValue = stringValue + " " + System.Convert.ToString(i);
    Console.WriteLine(stringValue);
}
```
Resulting in
42 1
42 1 2
42 1 2 3

### Expected output
```C#
string text = "42";
checked
{
   int num = 10 - text.Length;
   for (int i = 1; i <= num; i++)
   {
	text = text + " " + Conversions.ToString(i);
     	Console.WriteLine(text);
   }
}
```
Resulting in
42 1
42 1 2
42 1 2 3
42 1 2 3 4
42 1 2 3 4 5
42 1 2 3 4 5 6
42 1 2 3 4 5 6 7
42 1 2 3 4 5 6 7 8

###Details
In C# the loop boundary condition is evaluated on each iteration. In VB.NET, it is only evaluated on entry of the loop.

Tested at
https://codeconverter.icsharpcode.net/

**Comment by GrahamTheCoder** [comment]
Ah very good spot! Should be an easy enough fix. When doing this transformation, if the expression isn't a constant value we can pull it out as a variable as you showed in the expected output.  Thanks for the report.
