### ISSUE TITLE
VB -> C# As lacks surrounding paranthesis

### ISSUE THREAD

**Issue by MarcusAndren2** [icsharpcode/CodeConverter#178]
### Input code
```vbnet
TryCast(New Object(), Object).ToString()
```
### Erroneous output
```C#
new object() as object.ToString();
```
### Expected output
```C#
(new object() as object).ToString();
```
### Details
Product in use: VS Extension
Version in use: 6.0.0

Convert fails to add parentheses around the resulting As expression when needed.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Yep this should be a pretty straightforward fix. Just find the place where this cast is converted, and if it's parent is also an expression, add parentheses.
