### ISSUE TITLE
VB -> C# Module in different namespace

### ISSUE THREAD

**Issue by MarcusAndren2** [icsharpcode/CodeConverter#179]
### Input code
```vbnet
Namespace TestNamespace
    Public Module TestModule
        Public Sub ModuleFunction()
        End Sub
    End Module
End Namespace

TestNamespace.ModuleFunction()
```
### Erroneous output
```C#
TestNamespace.ModuleFunction();
```
### Expected output
```C#
TestNamespace.TestModule.ModuleFunction();
```
### Details
Product in use: VS Extension
Version in use: 6.0.0

When a Module exists in a different namespace than the calling function, the class is lost in conversion. This happens both with explicit namespace declarations as in the example and when importing a namespace.

**Comment by GrahamTheCoder** [comment]
Thanks for the clear report. This looks like a case of not re-qualifying something correctly when it's using Visual Basic's type promotion. Most of the fixes to the `QualifyNode` method to deal with similar things happened around https://github.com/icsharpcode/CodeConverter/issues/107 but this one must have been missed.
