### ISSUE TITLE
VB -> C# : methods need explicit parenthesis

### ISSUE THREAD

**Issue by splendid25** [icsharpcode/CodeConverter#181]
### Input code
```vbnet
Dim myItems As List(Of Item) = ItemDAL.GetItems
```

### Erroneous output
```C#
List<Item> myItems = ItemDAL.GetItems;
```
=> error CS0428

### Expected output
```C#
List<Item> myItems = ItemDAL.GetItems();
```

### Details
Version in use: 
- converter  6.0.0.0
- VS 15.8.4

**Comment by GrahamTheCoder** [comment]
If that's the only input you gave, there's no way to know the type of ItemDAL, so GetItems could be a property or a method - hence it can't guess to add brackets. In this sort of case I'll occasionally add heuristics. e.g. I could make it err on the side of assuming it's a method if it starts with the word "Get". But that seems a bit too specialist to me, so I don't think I will do so on this occasion.

However, you mention you're using visual studio - if the context was indeed available (and compiling), the converter should have used it, so this would be a bug. If that's the case, please provide enough context to create a compilable repro. Thanks for the report!

**Comment by splendid25** [comment]
I can't reproduce the issue consistently...

I have 2 checkout directories : 
1) working directory
=> IntelliSense is showing
=> the converter always adds explicit () in C#
2) fresh checkout with the same code base, compiled once correctly
=> all calls to a specific project are missing IntelliSence
=> the converter doesn't add () for these calls

When I try to create a minimal class to reproduce, it works in both solutions (and IntelliSense is working correctly)...

So actually the conversion rule is OK, it seems to be a VS problem.
Any idea on what's happening ?

**Comment by GrahamTheCoder** [comment]
Thanks for trying to repro. I agree it sounds like a vs issue. I do have vague plans to communicate difficulties during compilation that affect the conversion, but it's a bit down the priorities at the moment.

When I've seen VS so weird stuff like that it's usually down to:
* A project referencing one with a slightly higher dot net framework version
* The particular configuration (e.g release vs debug, or anycpu vs x64) either not building the project, our not doing so in a compatible configuration.
Hope that helps and thanks again!
