### ISSUE TITLE
VB -> C# : bracket operator

### ISSUE THREAD

**Issue by splendid25** [icsharpcode/CodeConverter#182]
### Input code
```vbnet
Function GetItem(dr As DataRow) As Object
    Return dr.Item("col1")
End Function
```

### Erroneous output
```C#
public static object GetItem(DataRow dr)
{
    return dr.Item["col1"];
}
```
=> error cs1061
=> visibility changed to public

### Expected output
```C#
static object GetItem(DataRow dr)
{
    return dr["col1"];
}
```

### Details
Version :
converter 6.0.0.0
VS 15.8.4

**Comment by GrahamTheCoder** [comment]
Good spot regarding the "Item" part still being there. The visibility for functions in Visual Basic is public if not specified, so I think that part is already correct. Thanks!
