### ISSUE TITLE
VB -> C# : ref / out and "Integer?" conversion

### ISSUE THREAD

**Issue by splendid25** [icsharpcode/CodeConverter#187]
### Input code
```vbnet
Public Function Bar(value As String) As Integer?
        Dim result As Integer
        If Integer.TryParse(value, result) Then
            Return result
        Else
            Return Nothing
        End If
    End Function
```

### Erroneous output
```C#
 public int? Bar(string value)
        {
            int result;
            if (int.TryParse(value, ref result))
                return result;
            else
                return default(Integer?);
        }
```

1. ref should be out
2. Integer? is not valid in C#

### Expected output
```C#
 public int? Bar(string value)
        {
            int result;
            if (int.TryParse(value, out result))
                return result;
            else
                return default(int?);
                // or :
                // return null;
        }
```

### Details
Version in use:
converter 6.0.0.0
VS 15.8.4

**Comment by GrahamTheCoder** [comment]
Thanks for the clean repro.

I'm very surprised to see the ref/out not working, there's already code in place to handle this and this [test](https://github.com/icsharpcode/CodeConverter/blob/master/Tests/CSharp/ExpressionTests.cs#L444) which is quite similar. So hopefully should be an easy fix.

The `Integer?` situation I'm less surprised by - the code for handling those things isn't particularly robust/methodical. Since there's already code to convert `Integer` to `int` though I can't see it being that tricky to add `Integer?` -> `int` conversion 👍

**Comment by knodel12** [comment]
This issue appears to be related to ToMinimalCSharpDisplayString.

It seems this function results in a VB syntax declaration, which is where the Integer? seems to come from.

**Comment by GrahamTheCoder** [comment]
Yep, that sounds right - very happy to accept a PR

**Comment by splendid25** [comment]
Perhaps Nullable<T> values should be converted to null instead of default(T) when dealing with assignment/equality.
I think the code would be clearer. Even if the result is actually the same.
What do you think?

**Comment by knodel12** [comment]
@GrahamTheCoder , I was trying to figure out the issue, but I'm a tad stuck... It seems the Semantic object that's passed in is for VB when it seems it should be CSharp.  Do you have any suggestions on how to get the CSharp Semantic object?

**Comment by GrahamTheCoder** [comment]
That is the crux of the problem yes. In doing a semantic analysis of vb code, you obviously get a vb model. Hence there's that method which tries to tweak the result into a valid csharp string. The semantic model will contain the underlying .net type so the ideal would be to create a C# symbol from that, then call ToDisplayString. I'm not sure how to do so or whether that's even possible, so the alternative is to take a look at the code for a csharp type symbol which does ToDisplayString, and try to reimplement the relevant parts.
