### ISSUE TITLE
VB -> C#: regions are ignored

### ISSUE THREAD

**Issue by LinoBarreca** [icsharpcode/CodeConverter#189]
### Input code
```vbnet
#Region "Region Name"
'some code
#End Region
```

### Erroneous output
```C#
//some code
```

### Expected output
```C#
#region Region Name
//some code
#endregion
```

### Details
Product in use: VS extension

Version in use: e6.1.0.0

Regions aren't translated.

**Comment by GrahamTheCoder** [comment]
Yep you're absolutely right, thanks for the report I'd forgotten about this.
I'm unlikely to pick it up any time soon, but very happy to accept a PR that uses the existing trivia conversion code to process these. Look at the part that [converts comments](https://github.com/icsharpcode/CodeConverter/blob/b73c1a4a865fd80866e4d7302d8f973130eab767/ICSharpCode.CodeConverter/Util/SyntaxNodeExtensions.cs#L863) and you'll probably find an easy place to put it.

**Comment by knodel12** [comment]
@GrahamTheCoder So I tried to investigate this one, but it seems the regions don't show up during the crawl in the file you referenced.  Is there any chance that since it's a compiler directive that Roslyn doesn't see those?

**Comment by GrahamTheCoder** [comment]
Thought I'd seen it around there, but might have misremembered, I'll take a look next time I have it open

**Comment by GrahamTheCoder** [comment]
Still an issue, but I'm closing this to consolidate into #15. Since I believe there's the same issue, that Roslyn has already processed them before providing the syntax tree.
