### ISSUE TITLE
Support VS 2015 for VSIX

### ISSUE THREAD

**Issue by Abvirk** [icsharpcode/CodeConverter#191]
29-10-2018 10:40:07 PM - Microsoft VSIX Installer
29-10-2018 10:40:07 PM - -------------------------------------------
29-10-2018 10:40:07 PM - Initializing Install...
29-10-2018 10:40:07 PM - Extension Details...
29-10-2018 10:40:07 PM - 	Identifier         : 7e2a69d6-193b-4cdf-878d-3370d5931942
29-10-2018 10:40:07 PM - 	Name               : Code Converter C# to/from VB.NET
29-10-2018 10:40:07 PM - 	Author             : IC#Code
29-10-2018 10:40:07 PM - 	Version            : 6.1.0.0
29-10-2018 10:40:07 PM - 	Description        : Based on Roslyn, this converter allows you to convert C# code to VB.NET and vice versa
29-10-2018 10:40:07 PM - 	Locale             : en-US
29-10-2018 10:40:07 PM - 	MoreInfoURL        : 
29-10-2018 10:40:07 PM - 	InstalledByMSI     : False
29-10-2018 10:40:07 PM - 	SupportedFrameworkVersionRange : [4.6,)
29-10-2018 10:40:07 PM - 
29-10-2018 10:40:07 PM - 	SignatureState     : Unsigned
29-10-2018 10:40:07 PM - 	Supported Products : 
29-10-2018 10:40:07 PM - 		Microsoft.VisualStudio.Pro
29-10-2018 10:40:07 PM - 			Version : [15.0,16.0)
29-10-2018 10:40:07 PM - 		Microsoft.VisualStudio.Community
29-10-2018 10:40:07 PM - 			Version : [15.0,16.0)
29-10-2018 10:40:07 PM - 		Microsoft.VisualStudio.Enterprise
29-10-2018 10:40:07 PM - 			Version : [15.0,16.0)
29-10-2018 10:40:07 PM - 
29-10-2018 10:40:07 PM - 	References         : 
29-10-2018 10:40:07 PM - Signature Details...
29-10-2018 10:40:07 PM - 	Extension is not signed.
29-10-2018 10:40:07 PM - 
29-10-2018 10:40:07 PM - Searching for applicable products...
29-10-2018 10:40:07 PM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
29-10-2018 10:40:07 PM - Found installed product - Microsoft Visual Studio Professional 2015
29-10-2018 10:40:07 PM - Found installed product - Microsoft Visual Studio Community 2015
29-10-2018 10:40:07 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
29-10-2018 10:40:07 PM - Found installed product - Global Location
29-10-2018 10:40:07 PM - Found installed product - ssms
29-10-2018 10:40:07 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by GrahamTheCoder** [comment]
Interesting, thanks for reporting. It's possible the manifest needs tweaking to support VS2015.
If you want to troubleshoot you can unzip the vsix, tweak the manifest, rezip and try to install. If you figure out what makes it work, PR it and I'll put it in future releases.
Maybe this will help: https://stackoverflow.com/a/24348026/1128762

Obviously if you have a license then try upgrading to 2017 and it'll probably work.

**Comment by christophwille** [comment]
Does VS2015 support all the project system features that the addin uses? I think it is intentionally locked to 2017.

**Comment by GrahamTheCoder** [comment]
It's true that the extension page says it only supports 2017 so this error is expected, though I believe it was possible to get an MS extension to add Roslyn to vs2015 which could make it work, but I don't know the full details.

If someone gets it working without breaking other stuff I'll happily merge the change, though I really would recommend just updating VS wherever possible

**Comment by GrahamTheCoder** [comment]
If there's no further interest from anyone in implementing this, I'll close it at the start of 2019 to keep things tidy.
