### ISSUE TITLE
'ReConverterpackage' pacakge did not load corectly

### ISSUE THREAD

**Issue by tigrom** [icsharpcode/CodeConverter#195]
Visual Studio 2017 Professional

  | {60378C8B-D75C-4FB2-AA2B-58609D67F886} |   | VisualStudio | 2018/11/02 11:04:28.069
-- | -- | -- | -- | --
698 | ERROR | LegacySitePackage failed for package [REConverterPackage]Source: 'CodeConverter.VsExtension' Description: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Culture=neutral' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Culture=neutral' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.LanguageServices, Culture=neutral'    at CodeConverter.VsExtension.ConvertCSToVBCommand..ctor(REConverterPackage package)    at CodeConverter.VsExtension.REConverterPackage.Initialize() in D:\GitWorkspace\CodeConverter\Vsix\REConverterPackage.cs:line 100    at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)  WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

SetSite failed for package [REConverterPackage](null)

697 |   | Begin package load [REConverterPackage] | {60378C8B-D75C-4FB2-AA2B-58609D67F886} |   | VisualStudio | 2018/11/02 11:04:28.069
-- | -- | -- | -- | -- | -- | --
698 | ERROR | LegacySitePackage failed for package [REConverterPackage]Source: 'CodeConverter.VsExtension' Description: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Culture=neutral' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Culture=neutral' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.LanguageServices, Culture=neutral'    at CodeConverter.VsExtension.ConvertCSToVBCommand..ctor(REConverterPackage package)    at CodeConverter.VsExtension.REConverterPackage.Initialize() in D:\GitWorkspace\CodeConverter\Vsix\REConverterPackage.cs:line 100    at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)  WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. | {60378C8B-D75C-4FB2-AA2B-58609D67F886} | 80070002 | VisualStudio | 2018/11/02 11:04:28.071
699 | ERROR | SetSite failed for package [REConverterPackage](null) | {60378C8B-D75C-4FB2-AA2B-58609D67F886} | 80070002 | VisualStudio | 2018/11/02 11:04:28.082
700 | ERROR | End package load [REConverterPackage] | {60378C8B-D75C-4FB2-AA2B-58609D67F886} | 80070002 | VisualStudio | 2018/11/02 11:04:28.087

**Comment by tigrom** [comment]
The problem disappeared after updating visual studio 2017.

**Comment by kwhitefoot** [comment]
It was fine until today, now I have the same error.

**Comment by GrahamTheCoder** [comment]
Hi, thanks for reporting the issue. https://github.com/icsharpcode/CodeConverter/releases/tag/6.4.0 should work - I'll get it on the gallery soon
