### ISSUE TITLE
VB -> C# Decimal casted to double

### ISSUE THREAD

**Issue by vfle** [icsharpcode/CodeConverter#202]
### Input code
```vbnet
return 100D / 100D
```

### Erroneous output
```C#
{
    return 100M / (double)100M;
}
```

### Expected output
```C#
{
    return 100M / 100M;
}
```

### Details
Product in use: both

Version in use: e.g. 6.1

**Comment by GrahamTheCoder** [comment]
Ah, I previously believed that `/` is always division of doubles in Visual Basic, so I implemented it that way. I've just found https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/floating-point-division-operator#remarks which says differently.

This would be a great first issue. See the [existing tests](https://github.com/icsharpcode/CodeConverter/blob/master/Tests/CSharp/ExpressionTests.cs#L224) which may be wrong and [the implementation](https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L1349) 

There's a comment there explaining my thinking at the time, which should have a link to [the docs](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/floating-point-division-operator#remarks) above added.

**Comment by taylus** [comment]
Interesting, C# follows those same rules about operand types, doesn't it? [Its docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/division-operator) aren't as specific, but do you think just removing the rhs cast to double is sufficient?
