### ISSUE TITLE
VB -> C#: Native functions

### ISSUE THREAD

**Issue by Adam--** [icsharpcode/CodeConverter#203]
### Input code
```vbnet
Friend Declare Ansi Function GetNumDevices _
Lib "CP210xManufacturing.dll" Alias "CP210x_GetNumDevices" _
(ByRef NumDevices As DWORD) As CP210x_STATUS
```

### Erroneous output
```C#
[System.Runtime.InteropServices.DllImport(@"CP210xManufacturing.dll")]
internal static extern CP210x_STATUS GetNumDevices(ref DWORD NumDevices);
```

### Expected output
```C#
[System.Runtime.InteropServices.DllImport(@"CP210xManufacturing.dll", EntryPoint = "CP210x_GetNumDevices", CharSet = CharSet.Ansi)]
internal static extern CP210x_STATUS GetNumDevices(ref DWORD NumDevices);
```

- The VB `Alias` should be converted to the C# `EntryPoint`.
- The VB `Ansi` declaration should be converted to the C# `CharSet`.

### Details
Product in use: both

Version in use: e.g. 6.1.0

**Comment by knodel12** [comment]
Did the path to the DLL intentionally change or is that unintentional?

**Comment by Adam--** [comment]
Path should not change, that was a typo in the expected output. I've updated the sample. Thanks!

**Comment by GrahamTheCoder** [comment]
Fix should be released in a couple of weeks. If you have more examples, try them out on a development build of master or let me know since I haven't delved into all the possibilities, just this one case.
