### ISSUE TITLE
VB -> C#: Ternary Conditional Operator With Operation Converts Incorrectly

### ISSUE THREAD

**Issue by knodel12** [icsharpcode/CodeConverter#205]
### Input code
```VB
Public Class TestClass
    Public Sub TestMethod(i As Integer)
        Dim max As Integer = If(i > 5, 5, i) - 1
        Console.WriteLine(max)
    End Sub
End Class
```

### Erroneous output
```C#
public class TestClass
{
    public void TestMethod(int i)
    {
        var max = i > 5 ? 5 : i - 1;
        Console.WriteLine(max);
    }
}
```

### Expected output
```C#
public class TestClass
{
    public void TestMethod(int i)
    {
        var max = (i > 5 ? 5 : i) - 1;
        Console.WriteLine(max);
    }
}
```

### Details
Product in use: both

Version in use: e.g. 6.1.0

So, all ternary in VB are wrapped in parenthesis so any operations are performed on the result of the operator.  The C# converter doesn't wrap it in parenthesis, so any operations performed on the result end up only applying to the right side of the operator.

Any ternary operators in VB that contain anything other than the ternary operator on the same line should be wrapped in parenthesis in the C# variation.

**Comment by GrahamTheCoder** [comment]
Yep sounds good, see https://github.com/icsharpcode/CodeConverter/commit/9b6088b32ff0328ff6b6985683f1332408748f33155 and #155 for reference and other discussion around approach to similar work.

**Comment by vfle** [comment]
That regex should identify possible problems at your codebase.
`If\(.*\,.*\,.*\)\s[-+*\/]`
