### ISSUE TITLE
VB -> C# Nothing Integer/Date

### ISSUE THREAD

**Issue by vfle** [icsharpcode/CodeConverter#208]
### Input code
```vbnet
    Dim number As Integer
    number = Nothing
```

### Erroneous output
```C#
    int number;
    number = default(Integer);
```

### Expected output
```C#
    int number;
    number = default(int);
```

### Details
Product in use: both

Version in use: 6.1

Date & Nullable of both have the same problem.
Please note that date behaves different at the vs plugin than the online tool.
Checked decimal,double,string they behave correctly.

**Comment by GrahamTheCoder** [comment]
There is some shared code that does this conversion correctly in several places. Hopefully we can just reference that from this place too. Weird that it differs on web version though, could point to a bigger issue.
