### ISSUE TITLE
VB -> C# Value as parameter of function

### ISSUE THREAD

**Issue by vfle** [icsharpcode/CodeConverter#209]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```vbnet
    Public Sub MyFunction(ByVal Value As String)
            Dim test = Value
    End Sub
```

### Erroneous output
```C#
public void MyFunction(string Value)
{
    var test = value;
}
```

### Expected output
```C#
public void MyFunction(string Value)
{
    var test = Value;
}
```

### Details
Product in use: both

Version in use: 6.1

I think #102 is relevant and could be the cause of the bug?

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I believe this was fixed in #198 - I'll do a release this week so it's easy to test against a more recent version.
