### ISSUE TITLE
VB - C#: Settings.Designer not converting

### ISSUE THREAD

**Issue by user905** [icsharpcode/CodeConverter#212]
I attempted to convert  VB project to C#. It seems to have mostly worked, however, the Settings.Designer.CS file is a mess. There are roughly 500 issues related to the following showing up in the file:

`global::Microsoft.VisualBasic.ChrW(13)`

The message is:

>  | CS0234 | The type or namespace name 'ChrW' does not exist in the namespace 'Microsoft.VisualBasic' (are you missing an assembly reference?) 

### Details
Product in use: Code Converter C# to/from VB.NET

Version in use: 6.1.0.0

Visual Studio: Visual Studio Community 2017 Version 15.8.9

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Does it mention CharW in the input? Can you add a small example of the input?

**Comment by Savjiyani** [comment]
I face same Issue
You can change follow, It'll work fine
global::Microsoft.VisualBasic.ChrW(13); -> (char)13;

**Comment by GrahamTheCoder** [comment]
In the absence of the actual input, I've made the transformation @Savjiyani suggested since it seems reasonable to me and comes up in a common case (settings file). It'll be released in the next couple of weeks. Thanks both.

**Comment by user905** [comment]
My solution was to delete the file and rebuild. That seemed to work.
