### ISSUE TITLE
VB -> C# Access modifiers are not allowed on static Constructor

### ISSUE THREAD

**Issue by Savjiyani** [icsharpcode/CodeConverter#215]
VB -> C#
### Input code
```vbnet
Shared Sub New()
            INITIAL_ACCESSDATE = New Date(2001, 1, 1)
End Sub
```

### Erroneous output
```C#
public static CLoadConfig()
        {
            INITIAL_ACCESSDATE = new DateTime(2001, 1, 1);
        }
```

### Expected output
```C#
static CLoadConfig()
        {
            INITIAL_ACCESSDATE = new DateTime(2001, 1, 1);
        }
```

### Details
Product in use: VS extension/VSIX

Version in use: e.g. 6.2.0.0

In C# we can not use access modifiers like Public, Private, Protected in Static Constructor

**Comment by GrahamTheCoder** [comment]
Thanks for the very clear bug report. Should be pretty straightforward to fix - there's probably a VisitConstructor method that needs an extra if statement.

**Comment by ramil89** [comment]
This issue occurred again a VS extension (version 6.7.0)

**Input code** 
```
Module Module1

    Sub New()
        Dim someValue As Integer = 0

    End Sub

    Sub Main()

    End Sub

End Module
```


**Erroneous output**

```
static class Module1
{
    public static Module1()
    {
        int someValue = 0;
    }
 
    public static void Main()
    {
    }
}

```

**Expected output**
```
static class Module1
{
    static Module1()
    {
        int someValue = 0;
    }
    public static void Main()
    {
    }
}
```

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report. I think this case (implicitly static constructor due to being part of module) was missed in the original fix. Thanks for the clean repro, hopefully should be an easy fix.
