### ISSUE TITLE
Convert "website"s with no project file

### ISSUE THREAD

**Issue by vcd195** [icsharpcode/CodeConverter#219]
VS extension
Code converter 6.2.0.0

![file](https://user-images.githubusercontent.com/33389540/50314184-92810a00-04b6-11e9-80db-ff8890175aa8.png)
![project](https://user-images.githubusercontent.com/33389540/50314185-92810a00-04b6-11e9-8cc6-aab8de242f09.png)
![solution](https://user-images.githubusercontent.com/33389540/50314186-9319a080-04b6-11e9-9ab5-c19302f0c512.png)

Context menu "convert" item doesn't show for either solution, project or file, VS 2017 community

**Comment by GrahamTheCoder** [comment]
I suspect your solution contains only "website" projects maybe? The converter detects projects with the extension csproj or vsproj. If you added those files to a normal vbproj I'd expect it to work.

Does the context menu appear on individual vb files?

**Comment by vcd195** [comment]
Hi,
Thanks for your reply. It is indeed a website project, but the context menu item doesn't appear on individual files (in that project) as well.

**Comment by GrahamTheCoder** [comment]
I'll need to check, but it may only show the menu if the parent project of a file is one that I can (currently) get the Roslyn model from - which is required in order to do the conversion.

**Comment by GrahamTheCoder** [comment]
Related info for aspx is probably relevant here: https://github.com/icsharpcode/CodeConverter/issues/175
It's possible there is in fact a project created behind the scenes that we could get hold of and convert.

**Comment by jrmoreno1** [comment]
I have pushed a sample website to my repo at: https://github.com/jrmoreno1/TestWebsite/, it opens and runs in both 2019 and 2022.  I can confirm that the Convert to C# menu isn't showing.

**Comment by jrmoreno1** [comment]
@GrahamTheCoder : added a web application to the solution as well, just thought that might be useful addition, the website project does run analyzers, but does not have the context menu for converting.  Total WAG: could it be that you have to use the website project guid somewhere?
