### ISSUE TITLE
Error on extension load

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#227]
Product in use: VS extension
Version in use: Probably 6.2.0
VS version: 2017 - exact version unknown

2 reports nearly 2 months apart of this error, reported at https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter#qna
```
LegacySitePackage failed for package [REConverterPackage]Source: 'CodeConverter.VsExtension' Description: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Culture=neutral' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Culture=neutral' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.LanguageServices, Culture=neutral'
 at CodeConverter.VsExtension.ConvertCSToVBCommand..ctor(REConverterPackage package)
 at CodeConverter.VsExtension.REConverterPackage.Initialize() in D:\GitWorkspace\CodeConverter\Vsix\REConverterPackage.cs:line 100
 at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. 
```
---

This could be due to a change in the assemblies shipped with Visual Studio, caused by corrupt installs (or ones with certain features not installed). Needs investigation, but it's very hard without being able to repro the problem. It basically comes down to having a look in the visual studio folder for this assembly, then finding out from the fusion log why it isn't loaded.

On my machine (where this works), the assembly is this one:
```
Microsoft.VisualStudio.LanguageServices.dll	2.10.0.0
c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\commonextensions\microsoft\managedlanguages\vbcsharp\languageservices\Microsoft.VisualStudio.LanguageServices.dll
```

The version number matches with this extension in the Extensions and Updates window:
![image](https://user-images.githubusercontent.com/2490482/50903359-8208e300-1415-11e9-96e6-7d3ab926f168.png)

**Comment by randycdouglas** [comment]
I have the same assembly and the same version (2.10.0.0).

**Comment by GrahamTheCoder** [comment]
Hmm, that limits that line of thought. If you temporarily disable any other 3rd party extensions and restart VS does it still happen? If so, the next thing off to check VS version and get a fusion log to detail where the assembly was searched for and why it failed

**Comment by tjemni** [comment]
I've the same issue at my end. Looking at my ActivityLog.xml I see the following error:
` <entry>
    <record>2285</record>
    <time>2019/02/07 08:01:29.487</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [REConverterPackage]Source: &apos;Microsoft.VisualStudio.Shell.15.0&apos; Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.GetService(Type serviceType)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.EnsureVerbs()&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.FindCommand(Guid guid, Int32 id)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.FindCommand(CommandID commandID)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)&#x000D;&#x000A;   at CodeConverter.VsExtension.ConvertCSToVBCommand..ctor(REConverterPackage package, CodeConversion codeConversion, OleMenuCommandService commandService) in D:\GitWorkspace\CodeConverter\Vsix\ConvertCSToVBCommand.cs:line 85&#x000D;&#x000A;   at CodeConverter.VsExtension.ConvertCSToVBCommand.&lt;InitializeAsync&gt;d__14.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\ConvertCSToVBCommand.cs:line 66&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at CodeConverter.VsExtension.REConverterPackage.&lt;InitializeAsync&gt;d__9.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\REConverterPackage.cs:line 106&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{60378C8B-D75C-4FB2-AA2B-58609D67F886}</guid>
    <hr>80131509</hr>
    <errorinfo></errorinfo>
  </entry>`

I'm running Visual Studio 2017 15.9.5. I'm opening a .Net Framework 4.5 solution (was a .Net Core 2.0 solution, had been ported)

**Comment by GrahamTheCoder** [comment]
Hi @tjemni, thanks for all the info. I believe you're seeing #242, which I have a tentative fix for here:
https://github.com/icsharpcode/CodeConverter/releases/tag/6.4.0
Please let me know if it works for you if you have time to try it.

**Comment by tjemni** [comment]
Hi @GrahamTheCoder, release 6.4.0 starts up just fine! Thanks for the quick answer!

**Comment by GrahamTheCoder** [comment]
The dependencies and startup massively changed in 6.3. I'll close this until I hear a report from a new version and then try to get an activity log and fusion log.
