### ISSUE TITLE
VB -> C#: VB Constants should be inlined to avoid referencing Visual Basic

### ISSUE THREAD

**Issue by elGuille-MVP** [icsharpcode/CodeConverter#229]
In Visual Basic, something like this:
Return txtB.Text.Split(**vbCr**.ToCharArray()).Length

it's converted to C#:
return txtB.Text.Split(**Constants.vbCr**.ToCharArray()).Length;

or

'''vbnet

"Error al guardar:" & vbCrLf & ex.Message

'''C#
"Error al guardar:" + Constants.vbCrLf + ex.Message

I simply change the constants to C# literals:

return txtB.Text.Split("\r".ToCharArray()).Length;

"Error al guardar:\r\n" + ex.Message

**Comment by GrahamTheCoder** [comment]
If I understand correctly, there is no error here, and it is a request for a more sensible/idiomatic conversion.
I've noted this as a specific case of https://github.com/icsharpcode/CodeConverter/issues/174 and will track progress there. Thanks for the report
