### ISSUE TITLE
VB -> C# vbcrlf & vbtab

### ISSUE THREAD

**Issue by cyrianox** [icsharpcode/CodeConverter#239]
vbcrlf should be converted to 
System.Environment.NewLine
instead of 
Constants.vbCrLf

and

vbtab should be converted to 
"\t" instead of Constants.vbTab

**Comment by GrahamTheCoder** [comment]
Thanks, this is a specific case of #174 so I will track progress there. I've already consolidated a similar request. For vbcrlf, I'd guess \r\n is returned on Linux, but Newline probably acts differently, so we'll have to be a bit careful. Thanks for the report.
