### ISSUE TITLE
Error on loading extension

### ISSUE THREAD

**Issue by bodrick** [icsharpcode/CodeConverter#242]
### Details
Product in use: VS extension

Version in use: 6.3.0
Visual Studio Version: 15.9.6

Receive a popup saying ReConverterPackage failed to load and check the activitylog.xml

The error in the activity log is 

> SetSite failed for package [REConverterPackage]Source: 'Microsoft.VisualStudio.Shell.15.0' Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
> System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
>    at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
>    at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)
>    at System.ComponentModel.Design.MenuCommandService.GetService(Type serviceType)
>    at System.ComponentModel.Design.MenuCommandService.EnsureVerbs()
>    at System.ComponentModel.Design.MenuCommandService.FindCommand(Guid guid, Int32 id)
>    at System.ComponentModel.Design.MenuCommandService.FindCommand(CommandID commandID)
>    at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)
>    at CodeConverter.VsExtension.ConvertCSToVBCommand..ctor(REConverterPackage package, CodeConversion codeConversion, OleMenuCommandService commandService) in D:\GitWorkspace\CodeConverter\Vsix\ConvertCSToVBCommand.cs:line 85
>    at CodeConverter.VsExtension.ConvertCSToVBCommand.<InitializeAsync>d__14.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\ConvertCSToVBCommand.cs:line 66
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CodeConverter.VsExtension.REConverterPackage.<InitializeAsync>d__9.MoveNext() in D:\GitWorkspace\CodeConverter\Vsix\REConverterPackage.cs:line 106
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass17_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()

**Comment by GrahamTheCoder** [comment]
Thanks very much for the report - the stack trace was very helpful. Hopefully the commit I've just added to master will fix it. Though potentially you'll hit other errors further in to the load process. I'm just trying it in VS2017 now to see if I can find any errors further through the load. Let me know if you come across any other errors (either now on a dev build, or when it's released)

**Comment by bodrick** [comment]
I can confirm this fixes the issue I reported and the extension once again works in VS2017.
