### ISSUE TITLE
Null project file name during project conversion

### ISSUE THREAD

**Issue by skitscha** [icsharpcode/CodeConverter#243]
When I attempt to convert a Vb.net project to C#, I get the error in the picture below
![image](https://user-images.githubusercontent.com/25359125/52661770-5d969f80-2ec8-11e9-9565-20143feefd41.png)

**Comment by GrahamTheCoder** [comment]
Thanks for the bugreport, it's probably an issue with reading the projects that reference the one being converted. Until I have time to look into it you might be able to temporarily remove those projects from your solution prior to conversion as a workaround.

**Comment by GrahamTheCoder** [comment]
Could be related to #173. Definitely worth trying a vs restart if you haven't already.

**Comment by GrahamTheCoder** [comment]
I think my first comment about Website projects (and maybe some other types) was correct. I've pushed a likely fix based on that. Feel free to try it out when it's built by grabbing the artifact from here: https://ci.appveyor.com/project/icsharpcode/codeconverter/builds/22333367
