### ISSUE TITLE
VB => C#: Output Switch expression without parentheses

### ISSUE THREAD

**Issue by FFouetil** [icsharpcode/CodeConverter#246]
### Input code
```vbnet
Select Case elem.Type
	Case SomeEnum.A
                'somecode
	Case SomeEnum.B
                'somecode
End Select
```

### Erroneous output
```C#
switch elem.Type
{
	case SomeEnum.A:
                {
                //somecode
                break;
                }
	case SomeEnum.B:
                {
                //somecode
                break;
                }
}
```

### Expected output
```C#
switch (elem.Type) //<= parentheses here
{
	case SomeEnum.A:
                {
                //somecode
                break;
                }
	case SomeEnum.B:
                {
                //somecode
                break;
                }
}
```

### Details
Product in use: only tested VS extension, v6.4.0
Problem also applies to non-enum integers and strings

Feel free to contact me if you need more details. That's a really nice job your doing there, it would be a shame to leave that unfixed :)

**Comment by GrahamTheCoder** [comment]
There were quite a few changes to parenthesization recently and I think one of them probably caused this. Should be an easy fix, I'm amazed an existing test didn't catch it. Thanks for the bug report!

**Comment by FFouetil** [comment]
No problem! What It's more surprising to me is that no one else reported it
when I checked for an existing ticket.
I'll try and convert a whole projet when the extension is fixed. Big
projects in VB are a pain to maintain when it comes to readability...

Good job on that tool :)

**Comment by GrahamTheCoder** [comment]
After a few attempts I can't reproduce the error. Would you be able to add some more code to the example such that it produces erroneous output when converted here: https://codeconverter.icsharpcode.net/
Thanks!

**Comment by FFouetil** [comment]
Ok I'll get back to you as soon as I find a moment to do it.
Is it possible that the behavior is slightly different in the VS extension?
I was using VS2019 btw, maybe it matters in this case

**Comment by FFouetil** [comment]
Well, I tried with your online converter with a similar case and it worked
correctly. Though I noticed that the converter version at the bottom of the
page shows 6.3.
My problem happened on the VS extension 6.4, on 2019 Preview 3.

I just tried again on a clean project. Created a VBTest.vb file and
right-clicked it to do Convert to C# from the solution explorer.

VB code:
Public Class VBTest

    Enum TestEnum
        A = 0
        B = 1
    End Enum
    Sub Method(i As TestEnum)

        Select Case i
            Case TestEnum.A : Method(i + 1)
            Case TestEnum.B : Method(i + 1)
        End Select

    End Sub
End Class

Output C# code:
public class VBTest
{
    enum TestEnum
    {
        A = 0,
        B = 1
    }
    public void Method(TestEnum i)
    {
        switch i //<= still not parenthesized
        {
            case TestEnum.A:
                {
                    Method(i + 1);
                    break;
                }

            case TestEnum.B:
                {
                    Method(i + 1);
                    break;
                }
        }
    }
}

HOWEVER:
If the input Select Case has parentheses, the output code keeps them as
well!

Thing is, I don't see myself update Select Case parameters in the company
code that spans over 50K badly written lines.
Refactoring options are very lacky in VB compared to C#, so the only
"automated" thing I could come with would be a global Regex Replace,
but you know what they say about regex...

**Comment by GrahamTheCoder** [comment]
Thanks for putting that example together. Good spot that the versions are different, though that turned out not to be the issue. I can now reproduce the error when running the latest code in master inside VS 2019 preview (but not in the web converter). An issue at this particular level means it's very likely to be a "change in behaviour" (probably a bug) in the Roslyn libraries that are part of VS2019. I'll investigate further to try to find a workaround for you and report the issue upstream if necessary.

**Comment by GrahamTheCoder** [comment]
There's a workaround in the latest development build which you should be able to find here shortly:
https://ci.appveyor.com/project/icsharpcode/codeconverter/branch/master/artifacts
Let me know if that fixes the issue for you.

I'll do some more investigation to see if anything else is broken and see if I can report and help fix the issue in Roslyn.

**Comment by FFouetil** [comment]
Sorry for the late reply, I had a quite a busy day.
I just tested your dev build, and it seems your trick worked. I know get
"switch (i)" instead of "switch i" :)
Thanks for the fix, I think you can report them what you know. Glad I could
help you spot it

👍
