### ISSUE TITLE
C# -> VB: Namespace not converted correctly

### ISSUE THREAD

**Issue by jdmichel** [icsharpcode/CodeConverter#248]
VB namespaces are appended to the namespace from the project settings.
So, if the project settings have namespace A.B.C, and the original C# code had:
```
namespace A.B.C.D {
     class E {
     }
}
```
Then the correct VB translation is:
```
Namespace D 
     Class E 
     End Class
End Namespace
```
The current conversion with `Namespace A.B.C.D` results in a full class name of A.B.C.A.B.C.D.E.

Converter version 6.4

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I'm very happy to accept a PR, but if not, I will try to get around to it at some point 😄

**Comment by GrahamTheCoder** [comment]
I believe https://github.com/icsharpcode/CodeConverter/pull/450 fixed this
