### ISSUE TITLE
Installation Failing with "File contains corrupted data"

### ISSUE THREAD

**Issue by vdykcj** [icsharpcode/CodeConverter#250]
I have downloaded the extension from MarketPlace but it fails to install with an error message stating 'This is not a valid VSIX package'

![image](https://user-images.githubusercontent.com/30402414/53622105-6d6cee00-3c01-11e9-8a98-db840db088ab.png)

Install log attached.

[VSIXInstaller_eb1c4e89-c48b-4021-a0a7-2eda45b31bdf.log](https://github.com/icsharpcode/CodeConverter/files/2918282/VSIXInstaller_eb1c4e89-c48b-4021-a0a7-2eda45b31bdf.log)

**Comment by GrahamTheCoder** [comment]
Thanks. Not sure why that is happening, I'll try to investigate soon!

**Comment by GrahamTheCoder** [comment]
Your log file says "File contains corrupted data". I've checked that the uploaded file is fine and no-one else has reported the issue, so it's likely a problem during your download. Try downloading it again from the site.
On the file properties page, it should say "Size: 4.08 MB (4,279,936 bytes)"
The SHA-256 hash of the file is `C9A7A438963FD24F8535006C6E817E072D296AC9401B2F125921E538F337BC62`
If that still doesn't work, try downloading from GitHub: https://github.com/icsharpcode/CodeConverter/releases/tag/6.4.0

Either way, please post back and let me know whether it works, good luck!

**Comment by GrahamTheCoder** [comment]
I've just shipped a new version of the extension and verified it installs correctly on both VS2017 and VS2019 preview 3. Please post back here if you see the same issue again. Thanks for getting in touch.

**Comment by vdykcj** [comment]
Thanks a stack. Downloaded latest version and it installed without any issues. Much appreciated.
