### ISSUE TITLE
String interpolation format not converted

### ISSUE THREAD

**Issue by francescoformenti** [icsharpcode/CodeConverter#255]
In conversion from VB to C#, when using string interpolation, the format after the colon ":" is lost

### Input code
```vbnet
Public Function Test() As String
	Return $"{DateTime.Now:yyyyMMdd}"
End Function
```

### Erroneous output
```c#
public string Test()
{
    return $"{DateTime.Now}";
}
```

### Expected output
```c#
public string Test()
{
    return $"{DateTime.Now:yyyyMMdd}";
}
```

### Details
Product in use: web converter

Edit: tested also the C# to VB conversion, the conversion error is present here too

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Should just be a case of finding the methods dealing with interpolation and pushing an extra argument through. Let me know if you're interested in fixing it, otherwise I'll try to get it into a release in the next month or so.

**Comment by francescoformenti** [comment]
> Let me know if you're interested in fixing it, otherwise I'll try to get it into a release in the next month or so.

I downloaded the source code, but it's a nightmare for me..
I tried to debug step by step but didn't find where I should change something, I think I am missing too much background knowledge to accomplish this, sorry

**Comment by GrahamTheCoder** [comment]
Ok, no worries. Yeah there is obviously a fair amount of context to fully understand everything happening. If you're interested in seeing just this part of it, search "interpolation" in the code base, put a breakpoint when converting the problem code, then look at the inputs and outputs of the method.
https://github.com/icsharpcode/CodeConverter/search?utf8=✓&q=interpolation&type=

**Comment by francescoformenti** [comment]
I tried again and something has changed.. the VB -> C# conversion now works fine, but the C# -> VB conversion still presents the problem.. I don't understand why, since I did not change anything in source code..
If you try to use the telerik converter [(http://converter.telerik.com/),](http://converter.telerik.com/) that is based on this code, the conversion error is still present, maybe it is using an older version of the sources.
So I think that only C# -> VB needs a fix
Thanks for your time, your work is very appreciated!

**Comment by GrahamTheCoder** [comment]
Ah yes I did probably fix that recently while looking at another issue in the area. Yeah, the Telerik clone is generally very out of date.

I'll take a look soon, thanks!
