### ISSUE TITLE
VB -> C#: Fix casing

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#258]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```vbnet
Public Class Class1
    Sub Bar()

    End Sub

    Sub Foo()
        bar()
    End Sub
End Class
```

### Erroneous output
```c#
public class Class1
{
    public void Bar()
    {
    }

    public void Foo()
    {
        bar();
    }
}
```

### Expected output
```vbnet
public class Class1
{
    public void Bar()
    {
    }

    public void Foo()
    {
        Bar();
    }
}
```

### Details
Product in use: VS extension

Version in use: 6.6.0

Visual Basic is case insensitive. When converting code to C#, it should fix the casing of method calls, properties, etc.

**Comment by GrahamTheCoder** [comment]
Thanks for all the reports. I'll look into them more carefully soon. They appear to have good repros - the effort is much appreciated. Let me know if you're interested in tackling any of them - I'm happy to assist in learning.

**Comment by mrmonday** [comment]
Extra case:

```vbnet
Public Interface I
    Public Function Foo() As Integer
End Interface
 
Public Class C
    Implements I
 
    Public Function foo() As Integer
        Return 0
    End Function
End Class
```

**Comment by GrahamTheCoder** [comment]
Thinking about this, we might get a lot of the way there with a small tweak to ConvertIdentifier to check the case of the symbol:
https://github.com/icsharpcode/CodeConverter/blob/28e5607c121d05a0da710d4eea5c94e9457db26b/ICSharpCode.CodeConverter/CSharp/CommonConversions.cs#L286
There may well then be a long tail of edge cases that circumvent that path, but it'd be a good start.

**Comment by mrmonday** [comment]
Ha, you made that comment just as I opened a PR doing just that ;)
