### ISSUE TITLE
VB -> C#: Missing parenthesis when converting string concatenation

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#262]
### Input code
```vbnet
Public Class Class1
    Sub Foo()
        Dim x = "x " & 5 - 4 & " y"
    End Sub
End Class
```

### Erroneous output
```c#
public class Class1
{
    public void Foo()
    {
        var x = "x " + 5 - 4 + " y";
    }
}
```

### Expected output
```c#
public class Class1
{
    public void Foo()
    {
        var x = "x " + (5 - 4) + " y";
    }
}
```

### Details
Product in use: e.g. VS extension

Version in use: e.g. 6.6.0

The converted code gives this error:

```
CS0019	Operator '-' cannot be applied to operands of type 'string' and 'int'
```

Adding parenthesis fixes the error.

**Comment by GrahamTheCoder** [comment]
Hopefully just a case of calling https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L1000 from https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L1380
