### ISSUE TITLE
VB -> C#: Indexing treated as method call

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#272]
### Input code
```vbnet
Imports System.Linq

Public Class Class1
    Sub Foo()
        Dim y = "".Split(","c).Select(Function(x) x)
        Dim z = y(0)
    End Sub

End Class
```

### Erroneous output
```c#
using System.Linq;

public class Class1
{
    public void Foo()
    {
        var y = "".Split(',').Select(x => x);
        var z = y(0);
    }
}
```

### Expected output
```c#
using System.Linq;

public class Class1
{
    public void Foo()
    {
        var y = "".Split(',').Select(x => x);
        var z = y[0];
    }
}
```

### Details
Product in use: VS extension

Version in use: 6.6.0

The indexing should use square brackets rather than parenthesis.

**Comment by GrahamTheCoder** [comment]
Probably a fix in a similar place to https://github.com/icsharpcode/CodeConverter/issues/266
The fact both of these appeared sounds like there's been a regression, so definitely worth looking at the file history in that area.
