### ISSUE TITLE
The plugin fails silently if Visual Studio is out of date.

### ISSUE THREAD

**Issue by Python-Regius** [icsharpcode/CodeConverter#277]
I have Visual Studio 2017 and the plugin did not work until upgrading from 15.9.8 to 15.9.11. Would it make sense to display an error message if VS is out of date and not compatible with this plugin?

**Comment by GrahamTheCoder** [comment]
Can you confirm you have version 6.6 of the extension installed?
There was a commit in there intended to do exactly this: https://github.com/icsharpcode/CodeConverter/commit/ace56fb9e02f364050f81141c401cb98becc4fc5

If that's not working I think I might just downgrade the references to be more backwards compatible.

**Comment by Python-Regius** [comment]
Yes, I downloaded the file and verified that it had the same md5sum as the file I ran earlier today.
The md5sum is: 4ad9c517c034c089e51d3297fd81f87e
Also the URL contains a "6.6" sub-string. Also when I had the old version of Visual Studio and I checked the list of plugins I saw that I already had the Roslyn Language Service. Looking at the commit I don't think I would have got the error message because I had the language service and because I had a later version of Visual Studio.

One thing that I did not consider when originally writing this issue: maybe there was an issue with my installation of Visual Studio and the upgrade resolved it. I have no way of verifying this though.

**Comment by GrahamTheCoder** [comment]
Thanks for the extra info. I'm looking into whether I can downgrade the dependencies back to allow more versions of VS 2017 now.

**Comment by Python-Regius** [comment]
Thank you for getting to my issue so fast. I have been using this plugin a lot already and it is amazing.

**Comment by GrahamTheCoder** [comment]
Thanks for reporting it, I'm glad you're finding it useful!
