### ISSUE TITLE
VB -> C#: Create loop variable in loop initializer where possible

### ISSUE THREAD

**Issue by dftbaustin** [icsharpcode/CodeConverter#279]
On many of the C# output files, I get the VB upper loop boundary assigned as a separate variable before the C# for loop. Is there a reason why this extension does this?
### Input VB file
```vb
For y As Integer = 0 to NumYears - 1
    ' loop actions...
Next y
```

### Output C# file
```cs
int loopTo = NumYears - 1; // why is this variable necessary?
for (int y = 0; y <= loopTo; y++)
{
    // loop actions...
}
```

### Details
Product in use: VS extension
Version in use: 6.7.0.0

**Comment by GrahamTheCoder** [comment]
Hi, thanks for getting in touch. Hopefully looking at https://github.com/icsharpcode/CodeConverter/issues/177 should explain why this is done in general.
I've currently implemented a very conservative approximation of when the loop variable must be extracted.
I'd be happy to accept a pr improving that approximation.
E.g. where the loop condition depends on a local variable which doesn't change within the loop.

**Comment by dftbaustin** [comment]
After looking at #177, I understand why now! The project I work on has numerous `for` loops, but I don't think any of them have their boundaries change in the middle of the loop like the example you showed me. The problem I'm concerned about is that the variables are used only once and having a lot of `loopToX` variables may waste resources. (I'm not sure how C# manages memory.) Perhaps the generated C# code should look like this so the `loopTo` variable is kept in scope?
```cs
for (int y = 0, loopTo = NumYears - 1; y <= loopTo; y++)
{
    // loop actions...
}
```
I would really like to submit a pull request, but I'm currently busy finishing the .NET project before the end of the month.

**Comment by dftbaustin** [comment]
(I did test the example on #177 using a scoped variable and it does output as expected.)

![image](https://user-images.githubusercontent.com/10902417/55965742-2ed94300-5c45-11e9-9c1d-16937b7da93f.png)

**Comment by GrahamTheCoder** [comment]
I'd be happy for it to be changed to your example of defining the boundary within the loop, perhaps looks slightly neater, and closer to the VB.

#### Performance
* It's generally not worth worrying about resources in the case of local variables that are simple value types, they'll be gone once the method finishes.
* Having the variable extracted means you're likely to get a (very small) performance gain by not recalculating the loop condition. Again, in general, not worth worrying about and in certain cases, the compiler or jitter might well have made this micro-optimization anyway.

It's only a really extreme case where you'd need to worry about performance of cases like this, and it's definitely a case of profiling your particular application at that point.
