### ISSUE TITLE
VB -> C#: Converter does not add project reference to Microsoft.VisualBasic

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#292]
When converting, some converted code references `Microsoft.VisualBasic`. If this happens, there should be a reference to this DLL added to the `.csproj` that was output.

**Comment by GrahamTheCoder** [comment]
It may be worth adding the reference to the C# compilation in the second pass too, to increase semantic information. 
https://github.com/icsharpcode/CodeConverter/blob/1c5eee5044726bd3b1e274d7c461bcef8431fde3/ICSharpCode.CodeConverter/Shared/ProjectConversion.cs#L60-L61

In both cases I think it'd be fine to always add it. I expect it'll be needed in a large number of cases, and having an extra unused reference is so much better than not having it when you need it (if we miss a case it was needed)
