### ISSUE TITLE
VB -> C#: Assignment return support for properties

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#295]
### Input code
```vbnet
Public Class Class1
    Public ReadOnly Property Foo() As String
        Get
            Foo = ""
        End Get
    End Property
End Class
```

### Erroneous output
```c#
public class Class1
{
    public string Foo
    {
        get
        {
            Foo = "";
        }
    }
}
```

### Expected output
```c#
public class Class1
{
    public string Foo
    {
        get
        {
            string FooRet;
            FooRet = "";
            return FooRet;
        }
    }
}
```

**Comment by GrahamTheCoder** [comment]
That is rather surprising behaviour. If there's a setter too, would it use that to actually assign to Foo and then return default? Or still do the same thing?
Sounds like a good one for a self verifying test in ExpressionTests.vb so someone like me doesn't come along with the wrong idea about what happens and try to "fix" it.

**Comment by mrmonday** [comment]
https://github.com/icsharpcode/CodeConverter/pull/302/files#r278278050

Code in case it gets lost:

```vbnet
Imports System
				
Public Module Module1
	Public Sub Main()
		Console.WriteLine(X) '8
	End Sub
	
	Public ReadOnly Property X As String
		Get
			X = 4
			X = X * 2
			Dim y = "random variable to check it isn't just using the value of the last statement"
		End Get
	End Property
	
End Module
```

**Comment by GrahamTheCoder** [comment]
Just need to add the test, then change from MethodBlockSyntax to MethodBlockBaseSyntax here:
https://github.com/icsharpcode/CodeConverter/pull/302#discussion_r278773985
If it works then yay, merge, otherwise debug.
