### ISSUE TITLE
VB -> C#: Properties with parameters

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#296]
### Input code
```vbnet
Public Class Class1
    Public ReadOnly Property Foo(ByVal i As Integer) As String
        Get
            If i < 10 Then
                Return ""
            Else
                Return ""
            End If
        End Get
    End Property
End Class
```

### Erroneous output
```c#
public class Class1
{
    public string Foo
    {
        get
        {
            if (i < 10)
                return "";
            else
                return "";
        }
    }
}
```

### Expected output
```c#
public class Class1
{
    public string Foo(int i)
    {
            if (i < 10)
                return "";
            else
                return "";
    }
}

```

### Details

There might be a better way to convert this. I know if you want to call a VB property with an argument from C#, you would usually use `class1.get_Foo()` here.

**Comment by GrahamTheCoder** [comment]
There was some discussion there about solutions here: https://github.com/icsharpcode/CodeConverter/issues/200

I think this is a dupe, so I'll close it and we'll continue the discussion there

**Comment by GrahamTheCoder** [comment]
Thanks for filing all these by the way, and for all the fixes so far. Sorry I only have time to play a supporting role right now. Next month should be quieter so hopefully I'll have time to do more.
