### ISSUE TITLE
VB -> C#: String comparison behaviour does not match VB

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#308]
### Input code
```vbnet
Class Class1
    Sub Main()
        Dim s1 As String = Nothing
        Dim s2 As String = ""
        If s1 <> s2 Then
            Throw New Exception()
        End If
    End Sub
End Class
```

### Erroneous output
```c#
public class Class1
{
    public static void Main()
    {
        string s1 = null;
        string s2 = "";
        if (s1 != s2)
            throw new Exception();
    }
}
```

### Expected output
```c#
using Microsoft.VisualBasic.CompilerServices;

public class Class1
{
    public static void Main()
    {
        string s1 = null;
        string s2 = "";
        if (Operators.CompareString(s1, s2, TextCompare: false) != 0)
            throw new Exception();
    }
}
```

### Details

In VB, the code does not throw. In the current C#, it does throw.

In VB, `null` and `string.Empty` compare as the same.

The value of the `TextCompare` parameter depends on whether `Option Compare Text` or `Option Compare Binary` is set (I believe it defaults to Binary).

Unless we're dealing with literals, I don't think there's any way to automatically clean this up.

Source for `CompareString`: https://github.com/dotnet/corefx/blob/90dc9459b8eaf0c8ac93440e58c7535c67dacc22/src/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/CompilerServices/Operators.vb#L845-L883

**Comment by GrahamTheCoder** [comment]
More specific case of #105 . In this case I'll close as duplicate.

**Comment by GrahamTheCoder** [comment]
Thanks!
