### ISSUE TITLE
Online snippet converter down?

### ISSUE THREAD

**Issue by ltdeta** [icsharpcode/CodeConverter#313]
website [Online snippet converter](https://codeconverter.icsharpcode.net/)

the website is no longer available

Service Unavailable
HTTP Error 503. The service is unavailable.

**Comment by GrahamTheCoder** [comment]
Oh dear, it's still down. @christophwille : has anything changed? I'm pretty sure I checked it after the recent release

**Comment by christophwille** [comment]
Seems like a hard crash (the app pool was stopped indicating excessive failures). This does happen sometimes.
