### ISSUE TITLE
C# -> VB: Form designer compiles with errors + Missing types

### ISSUE THREAD

**Issue by ad48hp** [icsharpcode/CodeConverter#315]
https://github.com/mashmawy/FastStyleTransfer

This repository compiled with many errors, especially in the designer parts..
In some parts, it also missed type preface, for example..

```
Using wrapMode = New ImageAttributes()
End Using
```

should be written as

```
Using wrapMode As New ImageAttributes()
End Using
```

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I would have assumed either format of using statement would be valid.
Let me know if you're interested in working on a fix.
So it's easier to keep track, I'll consolidate this as a test case for #170
