### ISSUE TITLE
VB -> C# Default namespace duplicated

### ISSUE THREAD

**Issue by ezin82** [icsharpcode/CodeConverter#318]
"VB -> C#: " I have created a sample project in VB.NET with default namespace VbLibrary.

### Input code
```vbnet
Namespace A.B
    Public Class Class1
    End Class
End Namespace
```

### Erroneous output
```C#
namespace VbLibrary
{
    namespace VbLibrary.A.B
    {
        public class Class1
        {
        }
    }
}
```

### Expected output
```C#
namespace VbLibrary.A.B
{
    public class Class1
    {
    }
}
```

### Details
Product in use: VS extension 

Version in use:  6.8.0

If namespaces are nested It works correctly

### Input code
```vbnet
Namespace A
    Namespace B
        Public Class Class1
        End Class
    End Namespace
End Namespace
```

### Output code
```C#
namespace VbLibrary
{
    namespace A
    {
        namespace B
        {
            public class Class1
            {
            }
        }
    }
}
```

**Comment by GrahamTheCoder** [comment]
Thanks for the report, reopening #201 since it has the history of this issue

**Comment by GrahamTheCoder** [comment]
If you're interested in fixing it, it should be reasonably easy with that context, otherwise I'll hopefully get around to it in the next month or two
