### ISSUE TITLE
VB -> C#: Log when *.vb files not converted due to not being in the solution directory

### ISSUE THREAD

**Issue by gbrlcrpntr** [icsharpcode/CodeConverter#319]
### .vb files not being converted to c# during project level conversion

Representative output (somewhat edited) shows only the vbproj file and referencing assemblies getting converted :
```C#
--------------------------------------------------------------------------------

* C:\*\GenericHelpersVB.csproj

Creating backups and overwriting files:
* list of referencing projects

Code conversion completed
46 files have been written to disk.
```
![vbc#conversion](https://user-images.githubusercontent.com/50801399/58967566-557eaa80-87ac-11e9-90a6-bc255e7baecb.png)

It looks like the vbproj file is succesfully converted as the expected .cs files appear in the solution explorer, but are missing on disk.

### Details
Reproduced using extension version 6.8.0.0 in VS 2017 & 2019.
Also tried with Nuget (same issue)
Conversion of c#=> vb seemed to work fine at project level,
as did vb => c# at the file level.

**Comment by GrahamTheCoder** [comment]
Thanks for the very thorough report. I've never seen this issue before and it sounds very bad, so I will hopefully have time to investigate this weekend fully

**Comment by GrahamTheCoder** [comment]
I couldn't reproduce this on a totally new vb winforms project. Could you check whether that works for you? If it does, there must be something special about the project you're converting. If not, then the easiest way to troubleshoot is to run a debug build of the code converter, put a breakpoint around here and see what the converted files look like:
https://github.com/icsharpcode/CodeConverter/blob/master/Vsix/CodeConversion.cs#L82

Looking at the code, if it says "46 files have been written to disk" there should be 46 preceding lines listing those files. Can you confirm the number of referencing projects omitted? i.e. is it 45? If not, I don't know what's happening. If so, the conversion is possibly returning an empty code result but with no error.

**Comment by gbrlcrpntr** [comment]
Thanks for the quick response.
Set myself up for debugging and tried it on a test solution (empty console project), where it worked fine.
Issue remains in the original solution though. The number of files/referencing projects looks correct, and the only files being considered for conversion are the project and solution files.
![image](https://user-images.githubusercontent.com/50801399/59201539-8dae3080-8b92-11e9-9460-41851309ea64.png)

Will attempt some more debugging, but any insights into what in the project setup might be stopping files being considered would be much appreciated.

**Comment by GrahamTheCoder** [comment]
Ah thanks for the screenshot, very helpful!
It seems most likely to be this line :
https://github.com/icsharpcode/CodeConverter/blob/c70e6aa421e5c93bcb2fe19c3d428fcad82a0f01/ICSharpCode.CodeConverter/Shared/ProjectConversion.cs#L92

Are the files to be converted within the solution directory? There's a check there to avoid converting other unexpected stuff. The check doesn't currently log this behaviour to the console, but it should be changed to do so!

If that turns out to be the issue you can workaround the issue by just removing that condition from the code for now.

**Comment by gbrlcrpntr** [comment]
That was the issue, thank you very much for the help debugging.

**Comment by GrahamTheCoder** [comment]
I'll leave this open as a reminded to log the behaviour so it doesn't confuse people in future.

**Comment by GrahamTheCoder** [comment]
I've removed this behaviour
