### ISSUE TITLE
VB -> C#: Tidy up Select-Case to C# switch-case-when

### ISSUE THREAD

**Issue by RobEin** [icsharpcode/CodeConverter#323]
Original VB.net code (Case Else branch cannot be executed):
```vbnet
Dim rand As New Random
Select Case rand.Next(8)
	Case Is < 4
	Case 4
	Case Is > 4
	Case Else
End Select
```

Wrongly converted C# code (default branch can be executed!):
```csharp
Random rand = new Random();
switch (rand.Next(8))
{
	case object _ when rand.Next(8) < 4:
		{
			break;
		}
	case 4:
		{
			break;
		}
	case object _ when rand.Next(8) > 4:
		{
			break;
		}
	default:
		{
			break;
		}
}
```

Suggested C# code (default branch cannot be executed):
```csharp
Random rand = new Random();
var switchExpr = rand.Next(8);		
switch (switchExpr)
{
	case object _ when switchExpr < 4:
		{
			break;
		}
	case 4:
		{
			break;
		}
	case object _ when switchExpr > 4:
		{
			break;
		}
	default:
		{
			break;
		}
}		
```

**Comment by GrahamTheCoder** [comment]
Thanks for raising this, I agree with the suggested solution.

I've edited the description to add the code formatting from the template back -  I've noticed quite a few people delete it but I find it useful. For my future reference, is there anything I could have done to encourage you to fill in the existing template (that's a very similar format to what you've written)?

**Comment by GrahamTheCoder** [comment]
I implemented this, but I'm reopening because I realize a better conversion would be:
```csharp
Random rand = new Random();
switch (rand.Next(8))
{
	case int case1 when case1 < 4:
		{
			break;
		}
	case 4:
		{
			break;
		}
	case int case2 when case2 > 4:
		{
			break;
		}
	default:
		{
			break;
		}
}		
```

**Comment by RobEin** [comment]
Yes, this is a better conversion.
The encapsulation to the case section is safer.
