### ISSUE TITLE
Logic error when converting ByRef parameters

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#324]
Originally reported on [a wordpress comment](https://grahamthecoder.wordpress.com/about/#comment-89).

### Input code
```vbnet
Public Class MyTestClass

	Private Property Prop As Integer
	Private Sub TakesRef(ByRef vrbTst As Integer)
            vrbTst = vrbTst + 1
	End Sub

	Private Sub UsesRef(someInt As Integer)
		TakesRef(Prop)
		someInt += 1
	End Sub
End Class
```

### Erroneous output

```csharp
public class MyTestClass
{
    private int Prop { get; set; }
    private void TakesRef(ref int vrbTst)
    {
        vrbTst = vrbTst + 1;
    }

    private void UsesRef(int someInt)
    {
        var argvrbTst = Prop;
        TakesRef(ref argvrbTst);
        someInt += 1;
    }
}
```

### Expected output
```csharp
public class MyTestClass
{
    private int Prop { get; set; }
    private void TakesRef(ref int vrbTst)
    {
        vrbTst = vrbTst + 1;
    }

    private void UsesRef(int someInt)
    {
        var argvrbTst = Prop;
        TakesRef(ref argvrbTst);
        Prop = argvrbTst; // Need to set value of property afterwards to maintain logic
        someInt += 1;
    }
}
```

### Details
Should also:
* Create self-verifying tests to check cases where an implicit type conversion happens
* Check what happens when semantic info is incomplete (that it "errs" in the sensible direction)

See https://github.com/icsharpcode/CodeConverter/blob/c70e6aa421e5c93bcb2fe19c3d428fcad82a0f01/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L1460-L1469

If this solution is implemented, we should also bear in mind #310

**Comment by tverweij** [comment]
The expected output is still incorrect.
In this case the byRef method does not have a result - and makes it correct, but when the method has a result, the sequence of events is not correct

Changed the VB code to have a result:
Public Class MyTestClass

        Private SomeField As String
	Private Property Prop As Integer
	Private Function TakesRef(ByRef vrbTst As Integer) As String
            vrbTst = vrbTst + 1
            Return "Foo"
	End Sub

	Private Sub UsesRef(someInt As Integer)
		SomeField = TakesRef(Prop)
                someInt += 1;
	End Sub
End Class

The sequence that happens in UsesRef is:
1. Prop is copied to a local
2. TakesRef is called with this local
3. The local is copied back to Prop
4 SomeField is assigned

In the proposed solution step 3 and 4 are reversed, and that can (and will) cause changes in behavior when the code is called asynchronously.

The only way to get the correct behavior is to use one extra local to store the returnvalue:

    private void UsesRef(int someInt)
    {
        var argvrbTst = Prop;
        var resltvrTst = TakesRef(ref argvrbTst);
        Prop = argvrbTst; // Need to set value of property afterwards to maintain logic
        SomeField = resltvrTst; //now copy the result to preserve the proper sequence of events
        someInt += 1;
    }

**Comment by GrahamTheCoder** [comment]
Sorry I somehow missed this comment. You're absolutely right about the difference in logic for the solution I proposed. Now you've pointed that out, it brings to mind some further issues.

Imagine that TakesRef is implemented like this:
```vbnet
	Private Function TakesRef(ByRef vrbTst As Integer) As String
            vrbTst = vrbTst + 1
            Throw New Exception
	End Function
```
We'd also need a try...finally block at each call site to assign the result back like it would have been if it was a real ref

Now imagine TakesRef is implemented like this:
```vbnet
	Private Function TakesRef(ByRef vrbTst As Integer) As String
            vrbTst = vrbTst + 1
            vrbTst = vrbTest + Prop
            Throw New Exception
	End Function
```
Now we're really stuck. We can't possibly get the correct value for Prop within the method if we're only setting it after the method call.

Therefore I think the correct solution here is to output a property with a backing field (with the same accessibility) and pass that field by ref where needed. It'd be interesting to know if this works cross-project in VB, and if so, what the compiled IL looks like.

**Comment by tverweij** [comment]
If you look at the IL when compiling the Vb code, you see that VB is compiling exactly as I mentioned it.

Your example won’t change the var as it is copied back after the call.

**Comment by GrahamTheCoder** [comment]
Consolidating #310 which would also be covered by the backing field solution

**Comment by GrahamTheCoder** [comment]
Ah thanks for checking, that's very interesting - I'm surprised the VB team went with that solution!
Obviously the implementation you suggested is the best to emulate it then.

**Comment by GrahamTheCoder** [comment]
Consolidating #531 into this, either a duplicate or a variant with missing semantic info
