### ISSUE TITLE
VB -> C#: Error converting array indexer, getting round brackets instead of squre

### ISSUE THREAD

**Issue by dmzaharov** [icsharpcode/CodeConverter#325]
### Input code
```vbnet
Sub Main()
	Dim str2 = GetStrings(1)
End Sub

Function GetStrings() As String()
	Return New String() {"A", "B", "C"}
End Function
```
### Erroneous output
```csharp
public static void Main()
{
   var str2 = GetStrings(1);  // should be GetStrings()[1]
}

public static string[] GetStrings()
{
  return new string[] { "A", "B", "C" };
}
```
### Expected output
```csharp
public static void Main()
{
   var str2 = GetStrings()[1];
}

public static string[] GetStrings()
{
  return new string[] { "A", "B", "C" };
}
```
### Details
Two problems actually: 
1) Array indexing brackets become converted into round brackets, instead of square.
2) Parameterless method call empty round brackets are missing.

Version in use: 6.9.0

Interested in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for reporting this and you're interest in fixing it. The relevant bits of code for the two issues are listed below.

https://github.com/icsharpcode/CodeConverter/blob/62961fdd7b256bd2d77ccba35ba6be06a9fd5768/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L1795-L1799

https://github.com/icsharpcode/CodeConverter/blob/62961fdd7b256bd2d77ccba35ba6be06a9fd5768/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L1344-L1347

I'd recommend you start by adding this as a test case first (copy one of the existing methods from ExpressionTests.cs in the CSharp namespace and tweak the input and expected output to match this). Then you can put breakpoints in those places and run the test in debug mode to see what's going on currently.

This is an area that has a few nuances and has had a few iterations of fixes, so another couple of tests of related cases might be wise too once this one is passing.
