### ISSUE TITLE
VB -> C#: Comments lost in root of file

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#333]
### Input code
```vbnet
''' <summary>
''' Something
''' </summary>
Friend Class Program
    Public Shared Sub Main(ByVal args As String())
    End Sub
End Class
```

### Erroneous output
```c#
namespace ConsoleApp4
{
    internal class Program
    {
        public static void Main(string[] args)
        {
        }
    }
}
```

### Expected output
```c#
namespace ConsoleApp4
{
    /// <summary>
    /// Something
    /// </summary>
    internal class Program
    {
        public static void Main(string[] args)
        {
        }
    }
}
```

### Details
Product in use: VS extension

Version in use: 6.9.0.0

**Comment by RachelDavids** [comment]
Given the above input code I am getting the following (using v7.0.0.0 and VS15.9.15)
`
/// <summary>
/// Something
/// </summary>
namespace ConsoleApp4
{
    internal class Program
    {
        public static void Main(string[] args)
        {
        }
    }
}
`
