### ISSUE TITLE
VB -> C#: XmlElement literals are not properly converted to C#.

### ISSUE THREAD

**Issue by fabienDaou** [icsharpcode/CodeConverter#337]
### Input code
```vbnet
Class TestClass
    Private Sub TestMethod()
        Dim b = <someXmlTag></someXmlTag>
        Dim c = <someXmlTag><bla>tata</bla><someContent>tata</someContent></someXmlTag>
    End Sub
End Class
```

### Erroneous output
An exception occurs.

### Expected output
```c#
using System.Xml.Linq;
class TestClass
{
    private void TestMethod()
    {
        var b = XElement.Parse(""<someXmlTag></someXmlTag>"");
        var c = XElement.Parse(""<someXmlTag><bla>tata</bla><someContent>tata</someContent></someXmlTag>"");
    }
}
```

### Details
I have a pull request ready to fix this. Can you have a look?

**Comment by GrahamTheCoder** [comment]
This was originally raised as https://github.com/icsharpcode/CodeConverter/issues/253
I'll leave that issue open to represent the general case.

**Comment by fabienDaou** [comment]
Indeed, it is not the complete solution, but at least it unblocks me.
Thanks.

**Comment by GrahamTheCoder** [comment]
Yes as mentioned in the other issue, the whole solution is pretty big so it's definitely the right approach to get there iteratively. Thanks! 👍
