### ISSUE TITLE
VB -> C#: Conversion functions are not correctly translated

### ISSUE THREAD

**Issue by tverweij** [icsharpcode/CodeConverter#343]
### Input code
```vbnet
Dim x As Integer = CInt(SomeObject)
```

### Erroneous output
```C#
private int MyInt = System.Convert.ToInt32(SomeObject);
```

### Expected output
```C#
private int MyInt = Microsoft.VisualBasic.CompilerServices.Conversions.ToGenericParameter<int>(SomeObject);;
```

### Details
Product in use: web converter

Version in use: 7.0.0.0

This is not really convertable (as far as I know not documented anywhere), so the only way to convert this correctly is to use the Microsoft.VisualBasic.dll

**Comment by GrahamTheCoder** [comment]
Thanks! Other test cases #327 and #331, I'll consolidate those issues into this more generally titled one

**Comment by GrahamTheCoder** [comment]
If someone else wants to work on this, it's this method which determines the method invoked:
https://github.com/icsharpcode/CodeConverter/blob/7707ea9ab5deb55b93b2092c9b8d0c495f0fb4ad/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L67-L73
