### ISSUE TITLE
VB IIf(Bool, TruePart, FalsePart) -> C# (Bool ? TruePart : FalsePart)

### ISSUE THREAD

**Issue by vungsung** [icsharpcode/CodeConverter#345]
### Input code
```vbnet
Cap.ForeColor = IIf(CapLock, Color.Red, Color.Black)
```

### Complexed output (VS extension)
```c#
Cap.ForeColor = Interaction.IIf(CapLock, Color.Red, Color.Black); //Could be simplified,  by ?:
```
And even if we don't simply it, it can cause the error:
`CS0266  C# Cannot implicitly convert type 'object' to 'System.Drawing.Color'. An explicit conversion exists (are you missing a cast?)`
### Erroneous output (WEB)
```c#
Cap.ForeColor = IIf[CapLock, Color.Red, Color.Black]; //Error happen due to "[]"
```

### Expected output
```c#
Cap.ForeColor = (CapLock ? Color.Red : Color.Black);
```

### Details
Product in use: WEB & VS2019 extension

Version in use: 7.0.0

Thanks for reviewing.

**Comment by GrahamTheCoder** [comment]
Thanks for reporting. I'm going to consolidate it with the similar issues in #174 to encourage a general solution to this class of problems. Though if anyone wants to PR just this one fix that's fine too!
