### ISSUE TITLE
xggsmon

### ISSUE THREAD

**Issue by Rajko97** [icsharpcode/CodeConverter#347]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```C#
If relevant, please enter some example code here to reproduce the issue (in VB or C#), or the steps taken to cause the issue.
```

### Erroneous output
```vbnet
If relevant, the incorrectly converted output (in VB or C#), or an exception with stack trace.
```

### Expected output
```vbnet
If relevant, the output you expected (in VB or C#), or a description of what you expected.
```

### Details
Product in use: e.g. web converter / VS extension / both

Version in use: e.g. 5.6.3

Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Cannot reproduce: When my cat walks on my keyboard I get a different result 😄
