### ISSUE TITLE
Improve accessibility modifier conversion

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#349]
There are lots of cases where this goes wrong, e.g. In the VB->CS: constructors and nested enums

Using the semantic model, we should get the actual visibility. We could just always output that, then have a second pass to remove them where unnecessary (like the simplifier does for some things). Though there are still probably some special cases when a visibility modifier is not allowed at all which need to be covered.

**Comment by BrianFreemanAtlanta** [comment]
I'll add this so there is a reference to the relevant MSDN docs:

[VB overview](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/public)

[Here is the full breakdown for VB](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/declared-elements/access-levels)

[Here is overview for C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
[and the full breakdown of access modifiers](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/accessibility-levels)

The detailed articles list the possible modifiers and restrictions based on the enclosing object.

**Comment by GrahamTheCoder** [comment]
I'm now unaware of any specific remaining issues, so I'll close this and let it be re-opened with an appropriate repro
