### ISSUE TITLE
VB -> C#: Overloads modifier should not always be converted to new modifier

### ISSUE THREAD

**Issue by AngelSpeaks** [icsharpcode/CodeConverter#351]
This code:
protected new override void Dispose(bool Disposing)

Is issuing error CS0113 on all forms in the project.
Error	CS0113	A member 'frmLicenseAgreement.Dispose(bool)' marked as override cannot be marked as new or virtual	MTCB	C:\AngelSpeaksSoftware-2019\MyTalking Communicator\frmLicenseAgreement.Designer.cs	21	Active

Original VB code:
 'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> Protected Overloads Overrides Sub Dispose(ByVal Disposing As Boolean)
        If Disposing Then
            If Not components Is Nothing Then
                components.Dispose()
            End If
        End If
        MyBase.Dispose(Disposing)
    End Sub

Converted C# code:
// Form overrides dispose to clean up the component list.
        [System.Diagnostics.DebuggerNonUserCode()]
        protected new override void Dispose(bool Disposing)
        {
            if (Disposing)
            {
                if (!(components == null))
                    components.Dispose();
            }
            base.Dispose(Disposing);
        }

![image](https://user-images.githubusercontent.com/53458637/62588934-2d372900-b88d-11e9-81a2-285903135556.png)

**Comment by GrahamTheCoder** [comment]
Wokaround: Do a find and replace, to replace " new override " with " override ", that should fix your issues.
Thanks for pointing out this issue - it's due to the multiple possible uses of the "Overloads" keyword in Visual Basic. It may be possible to check which method is being overloaded in order to decide if the modifier is required

**Comment by GrahamTheCoder** [comment]
Closing to track this on #431
