### ISSUE TITLE
VB -> C#: "With" structure creates unexpected output (can introduce sneaky bugs when used in combination with struct)

### ISSUE THREAD

**Issue by fabienDaou** [icsharpcode/CodeConverter#354]
### Input code
```vbnet
Public Class VisualBasicClass
    Public Sub Stuff()
        Dim str As SomeStruct
        With Str
            ReDim .Arr(1)
        End With
    End Sub
End Class

Public Structure SomeStruct
  Public Arr As String()
End Structure 
```

### Erroneous output
```C#
public class VisualBasicClass
{
    public void Stuff()
    {
        SomeStruct str;
        {
            var withBlock = str;
            withBlock.Arr = new string[2];
        }
    }
}

public struct SomeStruct
{
    public string[] Arr;
}

```

### Expected output
```C#
public class VisualBasicClass
{
    public void Stuff()
    {
        SomeStruct str;
        str.Arr = new string[2];
    }
}

public struct SomeStruct
{
    public string[] Arr;
}

```

### Details
Product in use: both
Version in use: e.g. 7.0.0.0

This is especially problematic when it is used in combination with structure.

If you agree with the expected output, I'll try to provide a fix.

**Comment by GrahamTheCoder** [comment]
Yep makes sense. I think when visiting a with block, if it's an identifier we should just Inline. The general case is harder. Imagine accessing a property with vs without side effects. We need to look at the IL or spec to understand the right conversion

**Comment by fabienDaou** [comment]
Thanks for the fix!
