### ISSUE TITLE
C# -> VB: Complex LINQ problems (Select New)

### ISSUE THREAD

**Issue by ad48hp** [icsharpcode/CodeConverter#360]
I used the Telerik converter, so i'm not entirely sure if it's been fixed yet..

`var indices = from t in destTriangles
                          let p1 = destPoints.First(p => Math.Abs(p.X - t.P1.X) < 1 && Math.Abs(p.Y - t.P1.Y) < 1)
                          let p2 = destPoints.First(p => Math.Abs(p.X - t.P2.X) < 1 && Math.Abs(p.Y - t.P2.Y) < 1)
                          let p3 = destPoints.First(p => Math.Abs(p.X - t.P3.X) < 1 && Math.Abs(p.Y - t.P3.Y) < 1)
                          select new {
                              X1 = destList.IndexOf(p1),
                              X2 = destList.IndexOf(p2),
                              X3 = destList.IndexOf(p3)
                          }`

Failure code

`Dim indices = From t In destTriangles Let p1 = destPoints.First(Function(p) Math.Abs(p.X - t.P1.X) < 1 AndAlso Math.Abs(p.Y - t.P1.Y) < 1) Let p2 = destPoints.First(Function(p) Math.Abs(p.X - t.P2.X) < 1 AndAlso Math.Abs(p.Y - t.P2.Y) < 1) Let p3 = destPoints.First(Function(p) Math.Abs(p.X - t.P3.X) < 1 AndAlso Math.Abs(p.Y - t.P3.Y) < 1) Select New With {Key
    .X1 = destList.IndexOf(p1), Key
    .X2 = destList.IndexOf(p2), Key
    .X3 = destList.IndexOf(p3)
}`

Right code (probably)..

`Dim indices = From t In destTriangles Let p1 = destPoints.First(Function(p) Math.Abs(p.X - t.P1.X) < 1 AndAlso Math.Abs(p.Y - t.P1.Y) < 1) Let p2 = destPoints.First(Function(p) Math.Abs(p.X - t.P2.X) < 1 AndAlso Math.Abs(p.Y - t.P2.Y) < 1) Let p3 = destPoints.First(Function(p) Math.Abs(p.X - t.P3.X) < 1 AndAlso Math.Abs(p.Y - t.P3.Y) < 1) Select New With {.X1 = destList.IndexOf(p1),.X2 = destList.IndexOf(p2),.X3 = destList.IndexOf(p3)}`

**Comment by GrahamTheCoder** [comment]
Thanks for the detailed report, I believe this was fixed some time ago. If I put it into https://codeconverter.icsharpcode.net/ and I see the expected output you described.

You should see the same in the visual studio extension too. Let me know if you're seeing something different in either of those, or if there's another reason you can't use them. Thanks!
