### ISSUE TITLE
Some resources from the former VB.Net PM

### ISSUE THREAD

**Issue by tverweij** [icsharpcode/CodeConverter#369]
Anthony D Green wrote an article about the differences between VB and C#.
(As usual, the second part was never written).

https://anthonydgreen.net/2019/02/12/exhausting-list-of-differences-between-vb-net-c/

This explains a lot of the differences - might be handy for this project.

**Comment by GrahamTheCoder** [comment]
Yes I do like that one, in fact it's already linked from the contributing doc:
https://github.com/icsharpcode/CodeConverter/blob/master/.github/CONTRIBUTING.md

But I'm always glad to hear of more good resources 🙂

**Comment by GrahamTheCoder** [comment]
There's some nice c# bits in there too "Null is not greater than itself, but is equal to itself, and yet not greater than or equal to itself"
