### ISSUE TITLE
VB -> C#: it created errors

### ISSUE THREAD

**Issue by sniperfreak1998** [icsharpcode/CodeConverter#370]
### Input code
```.VB
this is part of the .VB code 
Imports System.Data.SqlClient
Imports System.Data
```

### Erroneous output
```
#error Cannot convert ImportsStatementSyntax - see comment for details
    /* Cannot convert ImportsStatementSyntax, CONVERSION ERROR: Conversion for ImportsStatement not implemented, please report this issue in 'Imports System.Data' at character 70
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 78
       at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
       at ICSharpCode.CodeConverter.CSharp.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\CommentConvertingNodesVisitor.cs:line 29
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.NodesVisitor.ConvertMember(StatementSyntax member) in D:\GitWorkspace\CodeConverter\ICSharpCode.CodeConverter\CSharp\NodesVisitor.cs:line 244

    Input: 
    Imports System.Data

     */
```

### problems
```
this is one of the many errors i get but they all seem to be diffrent and some code i cant find back from the orriginal 
```

### Details
* Product in use: web converter
* Version in use: Version 7.0.0.0
* Did you see it working in a previous version, which?: no this is my first time working with this program and my first time working with .vb or even C#
* Any other relevant information to the issue.
some code has the problems multiple times but other codes only a few times

[problem.zip](https://github.com/icsharpcode/CodeConverter/files/3577851/problem.zip)

**Comment by GrahamTheCoder** [comment]
Thanks, I'll take a look

**Comment by GrahamTheCoder** [comment]
Thanks for reporting this. It's always great to see real cases people are trying the converter on.
The big conversion errors see fixed in the latest development build - let me know if you see any other issues with this conversion (I can't tell without the rest of the project context).
[vNext-fax.zip](https://github.com/icsharpcode/CodeConverter/files/3581457/vNext-fax.zip)

**Comment by GrahamTheCoder** [comment]
By the way, since you said it's your first time working in these languages. While reading your code, I noticed you probably wanted something like this:
```vbnet
    Private Function TurnFirstToUp(ByVal Text As String)
        Dim firstCharacter = Text.Substring(0, 1).ToUpper()
        Return firstCharacter + Text.Substring(1)
    End Function
```
or 
```csharp
private string TurnFirstToUp(string Text)
{
    var firstCharacter = Text.Substring(0, 1).ToUpper();
    return firstCharacter + Text.Substring(1);
}
```
Good luck!

**Comment by GrahamTheCoder** [comment]
I believe the issues you saw will be fixed by the imminent release so I'll close this. Feel free to open other issues though!
