### ISSUE TITLE
VB -> C#: Explicitly qualified global names not translated

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#375]
For names which can be used globally, eg. `Timer`, `Now`, `Len`, etc, VB allows you to explicitly qualify them as eg. `Microsoft.VisualBasic.Timer`. The actual symbol is elsewhere, eg. `Microsoft.VisualBasic.DateAndTime.Timer`. This is not converted correctly.

### Input code
```vbnet
Friend Module Module1
    Sub Main()
        Dim x = Microsoft.VisualBasic.Timer
    End Sub
End Module
```

### Erroneous output
```c#
namespace ConsoleApp3
{
    internal static class Module1
    {
        public static void Main()
        {
            double x = Microsoft.VisualBasic.Timer;
        }
    }
}
```

### Expected output
```c#
using Microsoft.VisualBasic;

namespace ConsoleApp3
{
    internal static class Module1
    {
        public static void Main()
        {
            double x = DateAndTime.Timer;
        }
    }
}
```

### Details

Error:
```
error CS0234: The type or namespace name 'Timer' does not exist in the namespace 'Microsoft.VisualBasic' (are you missing an assembly reference?)
```

Version: master @ 3ffc597ffdce991ef0cccf01bd7c884b9d337d6a

**Comment by GrahamTheCoder** [comment]
The general case of this is supposed to be handled by `TryGetTypePromotedModuleSymbol` and `QualifyNode`. In solving this we should remember it's fine to overqualify things and let them be automatically simplified at the end.

**Comment by mrmonday** [comment]
@GrahamTheCoder are you actively working on this? If not, I'll take a shot at it tomorrow.

**Comment by GrahamTheCoder** [comment]
Sorry I probably should have unassigned myself while I was away - just got back. I was looking at it briefly yesterday. I'll push my progress and/or unassign myself by tomorrow.

**Comment by GrahamTheCoder** [comment]
I didn't get around to spending any more time on this, thought a few related tidyups went into #406. In `QualifyNode` I was pretty much going to try to replace a lot of it with just outputting the full name using something like `GetFullMetadataName`
