### ISSUE TITLE
C# -> VB: some missing code when convert 

### ISSUE THREAD

**Issue by a-actor** [icsharpcode/CodeConverter#377]
### Input code
```C#
public partial class RefEditForm : Form
```
```C#
            Closed += delegate
            {
                _selectionTracker.NewSelection -= ChangeText;
                _selectionTracker.Stop();
            };
```
```C#
Dispatcher.Invoke(new Action(() =>
            {
                _refEditWindow2.Dispatcher.Invoke(new Action(() => _refEditWindow2.Activate()));
            }
```

### Erroneous output
```vbnet
    Public Partial Class RefEditForm
        Inherits Form
```
```vbnet
            AddHandler ClosedEvent, Sub()
                                        RemoveHandler _selectionTracker.NewSelection, AddressOf ChangeText
                                        _selectionTracker.[Stop]()
                                    End Sub
```
```vbnet
Dispatcher(New Action(Sub()
_refEditForm2(New Action(Sub() _refEditForm2.Activate()))
```
### Expected output
```vbnet
   Partial Class RefEditForm
        Inherits Form
```
```vbnet
            AddHandler Closed, Sub()
                                        RemoveHandler _selectionTracker.NewSelection, AddressOf ChangeText
                                        _selectionTracker.[Stop]()
                                    End Sub
```
```vbnet
Dispatcher.Invoke(New Action(Sub()
_refEditForm2.Invoke(New Action(Sub() _refEditForm2.Activate()))
```

### Details
*  [ ] Unknown issue to do with "Public"
* [x] Shoud say "Closed" instead of "ClosedEvent"
* [x] Missing ".Invoke"

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I've edited the description to clarify a bit and moved one example out to the existing issue.
* Visibility modifier: should be possible to make use of the semantic model as per #349 
* "Event" suffix: This line needs some refinement: https://github.com/icsharpcode/CodeConverter/blob/b149a25eca197d0005466899a823f3777a1bf371/ICSharpCode.CodeConverter/VB/CommonConversions.cs#L434
* Missing invoke: This line needs refinement: https://github.com/icsharpcode/CodeConverter/blob/949f96d227354f08102126f2d9d2c481ecb5415d/ICSharpCode.CodeConverter/VB/NodesVisitor.cs#L964

**Comment by GrahamTheCoder** [comment]
I believe in the latest dev build I've now fixed most of the issues you mentioned. However, I can't understand what you mean regarding 
```csharp
public partial class RefEditForm : Form
```
Your listed erroneous output appears correct to me:
```vbnet
Public Partial Class RefEditForm
     Inherits Form
```

Was the listed expected output just a typo, and it was part of one of the other examples?

**Comment by GrahamTheCoder** [comment]
Several issues fixed - feel free to reopen with further details on repros

**Comment by BrianFreemanAtlanta** [comment]
In looking at issue #92, ran across issue #349 that was referenced by this issue.  In reading the MSDN docs for VB.  The default class visibility is Public whereas in C# the default visibility is internal.  Since the default VB visibility is Public it isn't "required."
so `Public Partial Class RefEditForm` is equivalent to `Partial Class RefEditForm`
It just becomes a question as mentioned in #349 if the superfluous `Public` modifier is removed or left on.
