### ISSUE TITLE
C# -> VB: For loop variable is not declared and initialized

### ISSUE THREAD

**Issue by MisinformedDNA** [icsharpcode/CodeConverter#38]
```
using System;

namespace myApp
{
    class Program
    {
        static void Main()
        {
            int total = 0;                        
            for (int i = 0; i < 5; ++i) 
            { 
                total = i + total;
            } 
            Console.WriteLine(total);
        }
    }
}
```
becomes
```
Imports System

Namespace myApp
    Class Program
        Private Shared Sub Main()
            Dim total As Integer = 0

            While i < 5
                total = i + total
                System.Threading.Interlocked.Increment(i)
            End While

            Console.WriteLine(total)
        End Sub
    End Class
End Namespace
```

First off, I'm not sure why the `for` is getting translated into a `while` (UPDATE: It's due to `++i` instead of `i++`). But even if `while` was correct, `i` is never instantiated in the VB.NET code.

**Comment by GrahamTheCoder** [comment]
In this case doesn't it automatically get initialized to zero anyway yielding the same results?
But yes, I imagine if you'd said `int i = 1`, it still wouldn't have been initialized, so that does sound like a bug. I'm happy to accept a PR to initialize that variable correctly.

**Comment by siegfriedpammer** [comment]
I think this is not just about initialization... the variable i actually never gets declared explicitly, which is a "feature" of VB, but should actually be forbidden, i. e. always use `Option Strict On` and `Option Explicit On`.
