### ISSUE TITLE
Why can't I select just some of the output code?

### ISSUE THREAD

**Issue by alantlau** [icsharpcode/CodeConverter#392]
I just converted some code and after I saw the results, I realized that I didn't need the function declaration, just the code inside.  I tried to copy just that code with my mouse, and your site doesn't allow this.  I'm a firm believer that programs and websites should follow the "Law of Least Astonishment".  I feel that not allowing marking of text with a mouse breaks that law.  Yes, I know there is the "Copy to clipboard" button, but then I had to open notepad, paste the code in there, delete the code I didn't want, select the code I did want, copy it to the clipboard, paste the code into the function that was already defined in my code, then close notepad.  Granted, it took me way more time to write this post, but it was still annoying enough to break my train of thought.

/end of rant

**Comment by GrahamTheCoder** [comment]
Thanks for getting in touch. Never fear, no rant required, I totally agree with you. You mentioned "your site" so I've just tested and could not reproduce the described behaviour on  https://codeconverter.icsharpcode.net/
(using chrome on a galaxy S series phone)

Could you confirm that's the site you mean, and which browser/device you are using?

**Comment by alantlau** [comment]
OK, I'm  a dumbass.  The site I was referring to was http://converter.telerik.com.  On the "about" page it says, "For the heavy lifting, we rely on the open source Code Converter built by ic#code. If an error occurs in conversion, we would like to ask you to report it here.", and that link took me here.  I didn't read that line fully, and my mind just saw the "report it here" link and I incorrectly assumed they were part of the same domain.
