### ISSUE TITLE
VB -> C# handle > operators for strings

### ISSUE THREAD

**Issue by v1nce** [icsharpcode/CodeConverter#396]
It would be awesome if code converter could handle [string] >[string] for us

### Input code
```vbnet
mystring > ""
```
### Erroneous output
```C#
mystring > ""
```

### Expected output
```C#
String.compare(mystring , "") > 0
```

### Details
* Product in use:VS extension
* Version in use: 7.2.0.0

**Comment by GrahamTheCoder** [comment]
Thanks for raising this. Sounds very sensible, though we'd need to
carefully check the expected output (by decompiling a vb dll using it)
since VB may use it's own special method with subtly different behaviour.
Let me know if you've already checked this, I've never used the string
greater than operator myself so I don't know.

The change would probably need to be made around a method called something
like VisitBinaryExpression in case someone wants to tackle this before I
get around to it.

**Comment by GrahamTheCoder** [comment]
Yep that sounds more like what I'd expect. Shouldn't be too tricky to use
that compilation option, it's already used for string equality comparison
(the per file overrides of options are currently ignored, there's a to do
in the code for that).
The class dealing with string equality might be good place to look when
fixing this actually, I'd forgotten about that.

**Comment by GrahamTheCoder** [comment]
See
https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/CSharp/VisualBasicEqualityComparison.cs

**Comment by GrahamTheCoder** [comment]
This is a handy place to start for checking the implementation: https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Binding/Binder_Operators.vb#L130
I'm hoping the symbol/operation API will allow me to detect whether an operator is user defined without doing the heavy lifting myself.

The comment just above the linked line makes a good point about a possible improvement to VisitBinaryExpression to avoid stackoverflows (I've seen at least one before from this effect):
> Some tools, such as ASP .NET, generate expressions containing thousands
of string concatenations. For this reason, for string concatenations,
avoid the usual recursion along the left side of the parse. Also, attempt
to flatten whole sequences of string literal concatenations to avoid
allocating space for intermediate results.

**Comment by GrahamTheCoder** [comment]
The implementation that binds to the VB methods is here:
https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb#L233-L464

Note that it doesn't rewrite the method if it's within an expression lambda (as we've already got wrong for equality - see #316)
