### ISSUE TITLE
VB -> C#: NullReferenceException when using the VS extension with .NET Standard

### ISSUE THREAD

**Issue by Keex0r** [icsharpcode/CodeConverter#398]
Hello,
I am trying to convert some VB.NET code to C# using the Visual Studio extension in VS2019. 
When I try to convert a file containing the input code below, an error message is shown:

![CodeConvertError](https://user-images.githubusercontent.com/8248242/67491359-1aa2e380-f675-11e9-8f1d-e0dcb36baa86.png)

No output file is generated. The same happens with other source files in the project as well, so it is probably no quirk of the code itself.

The solution contains both .NET Standard and .NET Framework projects, and weirdly this only occurs in .NET Standard (2.0) VB.NET projects. In .NET Framework both VB->C# and C#->VB works, in .NET Standard only C#->VB works.

I have no real clue why. I installed the extension by downloading the installer from the marketplace, instead of installing from the extension manager.
By virtue of the nice async/await stack traces I wasn't really able to find the code where it occurs :-)

Thanks for the work you put in!
Cheers
Jens

### Input code
```vbnet
Namespace CAD
    ''' <summary>
    ''' Represents a CAD RGB Color tuple
    ''' </summary>
    Public Structure CADColor
        Public Sub New(A As Byte, R As Byte, G As Byte, B As Byte)
            Me.A = A
            Me.R = R
            Me.G = G
            Me.B = B
        End Sub
        Public Sub New(R As Byte, G As Byte, B As Byte)
            Me.A = 255
            Me.R = R
            Me.G = G
            Me.B = B
        End Sub
        Public Property A As Byte
        Public Property R As Byte
        Public Property G As Byte
        Public Property B As Byte

        Public Shared Function FromArgb(R As Byte, G As Byte, B As Byte) As CADColor
            Return FromArgb(255, R, G, B)
        End Function
        Public Shared Function FromArgb(A As Byte, R As Byte, G As Byte, B As Byte) As CADColor
            Return New CADColor(A, R, G, B)
        End Function
    End Structure
End Namespace
```

### Details
* Product in use: VS extension
* Version in use: 7.2.0.0
* Did you see it working in a previous version, which? --> Never used the extension before

**Comment by GrahamTheCoder** [comment]
Thanks for the full diagnosis. I don't think there's currently a test for a
VB. Net standard project, so we should add one in to the project and
solution tests. Looks like the error is around the ConvertProjectContents
method, it'll be easy to see in a debugger. Happy to accept a PR, or I'll
hopefully get around to releasing a fix in a month or so.
