### ISSUE TITLE
Open Code Converter Issues from RE

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/CodeConverter#4]
General 

https://github.com/icsharpcode/RefactoringEssentials/issues/234

VSIX Issues

https://github.com/icsharpcode/RefactoringEssentials/issues/317
https://github.com/icsharpcode/RefactoringEssentials/issues/321

**Comment by GrahamTheCoder** [comment]
Done
https://github.com/icsharpcode/CodeConverter/issues/17
https://github.com/icsharpcode/CodeConverter/issues/18
