### ISSUE TITLE
VB -> C#: ReDim array of anything with (Of T1, ...) produces faulty code

### ISSUE THREAD

**Issue by FelixFifi** [icsharpcode/CodeConverter#403]
Thank you for this awesome tool :)

I encountered this while converting a project from VB to C#.
ReDim array of anything with (Of T1, ...), when converted to C#, keeps the (Of ...) syntax in C#.

### Input code
```vbnet
Public Class Class1
    Private Sub test123(sender As Object, e As EventArgs)
        Dim test() As List(Of Integer)
        ReDim test(42)

        Dim test1() As Tuple(Of Integer, Integer)
        ReDim test1(42)
    End Sub
End Class
```

### Erroneous output
```C#
using System.Collections.Generic;
using System;

namespace WindowsApp1
{
    public class Class1
    {
        private void test123(object sender, EventArgs e)
        {
            List<int>[] test;
            test = new List(Of Integer)[43];

            Tuple<int, int>[] test1;
            test1 = new Tuple(Of Integer, Integer)[43];
        }
    }
}
```

### Expected output
```C#
using System.Collections.Generic;
using System;

namespace WindowsApp1
{
    public class Class1
    {
        private void test123(object sender, EventArgs e)
        {
            List<int>[] test;
            test = new List<int>[43];

            Tuple<int, int>[] test1;
            test1 = new Tuple<int, int>[43];
        }
    }
}

```

### Details
* Product in use: both
* Version in use: VS extension 2.2.128.4985, online Version 7.2.0.0

**Comment by GrahamTheCoder** [comment]
Glad you're enjoying it, thanks for the full bug report. The redim code was
written a while back so where it currently creates the type should must
have been missed when I moved things to use CommonConversions. GetTypeSyntax

So it should just be an easy fix. Happy to accept and help with a PR.
Otherwise I might have some time to take a look later this month.
