### ISSUE TITLE
VB -> C#: Module with same name as method

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#420]
### Input code
```vbnet
Module Main
    Sub Main()
    End Sub
End Module
```

### Erroneous output
```c#
static class Main
{
    public static void Main()
    {
    }
}
```

### Expected output
Unsure, perhaps:

```c#
static class MainModule
{
    public static void Main()
    {
    }
}
```

### Details

* Version in use: 7.3.0

Gives:

```
error CS0542: 'Main': member names cannot be the same as their enclosing type
```

**Comment by GrahamTheCoder** [comment]
Similarly, an enum member cannot start with the name of the enum in C#
e.g.
enum MyEnum
{
    MyEnumFirst //Compile error
}

I propose we fix both of these with a pre-conversion rename similar to the C#->VB one:
https://github.com/icsharpcode/CodeConverter/blob/master/CodeConverter/VB/CaseConflictResolver.cs
