### ISSUE TITLE
VB -> C#: Incorrect visibility for constructor

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#422]
### Input code
```vbnet
Class Class1
    Sub New(x As Boolean)
    End Sub
End Class
```

### Erroneous output
```c#
class Class1
{
    Class1(bool x)
    {
    }
}
```

### Expected output
```c#
class Class1
{
    public Class1(bool x)
    {
    }
}
```

### Details
* Version in use: 7.3.0

Visibility of constructors in visual basic is public when no other modifier is specified (can't find this in the spec, but the same happens for other methods, and ILSpy confirms).

**Comment by GrahamTheCoder** [comment]
I previously tried a global approach to https://github.com/icsharpcode/CodeConverter/issues/349 and hit some issues (the CsSyntaxGenerator isn't as far reaching as I'd hoped), but it might be applicable here. I suspect a sensible model for these things to follow in some cases might be to use the syntaxgenerator, then replace bits using "With..." methods.

**Comment by BrianFreemanAtlanta** [comment]
This specific issue is related to the difference in default visibility between c# and VB.  I'll add this so there is a reference to the relevant MSDN docs:

[VB overview](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/public)

Excerpt: 
>Public access is the normal level for a programming element when you do not need to limit access to it. Note that the access level of an element declared within an interface, module, class, or structure defaults to Public if you do not declare it otherwise.

[Here is the full breakdown for VB](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/declared-elements/access-levels)

[Here is overview for C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
[and the full breakdown of access modifiers](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/accessibility-levels)
excerpt: 
>Classes and structs that are declared directly within a namespace (in other words, that are not nested within other classes or structs) can be either public or internal. Internal is the default if no access modifier is specified.

and
>Struct members, including nested classes and structs, can be declared as public, internal, or private. Class members, including nested classes and structs, can be public, protected internal, protected, internal, private protected or private. The access level for class members and struct members, including nested classes and structs, is private by default. Private nested types are not accessible from outside the containing type.

So the default visibility for C# class members is private while VB default is public.  This leads us to have to add an access modifier to keep the same behavior.
