### ISSUE TITLE
Seeing MissingMethodException

### ISSUE THREAD

**Issue by NiKiZe** [icsharpcode/CodeConverter#429]
### Details
* Product in use: VS extension
* Version in use: 7.2.0.0
* Fresh install of plugin on box with VS 2017 15.7.4

(weird behavior before actual issue if relevant)
Rightclicking on VB code block does not present the convert option on the menu.
Compiling the project and it shows up. But it also exists on edit menu before compile

Clicking on any of them, it shows `MissingMethodException` dialog (see below), and after this trying to save modifications in VS just results in failures (meaning any unsaved work can't be saved)

Only mention I can find of this is in commit 5ff661cc0f700a ?

It is true that I have only tried one code block, but this does seem more generic than the code itself. (tested with different solution as well, same issue), Any logs that I can find with more info of what the extension does?

Translation of "Methoden hittades inte" is something like "Method could not be found"
![image](https://user-images.githubusercontent.com/1240066/69014599-1d4edb00-098c-11ea-9233-6653fd9e0bd3.png)

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report. I think you're right that it's a general error that will affect all code. I suspect I've used a method that wasn't in old versions of visual studio. If you don't mind trying a later version (e.g. the latest update of 2017) and letting me know if it works for you that'd be a great help.

I'll look into it further and see if it's easy to restore compatibility for now, or at least find the last compatible version (old versions are in the releases section of github)

**Comment by GrahamTheCoder** [comment]
I didn't find anything further. I'll leave this open so others can upvote it if it's important.

**Comment by GrahamTheCoder** [comment]
That method has been present [since VS2015 RC](https://github.com/dotnet/roslyn/commit/7232491fbfe4b577d365c3d1b63135c7b86c0f59).
I'm going to close this. If anyone sees something like this again, please send a an activity log as explained here: https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019#to-examine-the-activity-log
