### ISSUE TITLE
VB -> C#: select case colon not in right line

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#437]
### Input code
```VB
Select Case strSomething
    Case "TestTest" 'Some comment
End Select
```

### Erroneous output
```C#
{
    switch (strSomething)
    {
        case "TestTest" // Some comment
       :
            {
                break;
            }
    }
}
```

### Expected output
```C#
{
    switch (strSomething)
    {
        case "TestTest": // Some comment
        {
            break;
        }
    }
}
```

### Details
* Product in use: e.g. web converter
* Version in use: 7.2.0.0
* Did you see it working in a previous version, which? Don't know
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
I'll consolidate this with #436 to be used as another test case
