### ISSUE TITLE
VB -> C#:  string equality

### ISSUE THREAD

**Issue by tomtheisen** [icsharpcode/CodeConverter#439]
### Input code
```vbnet
dim a as string = ""
dim b as string = nothing

Console.WriteLine(a = b)
```

### Erroneous output
```C#
{
    string a = "";
    string b = null;

    Console.WriteLine(a == b);
}
```

### Expected output
The output should use VB's goofy string equality under which null and empty are considered equal.

### Details
* Product in use: e.g. web converter 
* Version in use: http://converter.telerik.com, don't see a version number, but it says copyright 2019
* Did you see it working in a previous version? no

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report. Good news, this was fixed about 6 months ago!
You'll get VB's goofy string equality if you use the latest version of the [Visual Studio Extension](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter) or online snippet converter at https://codeconverter.icsharpcode.net/ (i.e. not Telerik's site which uses an ancient version of this library)

**Comment by tomtheisen** [comment]
Oh thanks. 👍  

Sorry for the spurious report.  It wasn't immediately clear what the relationship between Telerik and ICSharpCode is, and their site links directly here to report bugs.

**Comment by GrahamTheCoder** [comment]
No worries, it happens pretty often. I'm not sure how to subtly mention it without accidentally directing people to their site (which is out-of-date, HTTP only and has ~95 advertising cookies)
