### ISSUE TITLE
VB to CS: integer divide and narrowing/widening op not supported

### ISSUE THREAD

**Issue by BaronBodissey** [icsharpcode/CodeConverter#44]
VB to CS: integer divide and narrowing/widening op not supported

**Comment by BaronBodissey** [comment]
I've "commited" a possible resolution.
Also created a pull request....but I don't really know how this works, I'd need some help to continue.
How do I merge my fork with the main repo?

**Comment by GrahamTheCoder** [comment]
To get https://github.com/icsharpcode/CodeConverter/pull/43 integrated back into the main repo, I'll review, make any tweaks necessary and merge it.

**Comment by GrahamTheCoder** [comment]
Fixed by https://github.com/icsharpcode/CodeConverter/pull/43
