### ISSUE TITLE
VB -> C#: Renamed method implementation not converted

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#444]
### Input code
```vbnet
Public Interface IFoo
    Sub Foo()
End Interface

Public Class Foo
    Implements IFoo
    Sub Bar() Implements IFoo.Foo
    End Sub
End Class
```

### Erroneous output
```C#
public partial interface IFoo
{
    void Foo();
}

public partial class Foo : IFoo
{
    public void Bar()
    {
    }
}
```

### Expected output
```C#
public partial interface IFoo
{
    void Foo();
}

public partial class Foo : IFoo
{
    public void Foo()
    {
    }
    public void Bar()
    {
        Foo();
    }
}
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: 7.3.0

Worth checking the IL for this.

Also worth checking further inheritance behaviour - I'm not sure if the explicit `implements` clause in VB maps to the [explicit interface implementation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation) in C# which has different semantics.

**Comment by GrahamTheCoder** [comment]
I'm pretty sure in VB (and indeed in IL) you can change the name of something when explicitly implementing it. In c# you can't, which could need some creative thinking.
