### ISSUE TITLE
VB -> C#: Invalid indentation for Case blocks

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#447]
### Input code
```vbnet
Select Case (Variant)
  Case "1"
    SomeProp = "2"
End Select
```

### Erroneous output
```C#
{
    switch (Variant)
    {
        case "1":
            {
                SomeProp = "2";
                break;
            }
    }
}
```

### Expected output
```C#
{
    switch (Variant)
    {
        case "1":
        {
            SomeProp = "2";
            break;
        }
    }
}
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: 7.3.0.0
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Consolidating into #448
