### ISSUE TITLE
C# -> VB: Explicit public modifier of static class is converted to implicit Friend modifier of Module

### ISSUE THREAD

**Issue by Alexilia** [icsharpcode/CodeConverter#459]
### Input code
```csharp
public static class TestClass {
}
```

### Erroneous output
```vbnet
Module TestClass
End Module
```

### Expected output
```vbnet
Public Module TestClass
End Module
```

**Comment by GrahamTheCoder** [comment]
Yep, the accessibility modifier conversion code should probably make better use of the semantic model to get the symbol's declared accessibility (which I think just the VB -> C# does right now), and then fallback on a context system that encodes these rules:
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/declaration-contexts-and-default-access-levels#declaration-context-levels

**Comment by GrahamTheCoder** [comment]
I think this was fixed a while back, the example works now in the web converter.
