### ISSUE TITLE
VB -> C#: Operator overload support

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#46]
Example Input (we should test other operator overloads too):
```
[Fact]
public void PlusToken()
{
TestConversionVisualBasicToCSharp(@"Public Class AcmeClass
Public Shared Operator +(i As Integer, ac As AcmeClass) As Integer
Return 0
End Operator
End Class", @"using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualBasic;

public class AcmeClass
{
public static int operator +(int i, AcmeClass ac)
{
return 0;
}
}");
}
```

Originally reported here https://github.com/icsharpcode/CodeConverter/issues/29#issuecomment-370451648

**Comment by GrahamTheCoder** [comment]
Closing this as can't repro until there's more information

**Comment by BaronBodissey** [comment]
[Fact]
        public void PlusToken()
        {
            TestConversionVisualBasicToCSharp(@"Public Class AcmeClass
    Public Shared Operator +(i As Integer, ac As AcmeClass) As Integer
        Return 0
    End Operator
End Class", @"using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualBasic;

public class AcmeClass
{
    public static int operator +(int i, AcmeClass ac)
    {
        return 0;
    }
}");
        }

**Comment by GrahamTheCoder** [comment]
I've added the `Like` and `^` operator overloads to known limitations since they won't be converted
