### ISSUE TITLE
convert collection from vb to c#

### ISSUE THREAD

**Issue by githubanssary** [icsharpcode/CodeConverter#461]
[###]collection in vb.net use this bracket () but c# use []
1. 
2. 
3. 

### Error message shown
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by githubanssary** [comment]
![New Bitmap Image (2)](https://user-images.githubusercontent.com/25457175/70721836-f66f9480-1cfe-11ea-81da-f13e19e005bf.png)

**Comment by GrahamTheCoder** [comment]
It looks like you're using a web converter from another website that makes use of an older version of the library. Your example seems to work for me on https://codeconverter.icsharpcode.net/

Be aware though that there will be other similar examples that fail. When you convert a small snippet without the context, it's very hard (and sometimes impossible) to know whether SmartArtLayouts for example is a property of type array, or a method with a single parameter.

If you need a more accurate conversion, I'd recommend using the visual studio extension which can converts snippets, files, projects or whole solutions using the context to help: https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter
