### ISSUE TITLE
VB -> C#: Respect End If

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#466]
### Input code
```vbnet
If True Then
Call Bla
End If
```

### Erroneous output
```C#
{
    if (true)
        Bla();
}
```

### Expected output
```C#
{
    if (true)
    {
        Bla();
    }
}
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: 7.4.0.0
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix. Related to #448

**Comment by GrahamTheCoder** [comment]
As mentioned on https://github.com/icsharpcode/CodeConverter/issues/448, the general solution (and current workaround) to formatting code is via editorconfig.
For this especially common case I agree it makes sense to improve the currently inconsistent logic to:
* Make if/elseif/else blocks always contains braces.
* (Optional) A single line if in VB should be a single line if in C#
