### ISSUE TITLE
Improve website conversion time

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#469]
Upvote if you want this to happen sooner!

### Summary
With recent major additions, one-file-at-a-time performance is definitely slower. The test time has gone from 59 to 87 seconds since 2019-09-24. Obviously it's a bit up and down but there aren't that many more tests and there's an upwards trend.

While single file performance has decreased, I parallelized at the file-level. So I'm hoping that in the case that takes longest - converting whole projects/solutions - that the overall impact is acceptable for now. The snippet converter seems especially slow even for tiny samples so there may be something bad going on there.

### Cause
One really big cost is GetCompilationAsync within InitializeSourceAsync.

I expected the performance to decrease when adding things like extra separate passes added for things like normalizing inputs: https://github.com/icsharpcode/CodeConverter/pull/386
And when adding conversion of the VB compiler-inlined classes: https://github.com/icsharpcode/CodeConverter/pull/387
So some of the slowdown is just due to doing significantly more work in order to get a more accurate conversion.
However, there are certainly other changes which could potentially be optimized, for example in CS->VB: PR #456 introduces a potentially slightly slow operation on a "warm" path: https://github.com/icsharpcode/CodeConverter/pull/456/files#diff-709371109bde62ae9a9082fda70f3a94R192

There are some more big changes coming in a general drive to get VB->CS winforms conversion pretty solid. For example once I've flipped this switch it will go even slower: https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/CSharp/DocumentExtensions.cs#L45
However, it should allow deleting some other bits of code on hot paths, which will speed things up.

### Solution

Do some profiling and optimize as appropriate.

**Comment by GrahamTheCoder** [comment]
I'm now happy that project level specific   code performs well enough. The next step would be to focus on reducing time to convert for a single typical small snippet that'd be used in the Web converter

**Comment by GrahamTheCoder** [comment]
For some reason the live site is significantly (5x) slower for the trivial sample conversion than running the website locally

The local site is slow only for the first request, then fast (with browser cache disabled)

**Comment by christophwille** [comment]
I played around a bit with (unscientifically) Task Manager. Memory for the worker process is negligible, however, the CPU sometimes goes up considerably for the process (up to 30-40%). That's when the slowdown is noticeable (could parallel conversion tax the CPU that much?).

**Comment by GrahamTheCoder** [comment]
The parallelization is at the file level, so it shouldn't be kicking in for a single snippet. The memory/recycle values you mentioned by email seem sensible. Might be worth checking event viewer to see if the process is getting restarted due to errors or anything like that.

**Comment by GrahamTheCoder** [comment]
This seems to be even worse recently (especially VB to CS) . I need to get a local repro so I can do some profiling.
I may have increased the number of references in the compilation which could be affecting things.

**Comment by GrahamTheCoder** [comment]
This seems much improved now that the site is using the hosted Azure Function
