### ISSUE TITLE
VB -> C#: Duplicated property names (for prop in base class)

### ISSUE THREAD

**Issue by pmantos** [icsharpcode/CodeConverter#473]
### Erroneous output
UseWaitCursor.UseWaitCursor 

### Expected output
Application.UseWaitCursor

**Comment by GrahamTheCoder** [comment]
Thanks for raising this, there's a fix for it in a PR which is nearly finished: https://github.com/icsharpcode/CodeConverter/pull/471/files#diff-147671de17f06092e1edbbc8ab7f5826R1771

**Comment by Saibamen** [comment]
Please retest. Should be fixed with https://github.com/icsharpcode/CodeConverter/pull/471
