### ISSUE TITLE
No overload for ... matches delegate 'MouseEventHandler'

### ISSUE THREAD

**Issue by pmantos** [icsharpcode/CodeConverter#474]
### Erroneous output
        private void ChangeMinLevel()
        {
            try
            {
                Waterfall1.Levels.Axis.Min = tb_MinLevel.Value;
            }
            catch (Exception ex)
            {
                PostErrors_ThreadSafe(ex.ToString(), "ChangeMinLevel", "", true);
            }
        }

### Expected output
        private void ChangeMaxLevel(object sender, MouseEventArgs e)
        {
            try
            {
                Waterfall1.Levels.Axis.Max = tb_MaxLevel.Value;
            }
            catch (Exception ex)
            {
                PostErrors_ThreadSafe(ex.ToString(), "ChangeMaxLevel", "", true);
            }
        }

**Comment by GrahamTheCoder** [comment]
Thanks for the report, could you post the input code please? I tried the following but it seemed to work fine:
```vbnet
Private Sub ChangeMaxLevel(ByVal sender As Object, ByVal e As MouseEventArgs)
    Try
        Waterfall1.Levels.Axis.Max = tb_MaxLevel.Value
    Catch ex As Exception
        PostErrors_ThreadSafe(ex.ToString, "ChangeMaxLevel", "", True)
    End Try
End Sub
```

I notice you posted two different methods in your report, did one work and the other not work? If so, seeing both might speed up diagnosis of the issue. Thanks!

**Comment by GrahamTheCoder** [comment]
Found a repro
```vbnet
Partial Public Class Form1
    Private Sub Form1_MouseClick() Handles Me.MouseClick
    End Sub

    Public Sub Init()
        AddHandler Me.MouseClick, AddressOf Form1_MouseClick
    End Sub

    Public Sub Other()
        Form1_MouseClick()
    End Sub
End Class
```

Note: The only compilable forms in VB are to specify all parameters, or none. You can't specify just some.

The correct output in these cases is to add the event handler as a lambda which throws away the args.

**Comment by Saibamen** [comment]
Please retest. Should be fixed by https://github.com/icsharpcode/CodeConverter/pull/537
