### ISSUE TITLE
C# -> VB: Rename overloads for explicit interface implementation

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#492]
### Input code
```csharp
using System.Collections;
using System.Collections.Generic;

namespace ICSharpCode.CodeConverter.CSharp
{
  public class AdditionalLocals : IEnumerable<KeyValuePair<string, AdditionalLocal>>
  {
    private readonly Stack<Dictionary<string, AdditionalLocal>> _additionalLocals;

    public AdditionalLocals()
    {
      _additionalLocals = new Stack<Dictionary<string, AdditionalLocal>>();
    }
    
    public IEnumerator<KeyValuePair<string, AdditionalLocal>> GetEnumerator()
    {
      return _additionalLocals.Peek().GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
      return _additionalLocals.Peek().GetEnumerator();
    }

  }


  public class AdditionalLocal
  {
  }
}
```

### Erroneous output
```vbnet
Imports System.Collections
Imports System.Collections.Generic

Namespace ICSharpCode.CodeConverter.CSharp
    Public Class AdditionalLocals
        Implements IEnumerable(Of KeyValuePair(Of String, AdditionalLocal))

        Private ReadOnly _additionalLocals As Stack(Of Dictionary(Of String, AdditionalLocal))

        Public Sub New()
            _additionalLocals = New Stack(Of Dictionary(Of String, AdditionalLocal))()
        End Sub

        Public Function GetEnumerator() As IEnumerator(Of KeyValuePair(Of String, AdditionalLocal)) Implements IEnumerable(Of KeyValuePair(Of String, AdditionalLocal)).GetEnumerator
            Return _additionalLocals.Peek().GetEnumerator()
        End Function

        Private Function GetEnumerator() As IEnumerator Implements IEnumerable.GetEnumerator
            Return _additionalLocals.Peek().GetEnumerator()
        End Function
    End Class

    Public Class AdditionalLocal
    End Class
End Namespace
```

### Expected output
```vbnet
Imports System.Collections
Imports System.Collections.Generic

Namespace ICSharpCode.CodeConverter.CSharp
    Public Class AdditionalLocals
        Implements IEnumerable(Of KeyValuePair(Of String, AdditionalLocal))

        Private ReadOnly _additionalLocals As Stack(Of Dictionary(Of String, AdditionalLocal))

        Public Sub New()
            _additionalLocals = New Stack(Of Dictionary(Of String, AdditionalLocal))()
        End Sub

        Public Function GetEnumerator() As IEnumerator(Of KeyValuePair(Of String, AdditionalLocal)) Implements IEnumerable(Of KeyValuePair(Of String, AdditionalLocal)).GetEnumerator
            Return _additionalLocals.Peek().GetEnumerator()
        End Function

        Private Function GetEnumerator2() As IEnumerator Implements IEnumerable.GetEnumerator
            Return _additionalLocals.Peek().GetEnumerator()
        End Function
    End Class

    Public Class AdditionalLocal
    End Class
End Namespace
```

### Details
In VB, the function that implements the non generic version of IEnumerable.GetEnumerator has to have a different name.

* **Error Message**: 'Public Function GetEnumerator() As IEnumerator(Of KeyValuePair(Of String, AdditionalLocal))' and 'Private Function GetEnumerator() As IEnumerator' cannot overload each other because they differ only by return types.

* Version in use: Current compiled repository

**Comment by GrahamTheCoder** [comment]
https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/VB/CaseConflictResolver.cs is probably the place to deal with this case

**Comment by Alexilia** [comment]
There is no need to rename interface members at all. Explicitly implemented members can't be called directly, only using interface. We can simply generate it's names in specific manner.  For example,
`IEnumerator IEnumerable.GetEnumerator()`
will be
`Private Function IEnumerable_GetEnumerator() As IEnumerator Implements IEnumerable.GetEnumerator`
By the way, members' Name in semantic model for explicit members of interface is generated in the same manner.

**Comment by GrahamTheCoder** [comment]
I had been worried you could call the method from inside the class, but I've double checked and you're right, you have to cast it even within the member, which makes sense since multiple implementations can share the name like [this example ](https://sharplab.io/#v2:C4LghgzsA0AmIGoA+ABAzAAgJYDtgFMAnAMzAGN8MBJAYQHs9C6AbAWACgBvDjXjFACwYACmFzAAFAEoA3BwC+HdNjxFSFagGUAriXL4O3dn35DR46XPaL2ylACYMmsAFsADs3w1mkCBhDU9Iws0Fq66gZcPHyCgQzATMwAdOZ40tG8RiYmKACMSXkAnBIARLTxiSlieCWyGRg2OUJUOnoUVRZS9VnZvHkFucVlrREdNXXGfI189W6EWABuYASmItXAAILMzOmTmfUmAPSHNGA4AOTAGABW2lAYZGDbGMAAFlgQY5Jde9kSEuVgswpC93hApF9LAc+P8WuF9CC3h8IalvlYTDZ5EA===)
