### ISSUE TITLE
VB -> C#: Return statement doesn't include type conversion

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#496]
### Input code
```vbnet
Public Function Empty() As String
    Return 4
End Function
```

### Erroneous output
```C#
public string Empty()
{
    return 4;
}
```

### Expected output
```C#
public string Empty()
{
    return Conversions.ToString(4);
}
```

### Details
* Product in use: 7.6 web
* Haven't checked IL uses `Conversions` methods
* There's a special case in #495

**Comment by Saibamen** [comment]
Why `return Conversions.ToString(4);` instead of `return "4";?

**Comment by GrahamTheCoder** [comment]
Yep good question. The answer is that in the end I'd like to do what you say. But when something's broken, I try to aim to initially get it working as close to what VB produces in the general case as possible. i.e. If it was `Return x + 1`, I believe the VB compiler generates `Return Conversion.ToString(x+1)` under the covers.

Once it fundamentally works, I can iterate and cover special cases like:
* In this specific case we could use _semanticModel.GetConstantValue to optimize away the need for a conversion. In some similar cases this already happens in fact.
* I haven't checked whether (x+1).ToString() would do the same for an integer type. If so, I'd also like to move to using that.
