### ISSUE TITLE
Add support to With Block Syntax in VB.NET for conversion in C#

### ISSUE THREAD

**Issue by Thieum** [icsharpcode/CodeConverter#5]
Code with With Syntax in VB.NET throw a Not Implemented exception:

![image](https://user-images.githubusercontent.com/944894/34227659-ec313c22-e59b-11e7-87bd-bc2da29a3fca.png)

Code example:

```
    Private Shared Function GetTraceData(except As Exception) As String
        Dim messageTrace As New StringBuilder
        Dim trace As New StackTrace(except, True)
        If trace.FrameCount > 0 Then
            With trace.GetFrame(0)
                messageTrace.AppendFormat("File name: {0}", .GetFileName)
                messageTrace.AppendFormat("{0}Line: {1}", Environment.NewLine, .GetFileLineNumber)
                messageTrace.AppendFormat("{0}Column: {1}{0}{0}", Environment.NewLine, .GetFileColumnNumber)
            End With
        End If
        Return messageTrace.ToString
    End Function
```

**Comment by GrahamTheCoder** [comment]
Pretty sure I fixed that here https://github.com/icsharpcode/RefactoringEssentials/commit/3ee3be8c626adbbd24c163b1472d91da7eb94b4e

**Comment by Thieum** [comment]
It was indeed a confusion between Refactoring Essentials v5.,4.160 and Code Converter v5.5.0.0.
The Code Converter action works as intended, but the Refactoring Essentials does not.
Will there be a new release of Refactoring Essentials that drops the code conversion? That seems like the simplest solution for both bugs.

**Comment by GrahamTheCoder** [comment]
Yep, could you check it works on your example with the new version of Refactoring Essentials:
https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.RefactoringEssentialsforVisualStudio2017

**Comment by Thieum** [comment]
It works, thanks !
