### ISSUE TITLE
VB -> C#: Cleaner output for string comparison

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#500]
When comparing against a string literal in VB, the C# output could be cleaner.

### Input code
```vbnet
Public Class VisualBasicClass

    Sub Foo()
        Dim x = ""
        Dim y = x = "something"
    End Sub

End Class
```

### Erroneous output
```C#
public partial class VisualBasicClass
{
    public void Foo()
    {
        string x = "";
        bool y = (x ?? "") == "something";
    }
}
```

### Expected output
```C#
public partial class VisualBasicClass
{
    public void Foo()
    {
        string x = "";
        bool y = x == "something";
    }
}
```

### Details

Version 7.6.0.0

**Comment by GrahamTheCoder** [comment]
Good plan. `VisualBasicEqualityComparison` is a bit of a mess and I think actually misses a couple of cases currently, so feel free to move things around. I assume the rule you mean to add is:
"If either side is a non empty literal (and it isn't generating a string.compare call), there's no need to coalesce"
