### ISSUE TITLE
VB -> C#: Remove duplicated cases in switch

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#502]
### Input code
```vbnet
Select Case Something
  Case "First"
    sth.Farbe = "E1"
  Case "Second"
    sth.Farbe = "E2"
  Case "Third"
    sth.Farbe = "E3"
  Case "First"
    sth.Farbe = "E4"
End Select
```

### Erroneous output
```C#
{
    switch (Something)
    {
        case "First":
            {
                sth.Farbe = "E1";
                break;
            }

        case "Second":
            {
                sth.Farbe = "E2";
                break;
            }

        case "Third":
            {
                sth.Farbe = "E3";
                break;
            }

        case var @case when @case == "First":
            {
                sth.Farbe = "E4";
                break;
            }
    }
}
```

### Expected output
```C#
{
    switch (Something)
    {
        case "First":
        {
            sth.Farbe = "E1";
            break;
        }

        case "Second":
        {
            sth.Farbe = "E2";
            break;
        }

        case "Third":
        {
            sth.Farbe = "E3";
            break;
        }
    }
}
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: 7.6.0.0
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
There was some discussion here: https://github.com/icsharpcode/CodeConverter/issues/374
I think the current output generates a compiler warning. It's up to the programmer to decide whether they intended that code for a different case, or just wrote the same thing twice. Or whether they're using it as an elaborate kind of code comment similar to "if false". 
I appreciate the idea, I agree itd often make things better but for now I'm closing as won't fix.
