### ISSUE TITLE
VB -> C#:  Literal XML in element lookup does not convert

### ISSUE THREAD

**Issue by odigon** [icsharpcode/CodeConverter#503]
### Input code

```vbnet
Private Sub LoadValues(ByVal strPlainKey As String)
            Dim xmlFile As XDocument = XDocument.Parse(strPlainKey)

            Dim objActivationInfo As XElement = xmlFile.<ActivationKey>.First
End Sub
```

### Erroneous output

```csharp
private void LoadValues(string strPlainKey)
    {
        XDocument xmlFile = XDocument.Parse(strPlainKey);
        ;
#error Cannot convert LocalDeclarationStatementSyntax - see comment for details
        /* Cannot convert LocalDeclarationStatementSyntax, CONVERSION ERROR: Conversion for XmlElementAccessExpression not implemented, please report this issue in 'xmlFile.<ActivationKey>' at character 199


        Input:

                    Dim objActivationInfo As XElement = xmlFile.<ActivationKey>.First

         */
    }
```

### Expected output
```csharp
private void LoadValues(string strPlainKey)
{
       var xmlFile = XDocument.Parse(strPlainKey);
       var objActivationInfo = xmlFile.Elements("ActivationKey").First();
}
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / **both**
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above) **7.6.0.0**
* Did you see it working in a previous version, which? **no**
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report and nice example. I've just pushed a fix to master. There is a fair amount more work to do to fully support xml syntax. Feel free to add other examples into #253 to use as test cases.
