### ISSUE TITLE
VB -> C#: Invalid And/Or in if statement

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#522]
### Input code
```vbnet
If Something = "1" And Something2 = "2" Then
    Debug.Print "Test And"
Else If Something = "1" Or Something2 = "2" Then
    Debug.Print "Test Or"
End If
```

### Erroneous output
```C#
{
    if (Something == "1" & Something2 == "2")
        Debug.Print("Test And");
    else if (Something == "1" | Something2 == "2")
        Debug.Print("Test Or");
}
```

### Expected output
```C#
{
    if (Something == "1" && Something2 == "2")
        Debug.Print("Test And");
    else if (Something == "1" || Something2 == "2")
        Debug.Print("Test Or");
}
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: 7.6.0.0
* Did you see it working in a previous version, which? No

**Comment by GrahamTheCoder** [comment]
I believe this is the correct conversion. Here's a very similar example application making use of these non-short-circuit operators:
https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUH1AZgAINiAPPAbz2LtPXVvpt3vdMwAZiBDYgLzEARJmEBuZh049e6QSIlSOASwBmxABSb+AoaOEBKYgDItcwfvRHDy9q2nTUmAJybhAFQCmAZ2DEAQSg4I0k2RwBfO3ovABsfL2J1LR1LETFjZHN5PRFrQ1tw6QdHdmc3T19/AHkwUOi6KKLiJqagA=

Let me know if you're aware of a behaviour difference.

**Comment by GrahamTheCoder** [comment]
Reopening - accidentally closed due to typo

**Comment by GrahamTheCoder** [comment]
^ Ignore the above. I typo'd the issue number in a commit, then got mixed up which state it should be in
