### ISSUE TITLE
#error Cannot convert AssignmentStatementSyntax - see comment for details

### ISSUE THREAD

**Issue by kuxiaochouyu** [icsharpcode/CodeConverter#525]
HI：
this issuse because Chinese quotation marks “are not supported

thanks

**Comment by GrahamTheCoder** [comment]
Thanks, I'll try to look into this soon, should be an easy fix. As a workaround, hopefully you can find-replace the `“` with `"` until it's fixed.

**Comment by kuxiaochouyu** [comment]
> Thanks, I'll try to look into this soon, should be an easy fix. As a workaround, hopefully you can find-replace the `“` with `"` until it's fixed. Support for converting full-width english characters is probably pretty bad too, I'll try to test a few things around this area too.

thanks！ I have replaced all of them with English characters. But I hope it can be improved in this respect.
Vb.net is not strict in character requirements. So, I sometimes develop bad habits.
