### ISSUE TITLE
System.ArgumentException: SyntaxTree is not part of the compilation

### ISSUE THREAD

**Issue by Peter-Simpson** [icsharpcode/CodeConverter#527]
Hi,

I'm using 7.8 and tried to convert a small C# project to VB that is part of a much larger solution and received the exception message below that displays a message: " System.ArgumentException: SyntaxTree is not part of the compilation   Parameter name syntaxtree".

The output window just had the text "Converting ASCOM.Utilities.Support...".

Any thoughts?

Thanks, Peter

![image](https://user-images.githubusercontent.com/38855929/74715787-1b174980-5225-11ea-979d-ef3320baec03.png)

**Comment by GrahamTheCoder** [comment]
Thanks for posting. The stack trace should be enough to fix the bug. I'll try to take a look soon. It's probably something like you've declared a names pace also used in a different project, but used different casing.

**Comment by GrahamTheCoder** [comment]
I can't reproduce the issue, but I have a possible fix in master. You can uninstall your current build and try a CI build here: https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=922&view=artifacts&type=publishedArtifacts or run from source if you'd like to test. Thanks!

**Comment by Peter-Simpson** [comment]
Hi Graham,

 

I think you were on the right lines about something else in the solution interfering because the code converted OK when I put the project into its own solution with nothing else present. I’ll let you know how I get on with the CI build.

 

Many thanks for your prompt response!

 

Regards, Peter

**Comment by Peter-Simpson** [comment]
Hi Graham,

 

Not so good I’m afraid, the CI version doesn’t throw the exception anymore but instead VS goes quiet for a while but then just closes without warning or error message. When I start VS again the code hasn’t been converted and I can repeat the convert / close cycle. In case it’s important I’m using the latest VS version 16.4.5.

 

I’ve uploaded the VS solution containing the problem project here: https://1drv.ms/u/s!Aj1pud_Txa8Sgpwk8QVwyGGuaYRy5Q?e=TERW0S in case it helps find the underlying issue. The ASCOM.Utilities.Support C# project is the one I’m trying to convert to VB as shown below. Overall the solution is about 1.3Gb when uncompressed from the zip file.

 

Many thanks, Peter

**Comment by GrahamTheCoder** [comment]
Hi Peter, it sounds like you may now be hitting #524 which I was in dire need of a repro for, so this will be very helpful. I'll try to look into it in the next few days. Thanks!

**Comment by GrahamTheCoder** [comment]
Hi @Peter-Simpson, I just ran the converter on the whole solution's VB to C# in about 10 minutes. Here are just the changed files that you could unzip at the base directory in case it's helpful:
[ASCOMPlatform - Copy_3360d902608377c83f337039707434e324947b28.zip](https://github.com/icsharpcode/CodeConverter/files/4229872/ASCOMPlatform.-.Copy_3360d902608377c83f337039707434e324947b28.zip)

Since it worked, I suspect something deeper is going on with VS software versions, hardware, or antivirus scanning. I've posted more about it here:
https://github.com/icsharpcode/CodeConverter/issues/524#issuecomment-588832199
