### ISSUE TITLE
VB -> C#: _There were no events while converting the design file.

### ISSUE THREAD

**Issue by kuxiaochouyu** [icsharpcode/CodeConverter#528]
### Input code
       '
        'POW_btnV2DBM
        '
        Me.POW_btnV2DBM.Location = New System.Drawing.Point(207, 15)
        Me.POW_btnV2DBM.Name = "POW_btnV2DBM"
        Me.POW_btnV2DBM.Size = New System.Drawing.Size(42, 23)
        Me.POW_btnV2DBM.TabIndex = 3
        Me.POW_btnV2DBM.Text = ">>"
        Me.POW_btnV2DBM.UseVisualStyleBackColor = True

### Erroneous output
            // 
            // _POW_btnV2DBM
            // 
            this._POW_btnV2DBM.Location = new System.Drawing.Point(207, 15);
            this._POW_btnV2DBM.Name = "_POW_btnV2DBM";
            this._POW_btnV2DBM.Size = new System.Drawing.Size(42, 23);
            this._POW_btnV2DBM.TabIndex = 3;
            this._POW_btnV2DBM.Text = ">>";
            this._POW_btnV2DBM.UseVisualStyleBackColor = true;
           

### Expected output
            // 
            // _POW_btnV2DBM
            // 
            this._POW_btnV2DBM.Location = new System.Drawing.Point(207, 15);
            this._POW_btnV2DBM.Name = "_POW_btnV2DBM";
            this._POW_btnV2DBM.Size = new System.Drawing.Size(42, 23);
            this._POW_btnV2DBM.TabIndex = 3;
            this._POW_btnV2DBM.Text = ">>";
            this._POW_btnV2DBM.UseVisualStyleBackColor = true;
            this._POW_btnV2DBM.Click += new System.EventHandler(this.POW_btnV2DBM_Click);

HI：

I want to add event information when converting design files.

Because there are so many events, there are thousands of events. If it can't be added automatically during file conversion, it will be a very troublesome thing.

thanks

**Comment by GrahamTheCoder** [comment]
Thanks for posting. They can definitely be added, and already should be. I'll see if I can reproduce the issue, but may need more information, for example you didn't include the handling method.

**Comment by Saibamen** [comment]
Fixed in release 8.0.0
