### ISSUE TITLE
Resources not converted VB -> C#

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#540]
Hello,
I have decided to make a test to convert a a small project from vb.net to c#. as I had problems I have 
)tried to do a conversion of a smaller project.

I have made a simple form with one toolstrip button whose picture is in the project resource. The picture resource doesn't exist in the converted project. The picture is there but the project says that there is no [resources]. Here is a small project to reproduce the error.
[WindowsApp1.zip](https://github.com/icsharpcode/CodeConverter/files/4311344/WindowsApp1.zip)
 
- In another project I sometimes have two constructors for a Form but I can't find a reason (I will try to make a project to reproduce later)
- I also have a problem when there is a file 
Resources.nl-BE.Designer.vb in my project : the file has a size of 0 and is not converted but c# want this file (so it must be created manually)

Thank you
Marc

**Comment by GrahamTheCoder** [comment]
Thanks for posting. Part of the issue sounds like #423. I'll have more of a look this weekend, but just in case it helps in the meantime, saving the resource file in visual studio (ensuring code generation is enabled) should regenerate the designer file I think.

The constructor issue sounds related to something I've been changing recently but not released yet. Might be worth trying the latest ci build (vsix file within drop.zip) 
 https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/latest?definitionId=2&branchName=master&status=succeeded

**Comment by marcal** [comment]
Thank you. I will try as this week end
MArc

**Comment by GrahamTheCoder** [comment]
For the default resource, you can workaround the resources issue in the repro by changing a line in the designer.cs file:
`new System.Resources.ResourceManager("WindowsApp1.Resources", typeof(Resources).Assembly)`
to
`new System.Resources.ResourceManager("WindowsApp1.My_Project.Resources", typeof(Resources).Assembly)`

Regenerating the designer file fixes this (i.e. Open the resx file, next to code generation select public, select internal again, then press ctrl+s). Unfortunately it then changes the namespace - which I'll also look into as part of this issue.

Hopefully I'll have time tomorrow to find the best fix for this (and for #423)

**Comment by marcal** [comment]
Hello,

I have made a test project (removed everything from an project to have the error with the resource file.
- The work around with public doesn't work and there is no  resourcemanager... to edit (first part)...

- I also have the error 
Operator '==' cannot be applied to operands of type 'T' and 'default'	Backup
- Also, there is no reference to Microsoft.VisualBasic so there are a lot of errors 
(The converted designer has 
[Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]
that seems to be useless

[Backup.zip](https://github.com/icsharpcode/CodeConverter/files/4333107/Backup.zip)

**Comment by GrahamTheCoder** [comment]
I've made sure the Microsoft.VisualBasic reference gets added in more cases in #545
I'll keep the attribute just for consistency with the input, but you're right it won't do anything.

**Comment by Saibamen** [comment]
Should be fixed in release 8.0.2: https://github.com/icsharpcode/CodeConverter/releases/tag/8.0.2
Please retest

**Comment by marcal** [comment]
Hello,

It is working. Thank you
