### ISSUE TITLE
VB -> C#: Creating constructor in both new .cs and .designer.cs when converting .aspx

### ISSUE THREAD

**Issue by DanPFW** [icsharpcode/CodeConverter#541]
### Input code
there was no constructor in the original vb aspx page class files.

### Erroneous output
.cs
```csharp
    public partial class UserDetail : Web.UI.BasePage
    {
        UserDetail()
        {
            this.PreInit += EmployeeDetail_PreInit;
            this.Load += Page_Load;
        }
```
.designer.cs
```csharp
    public partial class UserDetail
    {
        UserDetail()
        {
            this.PreInit += EmployeeDetail_PreInit;
            this.Load += Page_Load;
        }
```
### Expected output
this results in CS0111 error

### Details
* Product in use: VS extension
* Version in use: 7.9.0.0 on VS2019
* Did you see it working in a previous version, which?  Yes, this appeared to convert OK in December 2019.  I'm not sure what version was available in that timeframe.

**Comment by GrahamTheCoder** [comment]
In some cases it's correct for the converter to generate a constructor if the input has the designer generated attribute. Generating 2 constructors is clearly wrong.

I've been trying to improve this recently, but not released the changes yet. Would you mind trying the latest ci build (vsix file within drop.zip)
https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/latest?definitionId=2&branchName=master&status=succeeded

**Comment by GrahamTheCoder** [comment]
Consolidating into #543 since that has a full repro

**Comment by GrahamTheCoder** [comment]
Fixed, it'll be in the next release, or see instructions on the readme for getting a CI build with it in right now. Thanks!
