### ISSUE TITLE
Version 8.0.0 throws error (revert to 7.9.0 fixes) (VS2017 only)

### ISSUE THREAD

**Issue by suxy110399** [icsharpcode/CodeConverter#542]
Reverting to [https://github.com/icsharpcode/CodeConverter/releases/tag/7.9.0](7.9.0) fixes the issue

### Steps to reproduce
But when I tried to change the code, something went wrong. 
I don't know how to solve this problem. Can you help me see what happened. 

![WS000000](https://user-images.githubusercontent.com/62096777/76508504-7554a480-6489-11ea-951d-75ac725f68cf.jpg)

[ActivityLog.zip](https://github.com/icsharpcode/CodeConverter/files/4323424/ActivityLog.zip)

**Comment by GrahamTheCoder** [comment]
ありがとう。I believe this is a new issue with this release. I'll look into it as soon as I can. Thanks for all the information!

**Comment by Rufistofeles** [comment]
Yeap, thats the same error it shows to me... VS2017 VB to C#

**Comment by GrahamTheCoder** [comment]
There's a chance using a later version of visual studio will fix the error - if you post your current version information from the about box, that might help pinpoint the issue.

If that doesn't work, an older version of the converter is very likely to https://github.com/icsharpcode/CodeConverter/releases/tag/7.9.0

**Comment by GrahamTheCoder** [comment]
Should be fixed in release 8.0.1 coming imminently, dev build of vsix installer available [in drop.zip](https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=1027&view=artifacts&type=publishedArtifacts)

**Comment by suxy110399** [comment]
> There's a good chance using a later version of visual studio will fix the error - if you post your current version information from the about box, that might help pinpoint the issue. I'd be interested in any reasons for not upgrading beyond certain versions to help choose which to support in future.
> 
> If that doesn't work, an older version of the converter is very likely to https://github.com/icsharpcode/CodeConverter/releases/tag/7.9.0

The Version of Vs is Visual Studio Enterprise 2017(15.9.8).
.NET Fremework is Version 4.7.03190
Version of CodeConverter is 8.0.0.
