### ISSUE TITLE
VB -> C#: Too many constructors

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#543]
Hello,

I have made a test for a problem with the constructors (too many constructors).
Here is an example project (I only created a vb.net project, with a splash screen). No line of code required. The conversion will fail.
If I add a second form (Form2) I will have the problem with the 3 forms. The zip file has only one form and one splash screen.
Edit : I used the lastest version (8.0.1.0 )
[WindowsApp1.zip](https://github.com/icsharpcode/CodeConverter/files/4330279/WindowsApp1.zip)

Error	CS0111	Type 'SplashScreen1' already defines a member called '.ctor' with the same 
Error	CS0111	Type 'Form2' already defines a member called '.ctor' with the same parameter 
Error	CS0111	Type 'Form1' already defines a member called '.ctor' with the same parameter 

Thank you again
Marc

**Comment by GrahamTheCoder** [comment]
Consolidating #541 into this since this has the better repro.

**Comment by GrahamTheCoder** [comment]
Fixed, it'll be in the next release, or see instructions on the readme for getting a CI build with it in right now. Thanks!

**Comment by marcal** [comment]
Thank you

**Comment by Saibamen** [comment]
Should be fixed in release 8.0.2: https://github.com/icsharpcode/CodeConverter/releases/tag/8.0.2
Please retest

**Comment by marcal** [comment]
Hello,

It is fixed. Thank you
