### ISSUE TITLE
VB -> C#: Compilation with some errors

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#544]
Hello,

I have made a VB.NET project with a compilation of all the problems I have encountered while converting a middle size project

I use the version 8.0.1.0 (last at the moment of the test)

- For example a Datarow.Item ("TEST") could be converted with Tostring (instead of using the conversion class.
- When there are two classes in one single file, (a module file that contains a class for example), there is a problem...
- When a byte array is initialised (
dim Test as new byte(){2}
the corresponding code has a problem in C#
- When you use 
mid (stringTest,4,1) = "C" tu put the letter C  in the 4th position, it will fail. 

[testconvert.zip](https://github.com/icsharpcode/CodeConverter/files/4332973/testconvert.zip)

EDIT : of course it is a VB.NET project before the conversion.
The code is a simplified version of a project (so it can't run anything, only compile).

Thank you again
Marc

**Comment by GrahamTheCoder** [comment]
Thanks, it's very helpful to have reduced-down versions of these things.
Please ensure that `MainDB.Password` isn't a password actually used for anything!

**Comment by marcal** [comment]
Hello,

Thank you.
 It is not a password, it is an encrypted  password to connect to a SQL Server (unfortunately, integrated login will only work locally or in a network domain).

**Comment by GrahamTheCoder** [comment]
I've improved some of the cases mentioned here, there are still issues with:
* Not quite constant Case in select `Case CChar(".")`
* Two linq query issues (one of them for a very simple expression) (cases of the very general #29)
* String comparison operators (Covered by #396)

**Comment by GrahamTheCoder** [comment]
I believe the simple linq case just needs:
`from CurRow in dtsMain.Tables["tb_Color"]`
to become
`from CurRow in dtsMain.Tables["tb_Color"].AsEnumerable()`

It's IEnumerable, but not IEnumerable of the desired type. An extension method specifically exists which I suspect VB uses, but need to check the IL
