### ISSUE TITLE
VB -> C#: After converting a Winform the events are broken

### ISSUE THREAD

**Issue by davidkdb** [icsharpcode/CodeConverter#547]
After converting a VB.NET form to C# hell breaks loose if trying to do any changes with events.

For example just double clicking on a button in the designer to open the click event of that button.

Since it has no knowledge of the special conversion of events that CodeConverter does, it will create a new event and all event handling in the designer are doubled up. 

To reproduce:
[WindowsApp2.zip](https://github.com/icsharpcode/CodeConverter/files/4343027/WindowsApp2.zip)

Using the attached VB project, convert the solution to C#. Then open the frmSearch form, and look at events. No events are visible on form. Double click on Select button so it will open the click event. Then it creates a new click event, even though it's already a click event from the VB form. Then a lot of errors are created.

Version 8.0.1 (Latest)

**Comment by GrahamTheCoder** [comment]
Thanks for posting. The post conversion winforms development experience was on my list of things to investigate. I think part of the solution might be to move the custom event code out of designer files so it isn't overwritten if that's regenerated.

Hopefully some additional small tweaks to how the events are hooked up in the constructor or initialize component should get the c# designer to be aware of them (I'm not sure how the designer keeps track of them yet)

**Comment by Saibamen** [comment]
Should be fixed in release 8.0.2: https://github.com/icsharpcode/CodeConverter/releases/tag/8.0.2
Please retest
