### ISSUE TITLE
VB -> C#: Select Case enum incorrect cast

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#549]
Hello,

I have a problem with  an Enum of type (short) and a select case (of a value)
The problem doesn't appear everywhere so it was hard to reproduce but I have managed to reproduce it in a project.

[ERREnum.zip](https://github.com/icsharpcode/CodeConverter/files/4362950/ERREnum.zip)

In this example I have a LINQ statment that can't be converted and the equivalent Linq statment in C#.

Thank you
Marc

**Comment by GrahamTheCoder** [comment]
Thanks, I'll take a look soon. Linq is one of the hardest areas to cover, and I'm still hoping to find a more general way to cover it than covering cases one by one, but I'll take a look in case it's pretty close to working.

By the way, if you do find any issues that can be reproduced in the [web converter](https://codeconverter.icsharpcode.net/), it's a bit easier to understand the issue when the code is visible directly in the issue like below. Though I see that in this case, having the linq issue in the same file makes the issue worse, so it's worth having both issues together to show that.

```vbnet
Module Main
    Public Enum EWhere As Short
        ArcTop = -2
        None = 0
        Bottom = 1
        BottomLeft = 13
        BottomRight = 14
        Top = 2
        TopLeft = 23
        TopRight = 24
        Left = 3
        LeftBottom = 31
        LeftTop = 32
        Right = 4
        RightBottom = 41
        RightTop = 42
        ToDefine = 5
        VerticalMulion = 10
        HorizontalMulion = 11
        AllArround = 12
        LeftUnderHandle = 301
        LeftOverHandle = 302
        RightUnderHandle = 401
        RightOverHandle = 402
        CADArcProf1 = 91
        CADArcProf2 = 92
        CADArcProf3 = 93
        CADArcProf4 = 94
        CompVertProf = 103

        FirstVerticalMulion = 105
        SecondVerticalMulion = 106
        ThirdVerticalMulion = 107
        FourVerticalMulion = 108
        FifthVerticalMulion = 109
        SixVerticalMulion = 110
        SevenVerticalMulion = 111
        EightVerticalMulion = 112
        NineVerticalMulion = 113
    End Enum



    Friend Function prtWhere(ByVal aWhere As EWhere) As String
        Select Case aWhere
            Case EWhere.None
                Return " "
            Case EWhere.Bottom
                Return "_ "
            Case EWhere.BottomLeft
                Return "_/ "
            Case EWhere.BottomRight
                Return "_\ "
            Case EWhere.Top
                Return "^ "
            Case EWhere.TopLeft
                Return "^/ "
            Case EWhere.TopRight
                Return "^\ "
            Case EWhere.Left
                Return "/ "
            Case EWhere.LeftBottom
                Return "/_ "
            Case EWhere.LeftTop
                Return "/^ "
            Case EWhere.Right
                Return "\ "
            Case EWhere.RightBottom
                Return "\_ "
            Case EWhere.RightTop
                Return "\^ "
            Case EWhere.VerticalMulion, EWhere.FirstVerticalMulion To EWhere.NineVerticalMulion
                Return "| "
            Case EWhere.HorizontalMulion '11
                Return "- "
            Case EWhere.LeftUnderHandle
                Return "/_-"
            Case EWhere.LeftOverHandle
                Return "/^-"
            Case EWhere.RightUnderHandle
                Return "\_-"
            Case EWhere.RightOverHandle
                Return "\^-"
            Case EWhere.AllArround
                Return "[]"
            Case Else
                Return aWhere.ToString
        End Select

    End Function
End Module

```

**Comment by marcal** [comment]
Hello,
Thank you
I will try to do smaller samples when possible. It is strange in the code you sent, only the None is converted to short.

**Comment by GrahamTheCoder** [comment]
Thanks, it's very much appreciated. I suspect (short) gets added to all by the conversion phase, but then simplified away by the simplification phase. That second phase can be broken by other conversion errors in the same class - I think that's why the full example differs. 

Weirdly I find that the one that gets left in the version I posted above isn't a compile error, but I have no idea why it isn't, and will try to remove (short) from all cases in the fix to this.

**Comment by marcal** [comment]
Hello,
You are right.
It is strange the one that has no error is NONE that has a value of 0.
When I change the value to 999, there is an error. If I change None to something else there is no error so I guess it is the value of 0

**Comment by GrahamTheCoder** [comment]
Yeah must be a special case, though I think I've seen some other special cases that work in the past. Not sure if it's a compiler bug, or a language quirk, but hopefully the converter can avoid it entirely.

**Comment by marcal** [comment]
Hello,
The issue seems to be solved. I am doing a test with a great project to be sure and I will close the case if it is the case

Marc

**Comment by marcal** [comment]
Hello,

The issue is not solved. The problem is still there

**Comment by GrahamTheCoder** [comment]
That makes sense. The simplification phase is a thin wrapper around compiler functions on the code analysis assemblies - the visual studio version determines which version is loaded.
When I look into this I may end up making the fix in the dotnet/roslyn repo as I have for a couple of other issues.
Slightly off topic, but out if interest, is there any specific reason you still use vs2017?

**Comment by marcal** [comment]
Hello,

I only use VS2019, but when I tried to import the "Beta" version of the converter in the VS2019 (double click on the vsix file) only VS2017 was allowed. It was not possible to do it in VS2019. That is why I use the VS2017 for the Beta version and 2019 for the final version.
Perhaps I have to remove the VS2017 completely to begin using the 2019. 
Marc

**Comment by GrahamTheCoder** [comment]
Ah, understood. To install the ci build on vs 2019, you'd need to go into its extension manager and uninstall the code converter extension. Otherwise it won't install because it thinks it's already there.

**Comment by marcal** [comment]
I understand. And as I didn't use VS2017 for  a few month, the version was outdated so an update was possible. Thanks for the explanation.
