### ISSUE TITLE
VB -> C#: Form_Load Event not triggered in converted code

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#550]
Hello,

I have seen another problem while testing conversion of small projects. Here is a zip file to reproduce.
[testhandler.zip](https://github.com/icsharpcode/CodeConverter/files/4367605/testhandler.zip)

I use the last version 8.0.2.0 I have seen that a Form_Load event doesn't trigger in the converted code.
The project opens a Form1 dialog and when I click on the button, the HfrmDB opens but there is no handler in the form_Load Event so the combo box is not filled.

EDIT : It seems to be the Load and Shown events that have the problem (perhaps there are others)
Marc

**Comment by GrahamTheCoder** [comment]
One of the issues here was that while usually VB puts event handlers in the constructor (creating one if needed), for DesignerGenerated classes, it puts them inside InitializeComponent.

There may still be other cases where handlers get missed since the code to cover these cases is getting a little messy. Next time an issue here pops up it could do with some tidying.

**Comment by marcal** [comment]
Hello,

Thank you.
Sometimes I create a non visible class that triggers Events so I guess I will have the problem.

**Comment by GrahamTheCoder** [comment]
Sorry I didn't quite understand

**Comment by marcal** [comment]
Hello,

I have a converter class . This class will convert some user datas. This class defines a public event and when I need to convert datas, if the datas has not been converted before, I trigger an event with the needed information and one parameter byref. The GUI will receive the event and ask for the user to select what value is needed.) I will make a test in that project and see if all is fine (I make tests with some old projects I have).

Thank you again
Marc

**Comment by Saibamen** [comment]
Please retest with recent version

**Comment by marcal** [comment]
Hello,
It is still working fine with 8.0.4.0

Thank you
