### ISSUE TITLE
VB -> C#: Resources files lose their directory (and code can't compile anymore)

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#552]
Hello,

I have tried the last version from the pipeline 20200325.2 (master 77ca73e) (from this morning) and I have seen that the RES files are not in the correct position any more  so the code can't compile after the conversion. It should stay in the same directory as the original project
I have made a sample project (you can simply create a Form, then move the form in a directory and add a toolstrip menu with one button. (so it creates a resx). After that you can do  the conversion. (I have put a zip file so it is simpler) The Res file will be at the root of the project while it should be in the directory where the position is.
The problem wasn't here with the 8.0.2 version before the corrections with the resource files. (in fact there are two resx files : the original one and the new one in the root that is an exact copy). The resources.resx is also copied from the My Project but there is no compilation error.

Thank you
Marc

[TestRES.zip](https://github.com/icsharpcode/CodeConverter/files/4381967/TestRES.zip)

**Comment by GrahamTheCoder** [comment]
I see. The resource associated with forms should stay where they are, only independent resx files should move (or in fact be copied since the converter doesn't delete anything).

It'd be good if I could figure out the exact rule for this. The two different resource types look quite different in the project file, so I'll try a few variants and see if one of these things (e.g. the My.Resources namespace) causes the resx files to be treated as root level:
```xml
    <EmbeddedResource Include="Form\Test\Form1.resx">
      <DependentUpon>Form1.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>WindowsApp1.My.Resources</CustomToolNamespace>
      <SubType>Designer</SubType>
    </EmbeddedResource>
```

**Comment by marcal** [comment]
Hello,

I have made a comparison of the two versions (old and new).
1) The new looks for the resources (Resources.Designer.cs) inside the My project  folder (that is better as the original file is there). 

2) For the file Resources.resX , it is outside of the My project folder , it would be better to move it too in the My Project Folder (there is a warning about it)
3) For the Form (Form1.resx), it is moved outside the sub folder where Form1 is (while before it was in the correct place).

I wonder if there is a reason why you change (copy) the resx files? In the few tests I have made, the copy is exactly the same as the original. Perhaps it is simpler to simply keep the reference from the old project file ?

Thank you
Marc

**Comment by GrahamTheCoder** [comment]
We discussed why they're moved here: https://github.com/icsharpcode/CodeConverter/issues/551#issuecomment-602797493
In order to preserve the name of the resource (changing it could break some programmatic resource accessing code) I believe standalone resx files need to be in the root folder. If there's another way to set the resource name you know of, that would be much easier.

**Comment by marcal** [comment]
Hello,

In that case it would be better to put the designer next to the resx file (for the warning that C# throws) when they are not in the same directory.

I have made some tests and I have an idea.
I have seen that the Field Custom Tool Namespace allows you to chose the namespace to access the ressource. (The field is the value of the first line of the designer of the resource file (
namespace WindowsApp1 {.......
for example the resource TestMarc in the RES diretory  must be accesses by Res.TestMarc
In that field I can enter the Value WindowsApplication1 and I will be able to work with TestMarc directly (even if the resource file is in the RES directory.
![image](https://user-images.githubusercontent.com/3047877/77672463-3e05ed80-6f89-11ea-8597-035c5347075b.png)

The resources files are really a strange thing. For example if you create a directory Form and put a resource file in it you won't be able to compile the code because .NET creates a Form namespace and there is a conflict with Form

**Comment by GrahamTheCoder** [comment]
Sadly the .net code namespace and resource namespace are different things in vb for some reason. Therefore I've continued with moving the non-form resources to the project root directory. I think we're getting close to something releasable now.

**Comment by marcal** [comment]
Hello,
Thank you. I will try to make a test with the last build and report

**Comment by marcal** [comment]
Hello,

The program compiles but the language change doesn't work.
I have a project with (in a Resources directory) where there are files
Lng.de.resx
Lng.fr.resx
Lng.nl.resx
Lng.resx
Lng.Designer.vb

The program moves Lng.resx and Lng.Designer.resx in the main directory of the project. (There is no problem with that, I can move it later).
The problem is that the other files Lng.de.resx (the fr and nl and so on if there are more) are not moved so it is impossible to change the language of the GUI (the Lng...... that are not in the same directory as the Lng.resx  and Lng.Designer.VB (or cs) are ignored so the neutral language is used.

I can make a new case and a project file as example if you want.

**Comment by GrahamTheCoder** [comment]
Thanks for testing. I thought I'd covered that case. I'll retest and let you know if I need a repro. Thanks!

**Comment by GrahamTheCoder** [comment]
Ah, I only tested different locale resource in the root directory - I'll add one in a subfolder

**Comment by GrahamTheCoder** [comment]
OK, I've added some code to try to find other language resources. I'm happy that this is in a better state than the previous release now. Thanks for all your help. If you'd like to, you're very welcome to pull request any test cases directly too by the way. Just add to one of the files like this in most cases: https://github.com/icsharpcode/CodeConverter/blob/master/Tests/CSharp/ExpressionTests/ExpressionTests.cs
See the [readme in the test folder](https://github.com/icsharpcode/CodeConverter/blob/master/Tests/Readme.md) or [contributing guidelines](https://github.com/icsharpcode/CodeConverter/blob/master/.github/CONTRIBUTING.md) for more info.

**Comment by marcal** [comment]
Hello,
Thank you
I will read how to put tests requests directly.
I don't have enough experience with C# to work in fixes.

Marc
