### ISSUE TITLE
VB -> C#:  If TypeOf elt Is type Then  not converted correctly

### ISSUE THREAD

**Issue by dTrimon** [icsharpcode/CodeConverter#562]
### Input code
```vbnet
 If TypeOf elt Is tpe Then
```

### Erroneous output
```C#
 if (elt is tpe)
```

### Expected output
```C#
if (elt.GetType() ==  typeof(tpe))
```

### Details
* Product in use:  VS extension 
* Version in use: 8.0.4.0

**Comment by GrahamTheCoder** [comment]
Thanks for posting. In your case, is tpe a generic type parameter, a variable, a type name? When is the behaviour different? Is there any associated compile or runtime error?

**Comment by dTrimon** [comment]
Sorry for the report, It seems I'm not familiar enough with C#. 
The translation works. The error was elsewhere.

**Comment by GrahamTheCoder** [comment]
No worries, thanks for getting back to me to confirm 🙂
