### ISSUE TITLE
VB -> C#: Unnecessary arg variable and stray ==

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#567]
### Input code
```vbnet
Public Class VisualBasicClass
    Dim arr(,) As String

    Sub DoSomething(ByRef str As String)
        str = "test"
    End Sub

    Sub Main()
        DoSomething(arr(2, 2))
        Debug.Assert(arr(2, 2) == "test")
    End Sub

End Class
```

### Erroneous output
```C#
using System.Diagnostics;

public partial class VisualBasicClass
{
    private string[,] arr;

    public void DoSomething(ref string str)
    {
        str = "test";
    }

    public void Main()
    {
        string argstr = arr[2, 2];
        DoSomething(ref argstr);
        Debug.Assert(arr[2, 2] ==  == "test");
    }
}
```

### Expected output
```C#
using System.Diagnostics;

public partial class VisualBasicClass
{
    private string[,] arr;

    public void DoSomething(ref string str)
    {
        str = "test";
    }

    public void Main()
    {
        DoSomething(ref arr[2, 2]);
        Debug.Assert(arr[2, 2] == "test");
    }
}
```

### Details
* Product in use: Web converter
* Version in use: Version 8.1.0.0

There are a few issues here:

- [ ] Instance variable not updated (covered in #324)
- [x] Additional `==` in the assert
- [ ] Unnecessary variable for the parameter - it's only needed for properties, not fields

**Comment by GrahamTheCoder** [comment]
I think the "==" issue is just because the input VB has "==" which isn't valid in VB. The rest of the issues certainly need dealing with though

**Comment by mrmonday** [comment]
Oh, good point, my bad.

Haven't had to write any VB in a while - successfully purged the last lines from our codebase at the start of the year thanks to CodeConverter :)
