### ISSUE TITLE
C# -> VB: A C# void expression body method is incorrectly converted to a VB method that returns something

### ISSUE THREAD

**Issue by carlossanlop** [icsharpcode/CodeConverter#568]
Expression body methods do not exist in VB, only in C#. Normally people use them to return a value, but it's possible to create an expression body method that returns void. When converting it to VB, the tool adds a return to the invocation inside the method.
It's a tricky problem to solve, because the tool does not know if the internal method returns something or not.

### Input code
```csharp
using System;

public class TestClass
{	
        public void PrintHelloWorld() => Console.WriteLine("Hello world");
}
```

### Erroneous output
```vbnet
Imports System

Public Class TestClass
    Public Sub PrintHelloWorld()
        Return Console.WriteLine("Hello world")
    End Sub
End Class
```

### Expected output
```vbnet
Imports System

Public Class TestClass
    Public Sub PrintHelloWorld()
        Console.WriteLine("Hello world")
    End Sub
End Class

```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
https://converter.telerik.com/ to convert C# to VB.
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
Not sure. Whatever version you have in the website on 2020/05/06 .
* Did you see it working in a previous version, which?
No.
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report, I'll take a look into it

**Comment by GrahamTheCoder** [comment]
I've tried exactly the example given and it produces the expected output on https://codeconverter.icsharpcode.net/ which is the latest version of the converter.
Nothing I can do to get Telerik to update to a later version so I'll close this.
Do feel free to raise a feature request if there's anything you can't achieve with the website/extension/commandline on th readme which are all always the latest version.
