### ISSUE TITLE
VB -> C#: Don't generate unnecessary properties for WithEvents field

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#572]
**Is your feature request related to a problem? Please describe.**
In order to convert a WithEvents field, the converter turns it into a property with a backing field (as the VB compiler also does).
If the field is only internally visible and has no Handles methods, this is redundant, and non-idiomatic C#.

**Describe the solution you'd like**
Use the field directly in the case described.

**Describe alternatives you've considered**
Leave it as it is now for consistency and simplicity of implementation

**Additional context**
It surprised someone in its current state, which is usually a bad sign:
https://github.com/icsharpcode/CodeConverter/issues/569#issuecomment-626743407

**Comment by FrancisVerreault** [comment]
I just experienced it on a very big project. Every component have been updated with an underscore at the begining of the name to let the original name for the getter/setter. It also added renames in the codes so yep there should be an option to choose if you want generated getter and setter.
