### ISSUE TITLE
CodeConverter crashes trying to write to a protected folder

### ISSUE THREAD

**Issue by mdevol** [icsharpcode/CodeConverter#581]
I'm using CodeConverter version 8.1.3.0 and it crashes while trying to convert VB to C#.  The error that is occurring is Access to the path 'C:\WINDOWS\system32\TempCodeToConvert.txt' is denied.  This path is protected and can only be accessed by someone with Administrator permission.  It doesn't appear to be related to the VB file as I get the same error on multiple VB files.  Also, I'm able to convert the same files on a different machine running the same version.  I get the same error in both VS2017 and VS2019.  The stack traces for both VS versions are attached below.

[Code Converter stack trace VS2017.txt](https://github.com/icsharpcode/CodeConverter/files/4831254/Code.Converter.stack.trace.VS2017.txt)
[Code Converter stack trace VS2019.txt](https://github.com/icsharpcode/CodeConverter/files/4831259/Code.Converter.stack.trace.VS2019.txt)

Forgot to mention that I have uninstalled CodeConverter from both VS versions and reinstalled and got the same result.

**Comment by GrahamTheCoder** [comment]
Apologies I forgot to release this fix to this.
Aka #578
