### ISSUE TITLE
C# -> VB: Code conversion ends in a .txt file

### ISSUE THREAD

**Issue by mdevol** [icsharpcode/CodeConverter#589]
Installed the latest version of CodeConverter (8.1.5) and when I converted a VB file to C# it resulted in a TempCodeToConvert.txt file in <user folder>\AppData\Local\Temp directory instead of a CS file in the same folder as the VB file.  The TXT file is the converted C# code, apparently it just didn't get moved and renamed.  The conversion completed successfully with no errors and there are no error messages in the Application event log.

**Comment by GrahamTheCoder** [comment]
Just to check a bit more on your use case, is it just that the syntax highlight didn't work because of the code extension? Or did you actually want the file to be there on disk? 
Would it be even better to just open a code window (with syntax highlight) without saving to disk?

**Comment by mdevol** [comment]
I was copying the VB file to be converted to my C# project and then right clicking the file (not included as part of the C# project) and selecting Convert to C#.  It was this conversion that was resulting in a .txt file instead of a .cs file in the project folder.

I did do a test this morning and tried to convert the VB file directly from its VB project and that worked as expected.  It created a .cs file and put it in the originating project folder.

I'm pretty sure my original conversion method worked in a previous version of CodeConverter.  So I'm either mistaken or this was a change to CodeConverter.  In any event, I now know I need to do the conversion in the VB project first and then move the .cs file.  Sorry for the confusion.

________________________________

**Comment by GrahamTheCoder** [comment]
Thanks for the extra context, that really helps! If you have the source file in a compiling project, the converter can do a much better job, so I think your new workflow should actually be better for your use case.

That said, I can imagine a related case where someone creates a file with text pasted from stackoverflow for example, so I'll try and fix it up if I can. Note to self: #245 and #247 also cover single file conversion use cases.
