### ISSUE TITLE
C# -> VB: VisitEmptyStatement

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#59]
There is an empty statement in the file CSharp\CommentConvertingNodesVisitor.cs that is preventing it from being converted to VB.  I can see 2 options to fix it.

**Option 1:**

Add to VB\MethodBodyVisitor.cs
```
public override SyntaxList<StatementSyntax> VisitEmptyStatement(CSS.EmptyStatementSyntax node)
{
	return SyntaxFactory.List<StatementSyntax>();
}
```
Add a null check in DefaultVisit method in VB\CommentConvertingMethodBodyVisitor.cs
```
public override SyntaxList<VBSyntax.StatementSyntax> DefaultVisit(SyntaxNode node)
{
	var syntaxNodes = wrappedVisitor.Visit(node);

	if (syntaxNodes == default(SyntaxList<VBSyntax.StatementSyntax>))
		return syntaxNodes;

	// Port trivia to the last statement in the list
	var lastWithConvertedTrivia = triviaConverter.PortConvertedTrivia(node, syntaxNodes.LastOrDefault());
	return syntaxNodes.Replace(syntaxNodes.LastOrDefault(), lastWithConvertedTrivia);
}
```

**Option 2:**
Change VisitMethodDeclaration in VB\VB\NodesVisitor.cs at line 388 so the EmptyStatements are not processed.  This is what is done in ConvertBlock in VB\VB\MethodBodyVisitor.cs.

**Comment by GrahamTheCoder** [comment]
Thanks! I went for something pretty close to option 1. When it's something that doesn't touch much code like this, where it takes the same amount of time to PR as write an issue, feel free to just open a PR without raising the issue first. In some case it might conflict, but if it's a small change that's easily fixed anyway.
