### ISSUE TITLE
VB -> C#: Enum with numerical value behavior change

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#590]
### Input code
```vbnet
Public Class Form1
    Private Enum TestEnum As Byte
        None = 0
        Tpe1 = 1
        Tpe2 = 2
        Tpe3 = 3
    End Enum

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim VarEnum As TestEnum = TestEnum.Tpe2

        MessageBox.Show("VarEnum Value " & VarEnum)
    End Sub
End Class

```

### Erroneous output
```C#
 private enum TestEnum : byte
        {
            None = 0,
            Tpe1 = 1,
            Tpe2 = 2,
            Tpe3 = 3
        }

        private void Button1_Click(object sender, EventArgs e)
        {
            var VarEnum = TestEnum.Tpe2;
            MessageBox.Show("VarEnum Value " + VarEnum);
        }
```

### Expected output
```C#
 MessageBox.Show("VarEnum Value " +(byte) VarEnum);
```

### Details

In VB.NET, the enum uses the byte (type byte) value not the Enum name so in VB.NET the message is 
"VarEnum Value 1"
In C#, the value is the name of the Enum. So the message is 
"VarEnum Value Tpe2"

I use the .NETplugin 8.1.5.0.
I am not sure if it worked before (I think that it worked 2 month ago but I am not sure) It could be related to #549 
where the correction was too aggressively triggered?

Thank you
Marc

**Comment by GrahamTheCoder** [comment]
I'm surprised to hear that's what VB does, but it should be reasonably easy to fix the conversion I think. Thanks

**Comment by marcal** [comment]
Hello,

I think it depends on the type of enum (I declare all my enum as integer, bytes or short) but you can declare Enum without a type

**Comment by GrahamTheCoder** [comment]
If you don't declare explicitly I expect it'll be int, same as c#

**Comment by marcal** [comment]
Hello,
I have made a test 
In VB.NET
Private Enum TestEnum
        None
        Tpe1
        Tpe2
        Tpe3
    End Enum

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim VarEnum As TestEnum = TestEnum.Tpe2

        MessageBox.Show("VarEnum Value " & VarEnum)
    End Sub

will give an integer value (0,1,2,3 even with no number) (auto increment 0 for none, 1 for Tpe1..)
