### ISSUE TITLE
VB -> C#: Problem with Operator and Nothing

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#591]
Hello, 
there is a problem when using the operator and one of the class is null
(if Test1 is nothing). In VB.NET the test returns true without entering into the operator code.
In VB.NET a message appears (TEST)
In C# there is a crash.

### Input code
```vbnet
Public Class Form1
    Dim Test1 As CTst

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        If Test1 Is Nothing Then
            MessageBox.Show("Test ")
        End If

    End Sub


End Class

Friend Class CTst
    Public List As New List(Of Integer)

    Public Sub New()
    End Sub


    Public Shared Operator <>(ByVal aCls1 As CTst, ByVal aCls2 As CTst) As Boolean
        Return Not (aCls1 = aCls2)

    End Operator
    Public Shared Operator =(ByVal aCls1 As CTst, ByVal aCls2 As CTst) As Boolean
        If aCls1.List.Count <> aCls2.List.Count Then Return False
        Return True
    End Operator

End Class

```

### Erroneous output
```C#
 public partial class Form1
    {
        public Form1()
        {
            InitializeComponent();
            _Button1.Name = "Button1";
        }

        private CTst Test1;

        private void Button1_Click(object sender, EventArgs e)
        {
            if (Test1 == null)
            {
                MessageBox.Show("Test ");
            }
        }
    }

    internal class CTst
    {
        public List<int> List = new List<int>();

        public CTst()
        {
        }

        public static bool operator !=(CTst aCls1, CTst aCls2)
        {
            return !(aCls1 == aCls2);
        }

        public static bool operator ==(CTst aCls1, CTst aCls2)
        {
            if (aCls1.List.Count != aCls2.List.Count)
                return false;
            return true;
        }
    }
```

### Expected output
```C#
 public partial class Form1
    {
        public Form1()
        {
            InitializeComponent();
            _Button1.Name = "Button1";
        }

        private CTst Test1;

        private void Button1_Click(object sender, EventArgs e)
        {
            if (Test1 is null)
            {
                MessageBox.Show("Test ");
            }
        }
    }

    internal class CTst
    {
        public List<int> List = new List<int>();

        public CTst()
        {
        }

        public static bool operator !=(CTst aCls1, CTst aCls2)
        {
            return !(aCls1 == aCls2);
        }

        public static bool operator ==(CTst aCls1, CTst aCls2)
        {
            if (aCls1.List.Count != aCls2.List.Count)
                return false;
            return true;
        }
    }
```

### Details
Version 8.1.5.0
Hello,
When there is a test with is nothing it is converted to ==null that triggers the operator == (that crashes in the List.Count)
while we could use is null to solve the problem.

EDIT If I compare 
Dim Test1 As New CTst
Dim Test2 As CTst
if Test1 is Test2 (VB.NET) (to see if I have the same reference (so object) there is a crash in C#
if (Test1 == Test2)  will crash if one of the class is null
you must use if ( object.ReferenceEquals(Test1,  Test2))
EDIT2 : in the reflector there is (object)Test1 == (object) Test2
For the first case (is null instead of ==) in the reflector it is still converted to == but there is no crash)

**Comment by GrahamTheCoder** [comment]
I think a previous version did this, but I had done reason to change it back because it wasn't working in another case. I'll look into it some more. Thanks!

**Comment by marcal** [comment]
Hello,

I have seen something strange with the decompiler.
Ilspy gives 
´´´CS
if ((object)Test1 == null)
	{
		MessageBox.Show("Test ");
	}
	Test2 = new CTst();
	if ((object)Test1 == Test2)
	{
		MessageBox.Show("Test ");
	}
´´´

While telerik gives


´´´CS
 if (this.Test1 == null)
            {
                MessageBox.Show("Test ");
            }
            this.Test2 = new CTst();
            if ((object)this.Test1 == (object)this.Test2)
            {
                MessageBox.Show("Test ");
            }

´´´

**Comment by GrahamTheCoder** [comment]
Thanks, yes we need to either cast (at least) one of the sides to object, or use object.referenceequals.
I think I'll fix it by converting " Is Nothing" as something like " == ((object) null)" or " == default(object)"

**Comment by GrahamTheCoder** [comment]
I've found the reason I switched away from "is null": to keep compatibility for old non-sdk project formats which don't support C# 7.3+ features according to my own note

**Comment by marcal** [comment]
Hello,
The problem with Is null is working.
There is still a problem when you compare two classes and one class is null (

I will open another case.

**Comment by GrahamTheCoder** [comment]
Ah I see. "Is" always needs to be reference equality, not just for "Nothing"

**Comment by marcal** [comment]
Hello,

Yes. In VB.NET  "is" will always compare references
For example  
If Test1 = Test2 Then  
Will use the operator
While  If Test1 is Test2 Then will see if the items have the same reference

```VB
Test2 = New CTst
Test1 = New CTst
If Test1 Is Test2 Then
    MessageBox.Show("Test ")
End If
```
Won't print anything

And
```VB
Test2 = New CTst
Test1 = New CTst
If Test1 = Test2 Then
    MessageBox.Show("Test ")
End If
```
Will print Test because the items have the same value (at least with an operator)
Without an "=" operator, it is a syntax error to use = between objects
