### ISSUE TITLE
VB -> C#: Excel .Value calls not converting assignment segment from VB

### ISSUE THREAD

**Issue by JiggsUK** [icsharpcode/CodeConverter#597]
### Input code
```
CType(m_ws.Cells(1, 1), Excel.Range).Value = reportName
CType(m_ws.Cells(1, 2), Excel.Range).Value = "From"
CType(m_ws.Cells(2, 2), Excel.Range).Value = "To"
CType(m_ws.Cells(1, 3), Excel.Range).Value = dtp_From.Value.Date
CType(m_ws.Cells(2, 3), Excel.Range).Value = dtp_To.Value.Date
```

### Erroneous output
```
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[1, 1]).Value;
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[1, 2]).Value;
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[2, 2]).Value;
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[1, 3]).Value;
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[2, 3]).Value;
```

### Expected output
```
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[1, 1]).Value = reportName;
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[1, 2]).Value = "From";
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[2, 2]).Value = "To";
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[1, 3]).Value = dtp_From.Value.Date;
((Microsoft.Office.Interop.Excel.Range)m_ws.Cells[2, 3]).Value = dtp_To.Value.Date;
```

### Details
* Product in use: VS extension
* Version in use: 8.1.6.0
* Did you see it working in a previous version, which? not used a previous version
* Any other relevant information to the issue, or your interest in contributing a fix.

It seems to specifically involve a .Value call in VB. I have other lines with assignments in a similar style that do convert correctly - e.g. NumberFormat is fine:
VB: `CType(m_ws.Columns(column.Ordinal + 1), Excel.Range).NumberFormat = "dd-mmm-yyyy"`
C#: ` ((Microsoft.Office.Interop.Excel.Range)m_ws.Columns[column.Ordinal + 1]).NumberFormat = "dd-mmm-yyyy";`

**Comment by GrahamTheCoder** [comment]
Interesting case because it works in the Web converter. I'll try it in visual studio when I get the chance, thanks for reporting

**Comment by GrahamTheCoder** [comment]
Yes I can reproduce in visual studio if I install:
`<PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1000" />`

If I remove the import, the conversion is "guessed" correctly, but with it, the conversion is wrong, so it must be getting confused about some detail of the library, I'll take a closer look

```vbnet

Imports Microsoft.Office.Interop

Public Class Issue597
    Private m_ws As Excel.Worksheet
    Public Sub MySub(reportName As String, dtp_From As Excel.Range, dtp_To As Excel.Range)
        CType(m_ws.Cells(1, 1), Excel.Range).Value = reportName
        CType(m_ws.Cells(1, 2), Excel.Range).Value = "From"
        CType(m_ws.Cells(2, 2), Excel.Range).Value = "To"
        CType(m_ws.Cells(1, 3), Excel.Range).Value = dtp_From.Value.Date
        CType(m_ws.Cells(2, 3), Excel.Range).Value = dtp_To.Value.Date
    End Sub
End Class
```

**Comment by GrahamTheCoder** [comment]
`Excel.Range.Value` is a parameterized property. The converter currently expects parentheses to follow a parameterized property invocation, but of course that isn't necessary in VB, especially when its parameter is optional (like this one).
If you add them, it gives the correct conversion in Visual Studio. In C# parameterized properties don't exist so you need to call `set_Value(reportName)` (so the web conversion was actually wrong for this case even though it appeared correct at first glance)
