### ISSUE TITLE
Long hang while converting VB proj to C#

### ISSUE THREAD

**Issue by docfresh** [icsharpcode/CodeConverter#598]
### Steps to reproduce
1.  Open a solution with multiple project types
2.  Right-click a VB Winforms project and Convert to C#
3.  After initially converting some files, the converter has been hung for over half an hour.  Visual Studio CPU usage is pegged at 30%

```
* HHWindow.vb - conversion succeeded
* lvCart.vb - conversion started
* frmnewtest.vb - conversion succeeded
* lvCart.vb - conversion succeeded
* frmBlankForm.vb - conversion succeeded
* dsInvoice.vb - conversion succeeded

^ hangs here

```

No error message.

### Details
* Visual Studio 16.6.4
* Product in use:  VS extension 
* Version in use: 8.1.6
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

I have an ActivityLog.XML (560kb) but don't see anything noteworthy --- what should I look for?

**Comment by GrahamTheCoder** [comment]
If you look at (or post) the full contents of the output window, I suspect you'll find that it lists every file in the project. But one or two of them (probably one near the start) only says "started", never succeeded. You'll likely find that file over 5k lines - the roslyn formatter called after conversion preforms very badly on such files. 
Usually (but not always) some significant patience will yield a result, but it'll probably go much faster if you split the file into partial classes under 5k lines.

If you find it's a reasonably small file causing the issue, that may indicate a performance issue in the conversion code, in which case if you can post the contents that would be a great help.

I think I'll disable the formatting operation in a future version for either big files or after a timeout.

**Comment by docfresh** [comment]
Thanks for the info. Yes you are spot on. Some of these files are massive. I will try running it overnight to see how that goes. Failing that, I will try splitting into partial classes.  Will let you know how it goes!

**Comment by docfresh** [comment]
Letting it run overnight worked.  I found 2 other issues which I'll report elsewhere. Thank you!

**Comment by edwardmiller87** [comment]
I like the timeout idea because the Rosyln formatter in the future may solve this performance problem.
