### ISSUE TITLE
Multiple entries in the different context menus

### ISSUE THREAD

**Issue by Thieum** [icsharpcode/CodeConverter#6]
Using Visual Studio 15.5.2, I have 4 entries for the conversion action with no noticeable differences:

![image](https://user-images.githubusercontent.com/944894/34227775-5ed92c58-e59c-11e7-883b-7a4188c6f232.png)

![image](https://user-images.githubusercontent.com/944894/34227793-708bf50c-e59c-11e7-8378-b11e407967ae.png)

![image](https://user-images.githubusercontent.com/944894/34227817-8185eb10-e59c-11e7-81ea-6838b86fbdd9.png)

![image](https://user-images.githubusercontent.com/944894/34227835-93090ae8-e59c-11e7-9637-f82963c9cadf.png)

One entry should be enough if the action is the same.

**Comment by christophwille** [comment]
Duplicates would be possible if you had Refactoring Essentials installed too - but four is definitely not intended.

**Comment by GrahamTheCoder** [comment]
Which versions of which extensions do you have installed?
If you have a pre-split refactoring essentials, and the converter separately, that'd explain two of the menu items at least

**Comment by christophwille** [comment]
Hopefully we will get around to publishing a new version of RE tomorrow which no longer has the code converter functionality in it.

**Comment by christophwille** [comment]
RE 5.6 is now online in the VS marketplace. Please verify. Thanks!

**Comment by Thieum** [comment]
It works, thanks !
