### ISSUE TITLE
Enable checks that test conversion code compiles

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#60]
Originally this was to track a collection of test improvements, the title has been updated to reflect remaining task.

Either add new tests, or add to the current test harness things like:
* Test that the input and output of existing tests compiles - they're just text strings and it's easy to accidentally be verifying incorrect behaviour
* Once the above is done, it may at least be interesting diffing the IL compiled from the input and output (obviously won't match in all cases, but would give great confidence for the ones it works for)
* Roundtripping e.g. VB -> C# -> VB -> C# and test the results of the first and third conversion are the same (don't expect both VB to be the same in this instance due to whitespace etc.)
* Tests with self-verifying inputs - i.e. We can run the input and output and check they have the same result.

**Comment by siegfriedpammer** [comment]
> Diffing the IL compiled from the input and output (obviously won't work in all cases, but would give great confidence for the ones it works for)
This won't work at all, except for very simple programs, because csc and vbc produce very different IL most of the time.

Suggestion: Testing Behavior? That is, convert a program, compile the source and the converted program, execute both and compare their output. If both compile and produce the same output, conversion is successful.

**Comment by GrahamTheCoder** [comment]
That is what I thought of first, and indeed I've worked on something previously where actually running the input and output worked well so I'll take the recommendation and add it to the description.

I figured the IL being equivalent is the step up from knowing the program has the same result for one or two inputs. Maybe I'm overestimating how many of even the simple cases it'll work for, but I think it's really easy to implement so I'll probably try it anyway and see.

**Comment by GrahamTheCoder** [comment]
The self verifying tests introduced in #216 allow the deeper level of testing this issue was intended to track and their use has been proven in #210

The remaining task to close this issue is to turn on reporting of compile errors in the normal tests (with some way to override it, since imperfect code should still be convertible)

**Comment by GrahamTheCoder** [comment]
I recently added warnings by copying the VB namespace code in. These will need to be fixed as part of this

**Comment by GrahamTheCoder** [comment]
Covered by #539
