### ISSUE TITLE
VB -> C#: Cannot convert ForEachBlockSyntax

### ISSUE THREAD

**Issue by docfresh** [icsharpcode/CodeConverter#601]
Ran into this after conversion.

### Input code
    Public Sub PopulateFormWinListAndOrderTotal(ByVal frm As frmNewInvoice)
        Dim sngOrderTotal As Single
        frm.lstWindows.Items.Clear()
        For Each Win In WinOrd.colWindows
            WinModel.Populate(Win.GetWinStyleID())

            'if part of a bay or bow do not include window as part of order total since its already figured for in the bay or bow
            If Win.strSuperType <> "BB" Then
                sngOrderTotal = sngOrderTotal + (Win.GetTotalPrice() * Win.GetWinQty())
                frm.lstWindows.Items.Add(New Mylist(WinModel.GetWinAbbreviation() & " " & Win.GetWidth() & " x " & Win.GetHeight() & " (" & Win.GetWinQty() & ")", Win.GetInvItemID()))
            Else
                frm.lstWindows.Items.Add(New Mylist("**" & WinModel.GetWinAbbreviation() & " " & Win.GetWidth() & " x " & Win.GetHeight() & " (" & Win.GetWinQty() & ")", Win.GetInvItemID()))
            End If

        Next
        frm.lblOrderTotalRetail.Text = sngOrderTotal
        frm.lblOrderTotalDealer.Text = (sngOrderTotal * WinOrd.GetSoldMultiplier())
    End Sub

### Erroneous output

#error Cannot convert ForEachBlockSyntax - see comment for details

/* Cannot convert ForEachBlockSyntax, System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.
               at ICSharpCode.CodeConverter.CSharp.MethodBodyExecutableStatementVisitor.<VisitForEachBlock>d__61.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at ICSharpCode.CodeConverter.CSharp.HoistedNodeStateVisitor.<AddLocalVariablesAsync>d__6.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingMethodBodyVisitor.<DefaultVisitInnerAsync>d__3.MoveNext()

### Details
* Product in use:  VS extension 
* Version in use: 8.1.6.0
* Did you see it working in a previous version, which? no

**Comment by GrahamTheCoder** [comment]
Thanks for the report. There isn't quite enough context for me to immediately reproduce the issue.
If you have time, could you try removing various bits within the foreach loop, converting the single file and see what the minimum needed to break it is? Thanks

**Comment by docfresh** [comment]
Here you go -- the class file with its members, a constructor, and the offending function. I could reproduce the bug by adding this file to a WinForms VB.NET project,  and attempting a convert. 
[ConWinOrders.zip](https://github.com/icsharpcode/CodeConverter/files/5017339/ConWinOrders.zip)

**Comment by docfresh** [comment]
Here is a VB project ready to convert / throw the bug.
[convertbug2a.zip](https://github.com/icsharpcode/CodeConverter/files/5017385/convertbug2a.zip)

**Comment by GrahamTheCoder** [comment]
Thanks!

**Comment by GrahamTheCoder** [comment]
I reproduced an error. Using a class member as the foreach variable should be supported in the next release.
