### ISSUE TITLE
VB -> C#: Error converting a For loop

### ISSUE THREAD

**Issue by FeaXR** [icsharpcode/CodeConverter#602]
### Input code
```vbnet
For i As Integer = 0 To i < OldWords.Length
            HTMLCode = HTMLCode.Replace(OldWords(i), NewWords(i))
        Next i
```

### Erroneous output
```C#
 for (var i = 0, loopTo = i < OldWords.Length; i <= Conversions.ToInteger(loopTo); i++)
                HTMLCode = HTMLCode.Replace(OldWords[i], NewWords[i]);
```

### Expected output
```C#
 for (var i = 0; i < OldWords.Length; i++)
            {
                HTMLCode = HTMLCode.Replace(OldWords[i], NewWords[i]);
            }
```

### Details
* Product in use:  VS extension, VS Community 16.6.5
* Version in use: 8.1.6.0

**Comment by GrahamTheCoder** [comment]
Hi thanks for getting in touch. Can you tell me about what problem the erroneous output is causing you? Is it that it doesn't compile (e.g. Missing reference to Conversions), does the wrong thing, or you just don't like the look of it?

I believe the loopTo variable more accurately reflects what VB does. I.e. If a method in the loop, or another thread changes the length of Old Words, I think your suggested output would behave differently to the VB.

The Conversions method looks entirely redundant, and shouldn't be generated if there's type information. Were the variables or properties defined with types?

**Comment by FeaXR** [comment]
The loopTo variable is non existent and never gets changed in the loop, thus rendering it useless.  The OldWords array never changes, especially in the for loop. 
Even if it did change, I believe 

` for (var i = 0; i < OldWords.Length; i++)
            {
                HTMLCode = HTMLCode.Replace(OldWords[i], NewWords[i]);
            }`
would still do the same thing, since it is checking if the iterator is greater than any possible index of the array.

**Comment by GrahamTheCoder** [comment]
Ah, now I'm reading on a proper-sized screen I see you've used a boolean as the limit on your for loop which is very unusual. Based on your expected output (converting it back to VB) your input should probably have been [this](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfACgVwsAlgYwAQGFgBDAZxIIFgAoXW3NDHXAZXVwFkAKAeWBgHUA9gCcY5AILlmAF2GYAdgHNOASii4AcgFMA7kNESpshcrW4AEgBV2AGXyCYW3JJbGlK6nS+4AYiNyYzuQAkvLSWopawrgAvLgADLiWgri8AiJiAHQ2WkrSABa4ALS4AIye3pVWtvaOsRbWdg5amQBKWgAOxNhaPHz6YpyYZtp6GSRDKh40lZpaAB7SARW0AKLyMCzo1OubhKQkK7O0R8dAA):
```vbnet
Public Class C
    Public Sub M(OldWords As String(), NewWords As String(), HTMLCode As String)
        For i As Integer = 0 To OldWords.Length - 1
            HTMLCode = HTMLCode.Replace(OldWords(i), NewWords(i))
        Next i
    End Sub
End Class
```

For that input, it does then convert to C# correctly - actual converted output:
```csharp
public partial class C
{
    public void M(string[] OldWords, string[] NewWords, string HTMLCode)
    {
        for (int i = 0, loopTo = OldWords.Length - 1; i <= loopTo; i++)
            HTMLCode = HTMLCode.Replace(OldWords[i], NewWords[i]);
    }
}
```

But even though I think it was a bug that lead here the bug report is still relevant. The VB you gave does compile, and is a feature people sometimes intentionally use in VB, so I'll try and improve the converter support around it at some point.

Hope that makes sense. Let me know if I've misunderstood, thanks for reporting!

**Comment by GrahamTheCoder** [comment]
I've handled the boolean To expression case.
I'm not planning to handle the case where `OldWords` is not declared, since I only usually support very common non-compiling input and this is an edge case.

**Comment by FeaXR** [comment]
Yes, you understood correctly :)
Sadly I didn't really have control over the input, as I was just given the code and I just had to transfer it to C#. Thanks a lot for your quick reply and fix, what you are doing is amazing.

**Comment by Saibamen** [comment]
@FeaXR: Please retest. New version is already available
