### ISSUE TITLE
VB -> C#: externally declared range variable in For loop can require type conversion

### ISSUE THREAD

**Issue by jamesmanning** [icsharpcode/CodeConverter#609]
### Input code
```vbnet
    Sub Main()
        Dim foo As Single = 3.5
        Dim index As Integer
        For index = Int(foo) To Int(foo * 3)
            Console.WriteLine(index)
        Next
    End Sub
```

### Erroneous output
```C#
        public static void Main()
        {
            float foo = 3.5F;
            int index;
            var loopTo = Conversion.Int(foo * 3);
            for (index = Conversion.Int(foo); index <= loopTo; index++)
                Console.WriteLine(index);
        }
```

### Expected output
since the Int() call returns float instead of integer (odd, but I'm not that familiar with VB so maybe it's a compat thing) , we need to cast it to integer so it can get assigned to the existing integer variable from outer scope
```C#
        public static void Main()
        {
            float foo = 3.5F;
            int index;
            var loopTo = Conversion.Int(foo * 3);
            for (index = (int)Conversion.Int(foo); index <= loopTo; index++)
                Console.WriteLine(index);
        }
```

### Details
* VS extension 8.1.6.0

**Comment by GrahamTheCoder** [comment]
Ah yes, you're exactly right it's the fact the variable is declared separately that's throwing off the current code getting the type info. Should be an easy fix.

**Comment by jamesmanning** [comment]
Awesome, thank you for such a quick fix! You rock @GrahamTheCoder !  👍
