### ISSUE TITLE
C# -> VB: Support Throw Expressions

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#61]
```
  Error processing Vsix\ConvertCSToVBCommand.cs
    In 'C:\Users\Graham\Documents\GitHub\CodeConverter\Vsix\ConvertCSToVBCommand.cs':
    System.NotImplementedException: Cannot convert ThrowExpressionSyntax from 'throw new ArgumentNullExcep...' at character 2446
     in 'package ?? '
       at ICSharpCode.CodeConverter.VB.CSharpConverter.MethodBodyVisitor.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitThrowExpression(ThrowExpressionSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.ThrowExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
       at ICSharpCode.CodeConverter.VB.CommentConvertingMethodBodyVisitor.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitThrowExpression(ThrowExpressionSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.ThrowExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
       at ICSharpCode.CodeConverter.VB.CSharpConverter.NodesVisitor.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.VisitThrowExpression(ThrowExpressionSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.ThrowExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
       at ICSharpCode.CodeConverter.VB.CommentConvertingNodesVisitor.DefaultVisit(SyntaxNode node)
       ...
```

### Option 1
Add a ThrowEx method that's something like
``` 
Private Shared Function ThrowEx(Of T)(ByVal e As Exception) As T
    Throw e
End Function
```
Calling code
```
ThrowEx(Of Integer)(New Exception)
```
Then just replace the throw expression with a call to that. The generic is so that the rest of the expression can get the right type. It's a bit messy, and needs to add a method which is awkward for snipped conversions, but does keep the code pretty readable in the context it was written.

### Option 2
Define a function outside the block, then use it where the original throw would have been

```
        Dim throwEx As Func(Of Integer) = 
                Function()
            Throw New Exception
        End Function
        Dim asd = IIf(True, 9, throwEx())
```

This avoids having to add an extra method at the class level (which means sub-method snippets will convert less cleanly), at the expense of more code for each time this is used.

### Proposal
Option 1. We can always implement option 2 as a special case if someone's particularly enthusiastic about it.

**Comment by RussellSmith2** [comment]
One place Throw Expressions are used is in Simple Lambda Expressions. This one can be addressed in first line of VisitSimpleLambdaExpression in the VB\NodesVisitor.cs file.

```c#
if (node.Body.IsKind(CS.SyntaxKind.ThrowExpression)) {
	var attributeList = SyntaxFactory.List<AttributeListSyntax>();
	var modifiers = SyntaxFactory.TokenList(node.AsyncKeyword);
	var emptyParameters = SyntaxFactory.ParameterList();
	var header = SyntaxFactory.FunctionLambdaHeader(attributeList, ConvertModifiers(modifiers, TokenContext.Local), emptyParameters, null);

	var body = (CSS.ThrowExpressionSyntax)node.Body;
	var throwExpression = (ExpressionSyntax)body.Expression.Accept(TriviaConvertingVisitor);
	var throwStatement = (StatementSyntax)SyntaxFactory.ThrowStatement(SyntaxFactory.Token(SyntaxKind.ThrowKeyword), throwExpression);
	var endFunctionStatement = SyntaxFactory.EndFunctionStatement();

	return SyntaxFactory.MultiLineFunctionLambdaExpression(header, SyntaxFactory.SingletonList(throwStatement), endFunctionStatement);
}
```

Or the code can be refactored and used in ConvertLambdaExpression in the same file.

This will address an error when converting the method ConvertQueryBodyClause in the file CSharp\NodesVisitor.cs to VB.

**Comment by GrahamTheCoder** [comment]
Yep I think your solution would work for an async lambda containing just a throw expression. To avoid adding hundreds of special cases to the code I'm intending to investigate creating a general case of this now corresponding to "Option 1" described above.

**Comment by RussellSmith2** [comment]
For normal Throw Expressions I had went for a different option.

From CodeWithOptions.cs:
```c#
Text = text ?? throw new ArgumentNullException(nameof(text));
```

To:
```vbnet
Me.Text = text

If text Is Nothing Then
    Throw New ArgumentNullException(NameOf(text))
End If
```

I had been converting Throw Expressions in VisitBinaryExpression.  After checking if the nodes was a CoalesceExpression then check if the right is a throw expression.

Then in VisitExpressionStatement add the extra statements.

My previous idea about doing the conversion in VisitSimpleLambdaExpression was a one time special case because they were different.

**Comment by GrahamTheCoder** [comment]
Good spot. Doesn't seem obviously related to throw expressions so I've opened another bug for it here:
https://github.com/icsharpcode/CodeConverter/issues/76

Remember expressions can be nested arbitrarily deep (AFAIK). e.g.
`Text = text != "1" ? text != "2" ? throw new ArgumentNullException(nameof(text)) : "2" : throw new NotSupportedException("1 isn't supported")`

Obviously this can be handled too, but I'm not convinced the result would be something I'd want to merge given the likely added code complexity. Of course you're most welcome to continue investigating if you're interested, or to convince me it's a good direction to go, I just don't want you to spend lots of effort on something and be surprised at the end. I'm much more interested in focusing effort on areas that currently don't convert at all, or convert incorrectly, such as #76.

**Comment by RussellSmith2** [comment]
"_" not a valid parameter name was just 1 issue found after converting ConvertQueryBodyClause method in CSharp\NodesVisitor.cs to VB.

The CSharpImpl.__Throw(Of System.Func`2 code is the throwing the following error.
Argument not specified for parameter 'e' of ' Public Shared Function __Throw(Of System.Func)(e As Exception) As System.Func'

All but the first parameter that is preceded by AddressOf is also throwing an error.  It appears it is an overload resolution error.  The correct VB code I listed yesterday does not throw any errors.

**Comment by GrahamTheCoder** [comment]
OK, thanks for letting me know. I will properly investigate the other issues with that particular bit of code being converted when I have time this weekend and either fix them or raise separate issues for them.
