### ISSUE TITLE
VB -> C#: Control names are renamed (name ==> _name only in specific forms)

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#615]
Hello,

Sometimes the controls names are renamed into private and public properties of the name are created.
The problem is when you use the GUI to create columns in a datagridview (there is an error column doesn't exist).

### Input code
```vbnet
// In the InitializeComponent
dim trvUse as TreeView 
```

### Erroneous output
```C#
private TreeView _trvUse;
```

### Expected output
```C#
private TreeView trvUse;
```
The name of the control shouldn't change

### Details
* Product in use: e.g. .NET extension
* Version in use: 8.1.7 (last at the moment
* Did you see it working in a previous version, which? No 
In some forms the controls are renamed (a "_" in added in front of the controls.)
It is not a big problem but if I have a datagridview where the columns are added in the GUI (I add a column Txt for example), the column, is also renamed in _Txt.
After that when I access the cell value (dgvTest.Rows(10).cells ("Txt").Value) there is a crash as the column is now named _Txt

I am sorry because I can't make a repro (I don't understand why in a smaller project I don't have the error.)
I am still trying to do something. I will update in case I manage to make a repro.

**Comment by GrahamTheCoder** [comment]
The renaming of the field is done when there is a method which "handles" it.
The converter should be adding code to the constructor to set the Name property back to the name without an underscore though, so an exception shouldn't have happened.
I did change this behaviour recently so it's very possible there's a case where the name fixups don't happen

**Comment by marcal** [comment]
Hello,

OK. In the converted code, there seems to be some names that don't have the _ (4 or 5) so perhaps there is something that stopped the process to remove the _.

Marc

**Comment by GrahamTheCoder** [comment]
I have failed in my attempt to reproduce this. See https://github.com/icsharpcode/CodeConverter/commit/dae47c32dc1df15218afcf078c346b01a3a76c19#r42097263

Let me know if you have any other information, or if you've seen it since #618 was fixed, thanks!

**Comment by marcal** [comment]
Hello,

The problem is still there but it is  less important. Now the DataGridViewTextBoxColumn are not renamed anymore (so there is no crash in runtime too). Some controls are still renamed but it doesn't matter.
What is strange is that taking the code of the form designer only makes no problem.

**Comment by marcal** [comment]
Hello,
I have managed to make a repro. 
[Repro.zip](https://github.com/icsharpcode/CodeConverter/files/5186462/Repro.zip).
Unfortunately, it is big. If I remove the code from the form, the problem disappears so I have to let it.
You will see a lof of objects being renamed (cboLng becomes _cboLng)...

**Comment by GrahamTheCoder** [comment]
Thanks for that. I think I've managed to get a small repro. I'll leave it here to remind me when I have some time to dig into what's happening.

```vbnet
Class AForm
    Private WithEvents cboLng As DataGridViewTextBoxColumn

    Public Sub SomeMethod() Handles cboLng.Dispose
    End Sub
End Class
```

Expected (should have Name property set):
```csharp
using System.Runtime.CompilerServices;

internal partial class AForm
{
    private DataGridViewTextBoxColumn _cboLng;

    AForm()
    {
        _cboLng.Name = "cboLng";
    }

    private DataGridViewTextBoxColumn cboLng
    {
        [MethodImpl(MethodImplOptions.Synchronized)]
        get
        {
            return _cboLng;
        }

        [MethodImpl(MethodImplOptions.Synchronized)]
        set
        {
            if (_cboLng != null)
            {
                _cboLng.Dispose -= SomeMethod;
            }

            _cboLng = value;
            if (_cboLng != null)
            {
                _cboLng.Dispose += SomeMethod;
            }
        }
    }

    public void SomeMethod()
    {
    }
}
```

Actual (constructor not even created):
```csharp
using System.Runtime.CompilerServices;

internal partial class AForm
{
    private DataGridViewTextBoxColumn _cboLng;

    AForm()
    {
        _cboLng.Name = "cboLng";
    }

    private DataGridViewTextBoxColumn cboLng
    {
        [MethodImpl(MethodImplOptions.Synchronized)]
        get
        {
            return _cboLng;
        }

        [MethodImpl(MethodImplOptions.Synchronized)]
        set
        {
            if (_cboLng != null)
            {
                _cboLng.Dispose -= SomeMethod;
            }

            _cboLng = value;
            if (_cboLng != null)
            {
                _cboLng.Dispose += SomeMethod;
            }
        }
    }

    public void SomeMethod()
    {
    }
}
```

**Comment by GrahamTheCoder** [comment]
Ah, turns out my repro was wrong. Here's my new understanding:
* The "Name" of a Component is string.Empty until it's set somewhere.
* When the converter converts InitializeComponent, it sets the name to the one with an underscore: This is necessary for the visual designer to correctly associate with handling methods.
* Therefore, only Components with their name set in InitializeComponent should have their name overwritten in the constructor (in a non-generated file wherever possible)

**Comment by docfresh** [comment]
This happened on my project in VB -> C# on CC 8.40 and I'm not sure how to clean up the mess.  Renaming the components in the designer brings up a slew of "ambiguous reference error" and now I'm stuck with different naming conventions for controls prior to conversion, and after.  There's a mix of those with and without the _ prefix.

![image](https://user-images.githubusercontent.com/8064022/145934002-cb9581e1-9bbb-409a-b76c-0fc4d1782a28.png)

**Comment by docfresh** [comment]
Here is a solution that seems to work.

1. Go into designer.cs and delete the 'internal' stuff under the private declaration

private TextBox _txtWeeklyReportsEmails;

        internal TextBox txtWeeklyReportsEmails
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtWeeklyReportsEmails;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtWeeklyReportsEmails != null)
                {
                    _txtWeeklyReportsEmails.TextChanged -= settingsChangedEvent;
                }

                _txtWeeklyReportsEmails = value;
                if (_txtWeeklyReportsEmails != null)
                {
                    _txtWeeklyReportsEmails.TextChanged += settingsChangedEvent;
                }
            }
        }
		
		
THEN you can rename the component on the designer to remove the leading underscore _.
		
If you rename in the designer first, you get messy errors.

**Comment by GrahamTheCoder** [comment]
The converter needs to add those properties since that's what VB does behind the scenes. It tries to only add them if they are needed to assign events - in order to reduce the amount of noise on the output. If you delete the internal property (and rename the field) you'll find that anywhere that assigns the field no longer reattaches the events.

If it wasn't being assigned to (except in initialize component) , let me know - I can't remember if the converter already checks that too. The converter could in future avoid generating the property in such cases.

You're right the names are inconsistent in one sense, but the consistent thing is that you should always use the non-underscore version in your code (whether it's a field or property).
This is a useful kind of consistency and the best that's possible given the constraints.

Obviously if you dislike underscores as a personal preference, then you can rename the ones prefixed with an underscore to literally anything that's valid... I. E. Not the name of something else that already exists.

**Comment by GrahamTheCoder** [comment]
If the WithEvents field is *only* assigned in InitializeComponent, or you were manually adding any event handlers there may be no issue

I started spiking a fix for this yesterday. It's quite a tricky set of constraints but I'm reasonably confident in the solution. I'll try to complete it next week but can't promise anything.

**Comment by GrahamTheCoder** [comment]
Disregard my above comment about spiking. I got mixed up, it was meant in regard to issue #774 (which is the bug that would happen everywhere if not for the existing property/field pair generation).

**Comment by GrahamTheCoder** [comment]
I have made some changes as part of #774 which should decrease the number of cases in which future conversions create the delegating property
In particular, if there is no write-usage of the property (except InitializeComponent) and no inheriting class, then it should no longer create the property - it should use the field directly. I hope that helps with your particular case!

**Comment by docfresh** [comment]
Thanks @GrahamTheCoder . I am sure it will be helpful.  However I have already made many modifications to the converted project and can't go back to the original VB source.  It looks like I will need to find a way to rename all the form controls by hand. Yet, I think others will appreciate it!

**Comment by GrahamTheCoder** [comment]
If you have a git commit from immediately after the initial conversion (before manual changes), it's possible you can start a new branch there, redo the conversion on top of that with a new version, then merge it with the branch containing manual changes. Depends a lot on what git history you have and how the changes overlap - just mentioning since it worked for me in a similar situation

**Comment by grochoge** [comment]
@GrahamTheCoder I'm running into issues with _ being prepended to the fields in a WinForms control. This is changing the automation ID of everything which causes the references in our automated UI tests to no longer be valid.

I tried installing CI build #290 but it's still renaming fields and generating properties even though nothing is setting the property (only InitializeComponents setting the underlying field). It does have events; does that force property generation?
