### ISSUE TITLE
VB -> C#: Public objects in the GUI become private after conversion

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#618]
Hello,
I have made a test with a public object.
The object is used with the instace variable (for example the Form  
FormTest is used (in the code)
imgexplorer is defined as public in the designer.

FormTest.imgexplorer

I have a form that has an ImageList. The object is public (every window of my project references the ImgForm.ImageList.

After the conversion it becomes private
```vbnet
Public imgExplorer as ImageList 
```

### Erroneous output
```C#
private ImageList imgExplorer;
```

### Expected output
```C#
public ImageList imgExplorer;
```

### Details
* .NET extension 8.1.7
* It worked one moth ago

**Comment by GrahamTheCoder** [comment]
Probably related to #616 
3 people have mentioned it now and it's a regression so I'm going to look at this as a priority

**Comment by GrahamTheCoder** [comment]
There's now a fix in master which I'll hopefully release soon. If anyone could retest on the latest source, or CI build that'd be much appreciated. Thanks!

**Comment by marcal** [comment]
Hello,

I launch a test before leaving. I report when it is over and I am back (in 3-4 hours I think)

**Comment by marcal** [comment]
Hello,

The problem is solved 
Thank you

**Comment by GrahamTheCoder** [comment]
Thanks for testing, it'll be released soon

**Comment by marcal** [comment]
Thank you
