### ISSUE TITLE
VB -> C#: missing type declaration in c# for vb implicitly-typed array

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#632]
### Input code
```vbnet
WithList({Sub() Debug.Print("a"), Sub() Debug.Print("b")})
Private Shared Sub WithList(actions As List(Of Action))
        Debug.Print(actions.Count.ToString)
End Sub
```

### Erroneous output
```c#
WithList(new[] { () => Debug.Print("a"), () => Debug.Print("b") }); 
--> No best type found for implicitly-typed array
```
### Expected output
```C#
WithList(new List<Action>() { () => Debug.Print("a"), () => Debug.Print("b") });
```
### Details
* Product in use: VS extension 
* Version in use: 8.1.8.0
* Did you see it working in a previous version, which? no

**Comment by GrahamTheCoder** [comment]
Thanks for this. There's already some code for inferring delegate types on the converter. Hopefully it'll be a good start for solving this. We'll need to check the VB behaviour though, often it just infers object for cases like these.

**Comment by GrahamTheCoder** [comment]
I've confirmed with an [example here](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUGlnkWRdQHQDCmwwlAxrgCWmAHb52AcUqjK2If3qMcBEuSqp2AESEBDAOajMFBfnr0ACgFcIwBYU7Bd+Ip3N1CnwhflhdVEgALXWxKGBIbQgANAAoASnovJMIAdSFcQIAZIQoYgG9iG3jCLUoIK312HyFRXBiAIl16uKgIiGLS8srq2oaIZoBfBI8vAFFRcMKIdyTqvwDiYNDJyLSM7NzdQRFxQgBBIj3tsXjh5M9Oiqr5Xq3hMQlMmX0M9gAVTGJcG/0zsYm2vRxuFHM58EA) that "Action" can be inferred in this case

Note: It chooses whatever the target type is, so no clever lambda analysis is needed here
