### ISSUE TITLE
VB -> C#: Converted With block does not update original struct element or property

### ISSUE THREAD

**Issue by eveltman-twinfield** [icsharpcode/CodeConverter#634]
### Input code
```vbnet
Public Structure SomeStruct
    Public FieldA As String
End Structure

Module Module1
   Sub Main()
      Dim myArray(0) As SomeStruct

      With myArray(0)
         .FieldA = "New FieldA value"
      End With

      'Outputs: FieldA was changed to New FieldA value 
      Console.WriteLine($"FieldA was changed to {myArray(0).FieldA}")
      Console.ReadLine
   End Sub
End Module
```

### Erroneous output
```C#
public partial struct SomeStruct
{
    public string FieldA;
}

internal static partial class Module1
{
    public static void Main()
    {
        var myArray = new SomeStruct[1];
        {
            var withBlock = myArray[0];
            withBlock.FieldA = "New FieldA value";
        }

        // Outputs: FieldA was changed to
        Console.WriteLine($"FieldA was changed to {myArray[0].FieldA}");
        Console.ReadLine();
    }
}
```

### Expected output
Not sure what the best solution is here. 
I was about to suggest copying the withBlock variable back to the original element at the end.
But if the structure has methods that are called somewhere halfway the With block, then that method would be operating on a copy of the structure so the converted code would still behave differently from the original.

Alternatively, the With block could be converted to a local method, with the original element passed by reference, but I was struggling to get the syntax right for that. Maybe I was trying something that C# doesn't support (or I just was too much in a hurry).

### Details
* Simple object expressions work fine, because in those cases the converter does not introduce a withBlock variable, and assignments within the block keep operating directly on the 'subject' of the original With block.
* The issue is also occurring for structs that are members of a class (With someObject.SomeStructure).
* I didn't try with other value types but maybe the same issue occurs there too.
* Issue first found in the VS extension, and reproduced with [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net).
* Version in use: 8.1.8.0.

**Comment by GrahamTheCoder** [comment]
Thanks for this. Mutating structs is a subtle area!
I'm a bit busy at the moment so it might be a while before I have space to dig into this one. I'm sure there must be a way though ☺

**Comment by GrahamTheCoder** [comment]
See #716 for more example cases
