### ISSUE TITLE
VB -> C#: Late bound implicit conversion creates compile error

### ISSUE THREAD

**Issue by VetrivelDevOps** [icsharpcode/CodeConverter#636]
### Input code
```vbnet
txtTotal.Text = Math.Round(sqlDT.Rows(0)("Expr1"), 2)
```

### Erroneous output
```C#
txtTotal.Text = Conversions.ToString(Math.Round(sqlDT.Rows[0]["Expr1"], (object)2));

the stack trace.
Error	CS1503	Argument 1: cannot convert from 'object' to 'double'
```

### Expected output
```C#
txtTotal.Text = Conversions.ToString(Math.Round(double.Parse(sqlDT.Rows[0]["Expr1"].ToString()), 2));

In C#, Math.Round function expecting 'double' datatype.

```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks, I think that's enough information to fix the issue. Hopefully I'll have some time to look at this in the next few weeks

**Comment by GrahamTheCoder** [comment]
Ah, now I've looked closer, I see that the difficulty with this case is that there are multiple overloads (e.g. decimal or double) available, and it can't be known until runtime which will be used.
You can see the full details of what the VB compiler emits in [this decompilation](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUPQAoCuEwAlgMaEDCwAhviIA1dvmb9gAIUFc+g/PULLCLNlxKtCADQAUASiUqAIu1SFMhQYQDyEAFaVOuQgF5CAZgB0ABgBmRiomZoQAHm6EALL8uAAWXgBKmMwAdjC6llCEAEyGdEEAommaEPRFMLwCQkA==)...it's not pretty.
It's possible to make the code converter to generate code like that...but I'm not convinced that's a particularly good solution to the issue. This will need more thought so is unlikely to be fixed very soon (if at all!) I'm sad to say

**Comment by GrahamTheCoder** [comment]
Closing as known limitation

**Comment by GrahamTheCoder** [comment]
Related to #782, #783, #786. Since the original report, I've realized that some cases may be solveable by careful use of `dynamic` in the output in the place of `object`
