### ISSUE TITLE
VB -> C#: NameOf Interface property

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#640]
### Input code
```vbnet
Public Shared Property AttributeTypeForeignKeyName As String = NameOf(IOhmniAttributeType.AttributeTypeId)
```

### Erroneous output
```C#
        class _failedMemberConversionMarker1
        {
        }
```

### Expected output
```C#
public static string AttributeTypeForeignKeyName { get; set; } = nameof( IOhmniAttributeType.AttributeTypeId );
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension 
* Version in use: 8.1.8
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment]
Thanks for posting, I'm afraid I can't reproduce any of your issues on https://codeconverter.icsharpcode.net/
Can you provide more info on which version of which converter you're using?

**Comment by GrahamTheCoder** [comment]
Consolidating
