### ISSUE TITLE
VB -> C#: XML output path needs output path prepending

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#641]
### Input code
```vbnet
    <OutputPath>bin\Debug\</OutputPath>
    <DocumentationFile>isr.Dapper.Ohmni.xml</DocumentationFile>
```

### Erroneous output
```C#
    <OutputPath>bin\Debug\</OutputPath>
    <DocumentationFile>isr.Dapper.Ohmni.xml</DocumentationFile>
```

### Expected output
```C#
    <OutputPath>bin\Debug\</OutputPath>
    <DocumentationFile>bin\Debug\isr.Dapper.Ohmni.xml</DocumentationFile>
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension
* Version in use: 8.1.8
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment]
Thanks, this should be an easy fix

**Comment by BrianFreemanAtlanta** [comment]
I took a look at this. I think that instead of language agnostic it may need to be multifile characterization. For VB-C# need to prepend the path. On C# -> VB need to remove the path. This looks to be a transform to the project file to add to PostTransformProjectFile for each language.
