### ISSUE TITLE
VB -> C#: Microsoft.VisualBasic.vbTab

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#651]
### Input code
```vbnet
Microsoft.VisualBasic.vbTab
```

### Erroneous output
```C#
Microsoft.VisualBasic.csTab
```

### Expected output
```C#
Microsoft.VisualBasic.vbTab
```

### Details
* Product in use:  [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension 
* Version in use: 8.1.8.0
* Visual Studion Community 2019 16.7.5
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment]
Is that within the project file by any chance? The regex is probably needs a quote or pointy bracket adding so it only replaces it at the end

**Comment by AteCoder** [comment]
That was in the code.

**Comment by GrahamTheCoder** [comment]
Hi, I've just tried unsuccessfully to repro using
```vbnet
Public Class VisualBasicClass
    Dim z = Microsoft.VisualBasic.vbTab
End Class
```

Are you able to provide any more details on the context where this failed?

**Comment by AteCoder** [comment]
[vbTabIssue.zip](https://github.com/icsharpcode/CodeConverter/files/5362165/vbTabIssue.zip)

I attached three files. Not sure if this occurred on all of them

**Comment by AteCoder** [comment]
...sorry, i did not mean to close this

**Comment by GrahamTheCoder** [comment]
The issue doesn't happen when I convert those (possibly due to other context not present), can you confirm whether it happens for you on a file just containing this:
```vbnet
Public Class Issue651
    Public Sub New(ByVal filePathName As String)
        Dim z = New String() {",", Microsoft.VisualBasic.vbTab}
    End Sub
End Class
```

**Comment by AteCoder** [comment]
Looks like this works:

VB Code
`    Public Sub New(ByVal filePathName As String)
        Dim z As String() = New String() {",", Microsoft.VisualBasic.vbTab}
    End Sub
`
C#
`
using Microsoft.VisualBasic;

namespace isr.VI.Device.Facade
{
    public class Issue651
    {
        public Issue651(string filePathName)
        {
            object z = new string[] { ",", Constants.vbTab };
        }
    }
}
`
VB Code:
`
Public Class Issue651
    Public Sub New(ByVal filePathName As String)
        Dim z As String() = New String() {",", Microsoft.VisualBasic.vbTab}
    End Sub
End Class
`

C#
`
using Microsoft.VisualBasic;

namespace isr.VI.Device.Facade
{
    public class Issue651
    {
        public Issue651(string filePathName)
        {
            var z = new string[] { ",", Constants.vbTab };
        }
    }
}
`

**Comment by GrahamTheCoder** [comment]
OK, so let's try building up a bit more context, but still keeping it isolated from most of the project. So for example, does this convert correctly for you (in terms of vbTab):
```vbnet
Imports System
''' <summary> This is the reader class of the delimited file class library. </summary>
''' <remarks>
''' (c) 2004 Integrated Scientific Resources, Inc. All rights reserved. <para>
''' Licensed under The MIT License. </para><para>  
''' David, 03/04/04, 1.0.1524.x. </para>
''' </remarks>
Public Class DelimitedReaderTest
    Inherits DelimitedFileTestBase

#Region " CONSTRUCTION and CLEANUP "

    ''' <summary> Constructs this class. </summary>
    ''' <remarks> David, 10/8/2020. </remarks>
    Public Sub New()
        MyBase.New()
        Me.Delimiter = DefaultDelimiter
    End Sub

#End Region

#Region " DELIMITED "

    ''' <summary> Gets or sets the tab delimited. </summary>
    ''' <value> The tab delimited. </value>
    Public Property TabDelimited As Boolean
        Get
            Return String.Equals(Me.Delimiter, Microsoft.VisualBasic.vbTab)
        End Get
        Set(value As Boolean)
            Me.Delimiter = If(value, Convert.ToChar(Microsoft.VisualBasic.vbTab), DefaultDelimiter)
        End Set
    End Property

    ''' <summary> The default delimiter. </summary>
    Public Const DefaultDelimiter As Char = ","c

    ''' <summary> Gets or sets the delimiter. </summary>
    ''' <value> The delimiter. </value>
    Public Property Delimiter As Char

#End Region
End Class

Public Class DelimitedFileTestBase
End Class
```

If that does work, could you try cutting out bits of your files that do cause the issue or adding to this  version until there's a version which causes the issue, but compiles without the whole project present, you can use [this editor](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUAOROEA8+ArqqgIbakB8hACoALAJZEJhXCMqFslbjErZCAY2Dd8RTADNpswsuBjUYqjEK6xwORq1ETEbL1IA6VgHoOXV/3pMDKwKPNgA1vj+jMwAFGoAlIQATAAMKQAshMgAdlQA5i4WJGpilLli1mqEAEqU+Jjs2Gp1UFnZah4AgsDA8mJ5IgTydSpglDAeLOi83FGBhAAyYs3Z+OOE7NnKqqJyALLIQovLZWuTntMu/FMzgoQBzAAi3GBiMK0pAMyeGT/prQBGNwpNwAgCsSXSbgAHudLrMHkEWJ4QrwIlEAArsCAmKoAYU02kIj0oJjMFlqShUQjquHohAZbVk2HMRBJZPM4wAYjZKDSKAAhLSUej0ADEtTyYkw2UIACJCHiAPIAOWIQmqAFU8UJkKrCNwtoqFgBRToqzUY+WiuiMwjzNicUICRUyijYdhqIYyKT2bTnHzOqJ2h2o8KRYkvN6AlKeAAcnlSqXOYfR9MZWJxyxI2MIKsoAHcYvF03aGXtSEKzvmiyXbWXy5Q3OzTJzVABeYmUXTcdjAXAt8kqUuEE1G4jYm1iseWSXS7JTucy+XEk0LZAHIQmx7Wugjh2BvyEADilCGOEIa29hlw3AgRlJrYsAadfn3zBYYG4wHYlEEu2kO8Hw5Z8vC/H8/xHTNcUIDFsEwdAVFwUhhDvQdOUsToiAFTBMFsQ0RztU86XrBs7VqXBGllYhcBZbI8jcE0AEd2G/fAYj2Jt0KobBWj2ZZ4PqXRcDcAA1CRWOAKtljcSAhDvOsyNHI1iMIxliDPGJwN/QgsMIHC8MUbJFKUxlOObR8hw7LJdC079f1aPEZTGPA3CETA8REXgOIEzAhJE8SOG/aSOjkhTWhJHs+wHSy2xMhsZxIM8R0SuCEKQ0gbRDD9Dz4f9DGUKL+2Ap8VBfXw8qg7EYKc1ZcC7IqYpAlRdKITzeEITs5SgOU1CyxkD1fPKTzPHRVCvIgZDkYxSuwcqg3fJFtL/YQCtinjzmW4MM2q7M0sQvAUO4lq9Pa7Ap0SpcFzoRKCQcG1oOzO6iWOmAeVsflcCrEUbqNZ78HoIA=) if it helps.

**Comment by AteCoder** [comment]
I went back to the original solution and converted the three files. They all converted w/o an error.

**Comment by GrahamTheCoder** [comment]
OK, I'll close this for now - please reopen if you see it again

**Comment by AteCoder** [comment]
Will do.  After the conversion I cleanup the code document and comments on the directives (e.g., #Region) so the files that I tested are no longer exactly the same and so is the project.   Next time I will clean the VB files only after all fixes are in place so as to be able to reproduce such issues.
