### ISSUE TITLE
VB -> C#: Strings.Instr case insensitive

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#655]
Hello,
I have seen another problem (linked to the #579 ), Strings.Instr has the same problem.

### Input code
```vbnet
si_Pos = Strings.InStr(1, astr_Error, "object '")
```

### Erroneous output
```C#
si_Pos = Strings.InStr(1, astr_Error, "object '");
```

### Expected output
```C#
si_Pos = Strings.InStr(1, astr_Error, "object '", Constants.vbTextCompare);
```

### Details
* Product in use: https://codeconverter.icsharpcode.net (extension .NET too).
When the project is in TextCompare, instr must compare texts as texts so Constants.vbTextCompare is mandatory to have the same result.

Thank you
Marc

**Comment by GrahamTheCoder** [comment]
Thanks, this should be easy enough to fix. I wonder if there's a place in docs/compiler that lists all these related cases

**Comment by marcal** [comment]
Hello,

Thank you
I don't think there is such a list but here are some I know of 

https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/option-compare-statement
InStr
InStrRev
Replace
Split
StrComp
>
<
=
<>

Doing a shift+F2 on such a function (strings.Instr) opens the metadata that gives the following for strings
Filter (so it seems OK)
Instr, InstrRev, Replace , Split, strComp, 
I think it is all for de Visualbasic dll

There are also other things in a declared string (instead of strings). This one doesn't use 
string Toto; (for the StringComparison Enum)
Toto.IndexOf and shift+F2 gives
Compare (some of them)
EndsWith
Equals
IndexOf(
LastIndexOf
Split
StartsWith

I think it is all (at least that I know about).

Marc
