### ISSUE TITLE
VB -> C#: Async Function doesn't translate to async lambda

### ISSUE THREAD

**Issue by brantburnett** [icsharpcode/CodeConverter#657]
### Input code
```vbnet
Return Await Me.ExecuteAuthenticatedAsync(Async Function()
    Return Await DoSomethingAsync()
End Function)
```

### Erroneous output
```C#
return await this.ExecuteAuthenticatedAsync(() => {
    return await DoSomethingAsync();
});
```

### Expected output
```C#
return await this.ExecuteAuthenticatedAsync(async () => {
    return await DoSomethingAsync();
});

```

### Details
* Product in use: VS extension
* Version in use: 8.1.8.0

**Comment by GrahamTheCoder** [comment]
Thanks for posting. The code around lambdas has a lot of cases, some are likely missing code like this https://github.com/icsharpcode/CodeConverter/blob/a5473fbf194d70daa6b47a5267c22337a6eef2e7/CodeConverter/CSharp/LambdaConverter.cs#L111
So probably a few test cases needed but should be a straightforward change.
