### ISSUE TITLE
CS1587 Comment at start of file is not placed on a valid language element

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#663]
### Input code
```vbnet
''' <summary> Form for viewing the my. </summary>
''' <remarks> David, 10/1/2020. </remarks>
Public Class MyForm
    Inherits isr.Automata.Finite.Forms.BimanualToggleForm
End Class
```

### Erroneous output
```C#
/// <summary> Form for viewing the my. </summary>
/// <remarks> David, 10/1/2020. </remarks>

namespace isr.Finite.Automata.Engines
{
    public class MyForm : isr.Automata.Finite.Forms.BimanualToggleForm
    {
    }
}
```

### Expected output
```C#
namespace isr.Finite.Automata.Engines
{
    /// <summary> Form for viewing the my. </summary>
    /// <remarks> David, 10/1/2020. </remarks>
    public class MyForm : isr.Automata.Finite.Forms.BimanualToggleForm
    {
    }
}
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) VS extension 
* Version in use: 8.1.8.0 CI artifact 10/12/20202
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment]
The comment conversion works by using anchor points. e.g. The comment comes after the start of the file, and before the identifier "MySplashScreen".
All of the new lines generated for namespace/usings are in between converted version of the two anchors. At the moment, it picks the highest up line possible. Here's an example of a case where that would make sense, just by changing the contents of the comment:

### Input code
```vbnet
''' This file is copyright notice must be preserved at the top of all files
Public Class MyForm
    Inherits isr.Automata.Finite.Forms.BimanualToggleForm
End Class
```

### Current output
```C#
// This copyright notice must be preserved at the top of all files

namespace isr.Finite.Automata.Engines
{
    public class MyForm : isr.Automata.Finite.Forms.BimanualToggleForm
    {
    }
}
```

### Output if I flip the heuristic
```C#
namespace isr.Finite.Automata.Engines
{
    // This copyright notice must be preserved at the top of all files
    public class MyForm : isr.Automata.Finite.Forms.BimanualToggleForm
    {
    }
}
```

Two resolutions that come to mind to solve at least these two cases:
1. Flip the behaviour just for documentation comments
2. Flip the behaviour everywhere except for comments at the start of a file which aren't doc comments

I'll probably try the second one and see how many tests it breaks, then retreat and have a rethink.

You could imagine going arbitrarily far adding heuristics for which line is relevant. e.g. When people have used `^` `\/` and `/\` to indicate which line they're referring to, or if there's a blank line before/after the comment, but it's a slippery slope leading to neural nets trained from the movement of comments in the history of all open source repositories, and I'm going to steer well clear of that as fun as it sounds 😄

**Comment by AteCoder** [comment]
Regular comments (i.e., starting with a  " ' ") are not expected to raise a warning.  It is code comments starting with ''' <summary> that raise the warnings.  

in other words converting this:
`
''' This file is copyright notice must be preserved at the top of all files
Public Class MyForm
    Inherits isr.Automata.Finite.Forms.BimanualToggleForm
End Class
`

to this: 

`// This file is copyright notice must be preserved at the top of all files
namespace isr.Finite.Automata.Engines
{
    public class MyForm : isr.Automata.Finite.Forms.BimanualToggleForm
    {
    }
}
`

is correct. 

Converting this:
`
''' <summary> This file is copyright notice must be preserved at the top of all files </summary>
Public Class MyForm
    Inherits isr.Automata.Finite.Forms.BimanualToggleForm
End Class
`

to this: 

`/// <summary> This file is copyright notice must be preserved at the top of all files </summary>
namespace isr.Finite.Automata.Engines
{
    public class MyForm : isr.Automata.Finite.Forms.BimanualToggleForm
    {
    }
}
`

will raise the warning.

**Comment by GrahamTheCoder** [comment]
👍  Ah yes sorry that's what I meant by "doc comments" - I've now amended it to say "XML doc comments"
