### ISSUE TITLE
VB namespace global.xxx => C# namespace xxx (global not supported)

### ISSUE THREAD

**Issue by BaronBodissey** [icsharpcode/CodeConverter#67]
[Fact]
        public void TestGlobalNamespace()
        {
            TestConversionVisualBasicToCSharp(@"Namespace Global.Test
End Namespace", @"using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualBasic;

 namespace Test
 {
 }");

**Comment by BaronBodissey** [comment]
I had the fact directly in here as you removed it from the code...I don't understand why!

**Comment by GrahamTheCoder** [comment]
Apologies! It seemed unrelated to the widening/narrowing and I thought it was some unfinished work you'd accidentally added! I'll take a look soon and add it back. While I have your attention, could you add information to #46 please?

**Comment by BaronBodissey** [comment]
Ok.
Also, I do have an issue with a fact already written but deactivated:
[Fact(Skip = "Not implemented!")]
public void TestIndexer()

Should I open another issue specifically for the indexer/default property?

**Comment by GrahamTheCoder** [comment]
Yes please for the indexer - I've pulled the default property out of "known limitations" and into issue https://github.com/icsharpcode/CodeConverter/issues/68
