### ISSUE TITLE
VB -> C#: events convert error

### ISSUE THREAD

**Issue by GladCypress3030** [icsharpcode/CodeConverter#671]
### Input code
```vbnet
Public Shared Event TestEvent(a As String)
```

### Erroneous output
```C#
public static event TestEventEventHandler TestEvent;
public static delegate TestEventEventHandler(string a);
```

### Expected output
```C#
public static event TestEventEventHandler TestEvent;
public delegate TestEventEventHandler(string a);
```

### Details
* Product in use: VS Extension
* Version in use: 8.2.0.0
* Did you see it working in a previous version, which? No.
* Because in C# not allowed making delegates "static" converting shared events from VB cause complile errors

**Comment by GrahamTheCoder** [comment]
Ah yes, good spot. Delegates should never have the static modifier added, should be quite an easy fix. There's probably a method like VisitEvent which ultimately passes all of the converted event modifiers through to create this delegate, and just needs static filtering out.

**Comment by GrahamTheCoder** [comment]
Here's the line where I think we'd need to filter to modifiers that aren't `IsKind(SyntaxKind.StaticKeyword)`:
https://github.com/icsharpcode/CodeConverter/blob/8ade6b18f60d7f83f6824e9adc6ec9621f0c4274/CodeConverter/CSharp/DeclarationNodeVisitor.cs#L1232
