### ISSUE TITLE
VB -> C#: error converting VB xml syntax

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#679]
### Input code
```vbnet
Const name = "name"
Dim xElement = <Module Name=<%= name %> LicenseCount=<%= 100 %>></Module>
```

### Erroneous output
```C#
const string name = "name";
var xElement = XElement.Parse("<Module Name=<%= name %> LicenseCount=<%= 100 %>></Module>");
```

### Expected output
```C#
const string name = "name";
var xElement = XElement.Parse("<Module Name=\"" + name + "\" LicenseCount=\"" + 100 +  "\"></Module>");
```

### Details
* Product in use: VS extension
* Version in use: 8.2.1.0
* Did you see it working in a previous version, which? no

**Comment by GrahamTheCoder** [comment]
Thanks for raising this. I'll consolidate it with https://github.com/icsharpcode/CodeConverter/issues/253 since it has a bit more discussion already.
