### ISSUE TITLE
VB -> C#: Default properties not implemented

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#68]
[Default properties](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/how-to-declare-and-call-a-default-property) could be implemented with [implicit casts](https://social.msdn.microsoft.com/Forums/en-US/de03e1ff-8e96-4be0-8eed-656e83bb7495/how-to-create-default-property-for-class-?forum=Vsexpressvcs)

There's also a special case of default properties which is used for indexers

**Comment by siegfriedpammer** [comment]
If this is implemented, a warning should be added via `#warning`, otherwise this might lead to surprises. Implicit conversions that do obscure things are dangerous.

**Comment by GrahamTheCoder** [comment]
Are they any more dangerous than the default property? If they end up being totally equivalent I'd be slightly reluctant to get opinionated about the code being converted. If they're worse in any scenario then I'd agree.

**Comment by siegfriedpammer** [comment]
Some of VB's features are dangerous and have not been added to C# for a reason, I think.

When you convert code from VB to C#, you usually do this to migrate it and get access to the safety features of C#. Therefore I think, a warning like this would be appropriate.  But that's just my opinion. I would expect a converter to point out parts of the code that need to be refactored to fit into the concepts of the target language.
