### ISSUE TITLE
VB -> C#: CS1009 Unrecognized escape sequence

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#684]
### Input code
```vbnet
$"Soak: {sender.SoakStopwatch.Elapsed:d\.h\:mm\:ss\.f}"
```

### Erroneous output
```C#
$"Soak: {sender.SoakStopwatch.Elapsed:d\.h\:mm\:ss\.f}";
```

### Expected output
```C#
$"Soak: {sender.SoakStopwatch.Elapsed:d\\.h\\:mm\\:ss\\.f}";
```

### Details
* Product in use: VS extension 
* Version in use: 8.2.1.0
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment]
There's already some logic to escape normal strings, I expect the same logic can probably be applied to format strings too
