### ISSUE TITLE
VB -> C#: Unspecific error casting EmptyStatementSyntax

### ISSUE THREAD

**Issue by BobFrankston** [icsharpcode/CodeConverter#686]
### Input code
```vbnet

I can't because the message doesn't give me a hint as to where to look
```

### Details
Version 8.2.1.0 (automatic update)

    System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.EmptyStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax'.
       at ICSharpCode.CodeConverter.CSharp.VisualBasicConverter.<ConvertCompilationTreeAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ICSharpCode.CodeConverter.CSharp.VBToCSProjectContentsConverter.<SingleFirstPassAsync>d__22.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at ICSharpCode.CodeConverter.Shared.ProjectConversion.<FirstPassAsync>d__26.MoveNext()
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both

I tried to remove all the VB HTML syntax but may have missed something. Even so, it should give me a hint as to where to look

**Comment by BobFrankston** [comment]
Finally tracked down another use of embedded HTML -- it now compiles. Still, needs to tell me here to look.

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report. As you probably guessed, this is an error-handling error. If you could post the original code containing the issue now that you've found it, I can hopefully at least make the error more specific.

**Comment by BobFrankston** [comment]
I've since worked around it. But I do suggest that the translations from inline-HTML generate a pragma to force manual inspection since the current translation is highly likely to fail. But it's a good starting point to a fix. What I did for myself was create very simple xe and xe static using functions so I could can write 

```
xe("h1", xa("class", "hello"), "Title")
```

 which is not only simple but it's safer than using parse. Similarly for static declarations a simple inline pragma would be easier to spot and fixed than an error traceback for well-understood limitations.
 
I also had to manually locate the linq translations but I understand that is a challenge.  Here too a standard helper function vbcompare (vbc) would make it far easier to find such case rather than the very complex lines of code that stretch to the edge making it hard to spot.

static class vb2cFixes {
  xa, xe, vbc ..
}

using static ns.vb2cFixes

**Comment by GrahamTheCoder** [comment]
I think I'm missing a bit of context - do you have an example of the original input that causes issues and needs these helper functions?

**Comment by BobFrankston** [comment]
in VB, i can say  dim x = <h1><%= hello %></h1>
you generate (something like) xDocument.Parse("<h1><%= hello %></h1>")
which doesn't work. I can manually correct as I find each instance since it is not flagged.
With my helper routines, I write it as xe("h1", hello) which is actually more readable. If you don't want to implement full parsing (which I understand) you can simply flag such statements.

**Comment by GrahamTheCoder** [comment]
In commit 841b22095f5cdd21aa37a0a4d3632a45edffaf8f and the few preceding, I believe I've covered a lot more cases where exception details were being lost. I'll close this issue for now until someone inevitably reports another example at some point
