### ISSUE TITLE
VB -> C#: wrong conversation of string comparision with Nothing

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#689]
### Input code
```vbnet
Dim str = ""
Assert.That(str = "")                     ' converts to Assert.That(string.IsNullOrEmpty(str))
Assert.That(str = Nothing)          ' converts to Assert.That(str == null);
```

### Erroneous output
```C#
str == null
```

### Expected output
```C#
string.IsNullOrEmpty(str)
```

### Details
* Product in use: VS extension 
* Version in use: 8.2.1
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I believe there are already tests for this sort of thing 
 - must have somehow missed this case
