### ISSUE TITLE
VB -> C#: Exit Do/For/While/Select treated as `break` even when within another breakable block

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#690]
Hello (and best wishes),

I have seen an error where the converted code doesn't give the expected result.

### Input code
```vbnet
Public Class VisualBasicClass
	Public sub Test
		dim LstTmp as new List (of Integer)
		LstTmp.Add (5)
		LstTmp.Add (6)
		LstTmp.Add (7)
		LstTmp.Add (8)
		LstTmp.Add (9)
		LstTmp.Add (10)
		dim i_Total as integer 
		for each CurVal as integer in LstTmp
			i_Total +=CurVal
			Select case CurVal
			Case 6
				Exit For 
			End select 
		Next
		Messagebox.show (i_Total.Tostring())
	End Sub
End Class
```

### Erroneous output
```C#
public void Test()
    {
        var LstTmp = new List<int>();
        LstTmp.Add(5);
        LstTmp.Add(6);
        LstTmp.Add(7);
        LstTmp.Add(8);
        LstTmp.Add(9);
        LstTmp.Add(10);
        var i_Total = default(int);
        foreach (int CurVal in LstTmp)
        {
            i_Total += CurVal;
            switch (CurVal)
            {
                case 6:
                    {
                        break;
                    }
            }
        }

        MessageBox.Show(i_Total.ToString());
    }
```

### Expected output
```C#
public void Test()
    {
        var LstTmp = new List<int>();
        LstTmp.Add(5);
        LstTmp.Add(6);
        LstTmp.Add(7);
        LstTmp.Add(8);
        LstTmp.Add(9);
        LstTmp.Add(10);
        var i_Total = default(int);
        foreach (int CurVal in LstTmp)
        {
           bool bo_ExitFor = false;
            i_Total += CurVal;
            switch (CurVal)
            {
                case 6:
                    {
                    bo_ExitFor = true;
                        break;
                    }
            }
            if (bo_ExitFor) break;
        }

        MessageBox.Show(i_Total.ToString());
    }
```

### Details
* Product in use: VS extension 
* Version in use: e.g. 8.2.1
* It didn't work before
* It is also possible to do a function with a return Value of true  to trigger the Break
It should at least give an error because the code doesn't work like before (VB ==> 11 and C#==>45).
It is also possible to convert to if (.....) but you lose some visibility.

**Comment by GrahamTheCoder** [comment]
Thanks for the report and good suggestion on a fix. There will be a few variants with other nested structures too since VB has more specific exit keywords.
One other solution that is much less idiomatic c#, but probably easier to implement would be adding a label at the end of each structure and use "go to".
Hopefully we can implement as you suggested though.

**Comment by GrahamTheCoder** [comment]
In df6354be975ac8e95e9a8a0bcb08a459919ec5fd I turned this into a compilation error so that it at least can't surprise anyone
