### ISSUE TITLE
VB -> C#: Split string - use correct method

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#691]
### Input code
```vbnet
Dim arrArtikelSplitted() As String
Dim strArtikel As String
arrArtikelSplitted = Split(strArtikel, ".")
```

### Erroneous output
```C#
string[] arrArtikelSplitted;
var strArtikel = default(string);
arrArtikelSplitted = Strings.Split(strArtikel, ".");
```

### Expected output
```C#
string[] arrArtikelSplitted;
string strArtikel;
arrArtikelSplitted = strArtikel.Split(".");
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: latest
* Did you see it working in a previous version, which? Don't know

**Comment by GrahamTheCoder** [comment]
I think this is an example of #174

Referencing Microsoft.VisualBasic library should allow it to compile, but if the methods are the same we can substitute. I would guess they'll behave slightly differently for null, empty string or depending on option text compare.

I'll leave this open for issue specific comments briefly, but consolidate it if nothing stands out about this case.

**Comment by marcal** [comment]
Hello,

Please pay attention that in VB (and c# too)

```
string str_Txt=null;
Strings.Split (    str_Txt,"C");
```

will work (no Exception)
While 
`str_Txt.Split ('C'); `
will raise an exception is str_Txt is null

**Comment by Saibamen** [comment]
Just use `?`:  `str_Txt?.Split ('C');`

**Comment by GrahamTheCoder** [comment]
We'll need to check the output in the null case, is it null, empty array, or something else?

**Comment by marcal** [comment]
Hello,

That is the strangest thing. You have exactly the same result as if your string was empty.
string str_Txt = null;
string[] Toto = Strings.Split(str_Txt, "C");
you have (as a result) ?toto[0] gives  "" (and not null)
Please pay attention to the parameters (CompareMethod Binary or not) that doesn't seem to exist in c# (for Capitals)

**Comment by GrahamTheCoder** [comment]
There are some optional parameters too, so when implementing, I'd suggest only changing the 1 and 2 parameter overloads of
```csharp
public static string[] Split(string Expression, string Delimiter = " ", int Limit = -1, [OptionCompare] CompareMethod Compare = CompareMethod.Binary)
```
I'll consolidate this into #174 since there are hundreds of these which can drown out other issues
