### ISSUE TITLE
Color changed after install? Why?

### ISSUE THREAD

**Issue by jamesatpolaris** [icsharpcode/CodeConverter#697]
### Steps to reproduce
1. Set Visual Studio to Dark Mode
2. Install CodeConverter
3. Open Visual Studio -  parenthesis are now black nearly invisible

![image](https://user-images.githubusercontent.com/63268124/105873297-f2fda200-5fc0-11eb-8fa4-83d2dff12c95.png)

**Comment by GrahamTheCoder** [comment]
That's a very surprising bug!
The extension (in theory) only integrates in menus, so there's no reason at all it should be changing bracket colour. I'll try to reproduce this myself. Do you have any other extensions which modify the editor installed?
It's possible that it's somehow interfering with the loading of another extension. Could you send your full list of extensions (or just disable them all and check if this is still an issue)?

**Comment by GrahamTheCoder** [comment]
VisualStudio.16.Preview/16.9.0-pre.1.0+30709.64
![image](https://user-images.githubusercontent.com/2490482/105984022-77b7f100-6091-11eb-85ce-6692a58c3d54.png)

Note: This screenshot was taken after converting a bit of code - the extension doesn't actually load until after you click one of its menu items (or open the options dialog)

I notice the colours in your dark mode are different in general, you might want to check this setting:
![image](https://user-images.githubusercontent.com/2490482/105984467-104e7100-6092-11eb-9ff8-ad244eafce8d.png)

**Comment by jamesatpolaris** [comment]
My colors matched Dark Theme before the install, after the install all colors changed. Setting the theme back to original theme, closing, reopening and re-setting to Dark theme fixed the issue. Just a very weird issue to have.

**Comment by GrahamTheCoder** [comment]
Yep, very bizarre. I can't see anything the extension does that comes even remotely close to this. I'll close the issue for now, but if someone else sees this please reopen.
