### ISSUE TITLE
VB -> C#: #Region and #End Region are not converted

### ISSUE THREAD

**Issue by Kuan5485** [icsharpcode/CodeConverter#698]
### Input code
```vbnet
#Region "SOMETHING"
...
#End Region
```

### Erroneous output
```C#
/* TODO ERROR: Skipped RegionDirectiveTrivia */
...
/* TODO ERROR: Skipped EndRegionDirectiveTrivia */
```

### Expected output
```C#
#region Something
...
#endregion
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I'll consolidate with https://github.com/icsharpcode/CodeConverter/issues/15
