### ISSUE TITLE
How do I get code coverage to show results from ICSharpCode.CodeConverter

### ISSUE THREAD

**Issue by paul1956** [icsharpcode/CodeConverter#7]
When I run Code Coverage I only see coverage of Codeconverter.tests.dll and not the DLL that does the work but I know the code is being called because most of the tests pass (the ones not skipped).
![image](https://user-images.githubusercontent.com/12789369/34406011-8ac65c1c-eb6b-11e7-9fd0-ba7cd44460fe.png)

**Comment by christophwille** [comment]
afaik portable pdbs are not yet supported for the VS in-box code coverage tools

**Comment by GrahamTheCoder** [comment]
Since it works in ReSharper I'll close this since it's an issue with the code coverage tool
