### ISSUE TITLE
VB -> C#: Conversion of Interface events fails

### ISSUE THREAD

**Issue by Periodica2021** [icsharpcode/CodeConverter#700]
### Input code
```vbnet
Public Interface IFileSystem

    Event FileChanged(FileData As FileData)
    Event FileCreated(FileData As FileData)
    Event FileDeleted(FileData As FileData)
    Event FileRenamed(e As RenamedEventArgs)
    Event WatcherError(e As ErrorEventArgs)

End Interface

Public Class FileSystemWin
    Implements IFileSystem

    Public Event FileChanged(FileData As FileData) Implements IFileSystem.FileChanged
    Public Event FileCreated(FileData As FileData) Implements IFileSystem.FileCreated
    Public Event FileDeleted(FileData As FileData) Implements IFileSystem.FileDeleted
    Public Event FileRenamed(e As RenamedEventArgs) Implements IFileSystem.FileRenamed
    Public Event WatcherError(e As ErrorEventArgs) Implements IFileSystem.WatcherError

End Class
```

### Erroneous output

```C#

    public interface IFileSystem
    {
        event FileChangedEventHandler FileChanged;

        delegate void FileChangedEventHandler(FileData FileData);

        event FileCreatedEventHandler FileCreated;

        delegate void FileCreatedEventHandler(FileData FileData);

        event FileDeletedEventHandler FileDeleted;

        delegate void FileDeletedEventHandler(FileData FileData);

        event FileRenamedEventHandler FileRenamed;

        delegate void FileRenamedEventHandler(RenamedEventArgs e);

        event WatcherErrorEventHandler WatcherError;

        delegate void WatcherErrorEventHandler(ErrorEventArgs e);
}

    public class FileSystemWin : IFileSystem
    {
        public event FileChangedEventHandler FileChanged;

        public delegate void FileChangedEventHandler(FileData FileData);

        public event FileCreatedEventHandler FileCreated;

        public delegate void FileCreatedEventHandler(FileData FileData);

        public event FileDeletedEventHandler FileDeleted;

        public delegate void FileDeletedEventHandler(FileData FileData);

        public event FileRenamedEventHandler FileRenamed;

        public delegate void FileRenamedEventHandler(RenamedEventArgs e);

        public event WatcherErrorEventHandler WatcherError;

        public delegate void WatcherErrorEventHandler(ErrorEventArgs e);

}
```

### Expected output
Delegates should be referenced from interface, not redeclared

```C#
using System.IO;

public interface IFileSystem
{
    event FileChangedEventHandler FileChanged;

    delegate void FileChangedEventHandler(FileData FileData);

    event FileCreatedEventHandler FileCreated;

    delegate void FileCreatedEventHandler(FileData FileData);

    event FileDeletedEventHandler FileDeleted;

    delegate void FileDeletedEventHandler(FileData FileData);

    event FileRenamedEventHandler FileRenamed;

    delegate void FileRenamedEventHandler(RenamedEventArgs e);

    event WatcherErrorEventHandler WatcherError;

    delegate void WatcherErrorEventHandler(ErrorEventArgs e);
}

public class FileSystemWin : IFileSystem
{
    public event IFileSystem.FileChangedEventHandler FileChanged;

    public event IFileSystem.FileCreatedEventHandler FileCreated;

    public event IFileSystem.FileDeletedEventHandler FileDeleted;

    public event IFileSystem.FileRenamedEventHandler FileRenamed;

    public event IFileSystem.WatcherErrorEventHandler WatcherError;
}
```

### Details
* Product in use:  VS extension 
* Version in use: 8.2.2.0

* Any other relevant information to the issue, or your interest in contributing a fix.
* Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0738	'FileSystemWin' does not implement interface member 'IFileSystem.WatcherError'. 'FileSystemWin.WatcherError' cannot implement 'IFileSystem.WatcherError' because it does not have the matching return type of 'IFileSystem.WatcherErrorEventHandler'.	
Error	CS0738	'FileSystemWin' does not implement interface member 'IFileSystem.FileChanged'. 'FileSystemWin.FileChanged' cannot implement 'IFileSystem.FileChanged' because it does not have the matching return type of 'IFileSystem.FileChangedEventHandler'.	
Error	CS0738	'FileSystemWin' does not implement interface member 'IFileSystem.FileCreated'. 'FileSystemWin.FileCreated' cannot implement 'IFileSystem.FileCreated' because it does not have the matching return type of 'IFileSystem.FileCreatedEventHandler'.	
Error	CS0738	'FileSystemWin' does not implement interface member 'IFileSystem.FileDeleted'. 'FileSystemWin.FileDeleted' cannot implement 'IFileSystem.FileDeleted' because it does not have the matching return type of 'IFileSystem.FileDeletedEventHandler'.	
Error	CS0738	'FileSystemWin' does not implement interface member 'IFileSystem.FileRenamed'. 'FileSystemWin.FileRenamed' cannot implement 'IFileSystem.FileRenamed' because it does not have the matching return type of 'IFileSystem.FileRenamedEventHandler'.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. The delegates shouldn't be generated within the interface, but probably should be created somewhere nearby. We'll have to check the decompilation for maximum compatibility with existing code.

**Comment by Periodica2021** [comment]
I refactored my code so that every event is declared in the following way : 

Event ..;... as Eventhandler  (for the generic Eventargs)
or
Event ...... as Eventhandler(of Eventargs(of ........ ))

then conversion proceeds without errors

**Comment by GrahamTheCoder** [comment]
I had it backwards initially - I've updated the "expected output" section at the top with what is, I believe, the correct conversion

Thanks for this interesting example. I've never seen delegates declared in an interface before, and wouldn't have guessed that they can have visibility modifiers (not that it matters in this case)
