### ISSUE TITLE
VB -> C#: Grandparent extension method not implemented

### ISSUE THREAD

**Issue by Periodica2021** [icsharpcode/CodeConverter#703]
### Input code
```vbnet

If relevant, please enter some example code here to reproduce the issue, or the steps taken to cause the issue.
```
General Idea :

BaseObject
DerivedBaseObject : BaseObject
ConcreteObject : DerivedBaseObject

Extensions defined for base object not recognised as applicable to concrete object

### Erroneous output
```C#
base.Extensionmethod()
```

### Expected output
```C#
this.ExtensionMethod()
```

### Details
* Product in use:  VS extension 
* Version in use: latest
* Any other relevant information to the issue, or your interest in contributing a fix.

General Idea :

BaseObject
DerivedBaseObject : BaseObject
ConcreteObject : DerivedBaseObject

Extensions defined for base object not recognised as applicable to concrete object
Replacing base with this resolves the issue.

**Comment by GrahamTheCoder** [comment]
I had never come across this [C# compiler quirk 
](https://stackoverflow.com/a/27884101/1128762) before. Interesting! I'll see which solution feels neatest at the point of fixing. I think your suggestion is a good one when there isn't a more specific overload available for the derived type. Otherwise a cast, or full static method call would be needed.

**Comment by GrahamTheCoder** [comment]
(sorry, hit the wrong button)

**Comment by GrahamTheCoder** [comment]
I can't find a compiling example that would cause this. e.g. [This doesn't compile](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUGlnkWRdQHQBKArgHa4BLVJXYBhTBgHBK2YjLACAxpXz01dAArcIwJYVHAAhviLIT3SgHYADAGYAIjIFhKMeoQ+EtOvQDE+ioKYvIQA4pS4vobA+JQAFACU7p4pnBHc2CEAsqQAQsYiZo7Yzq6JyR4AorwwhP68gQLB9NW1BsaqdPQAPJUAHlS8+E28iQB89N66ioRZmDDc0oT9g8PBnSm9A5RDI+MVXtrTdQFBIUVOLjBxmIQAgkQA8hAAVpSBSXQpqemZddGxA6tE4NM4HA5bVZ7BITL6eKZ+U4jQgXEpXG73UzmKx2YqlGCfb6eNK4DIhAAq2AsQJqIMazTowLmC2kQA==):
```vbnet
Imports System
Imports System.Runtime.CompilerServices


Public Class Issue703Derived
    Public Function GetFalse()
        Return MyBase.IsDerived()
    End Function
End Class

<Extension()>
Public Module Extensions
    <Extension()>
    Public Function IsDerived(o As Object)
        Return False
    End Function
    
    <Extension()>
    Public Function IsDerived(o As Issue703Derived)
        Return True
    End Function
End Module
```

@Periodica2021 Can you provide your actual input?

**Comment by GrahamTheCoder** [comment]
Closing due to lack of repro
