### ISSUE TITLE
--core-only flag expects a value

### ISSUE THREAD

**Issue by NickLydon** [icsharpcode/CodeConverter#704]
### Steps to reproduce
1. > codeconv .\MySolution.sln --core-only

### Error message shown
 `Missing value for option 'core-only'`

### Details
* dotnet tool
* 8.2.2

I expected it to act as a flag (false by default), especially as the --help output doesn't mention possible values for it.

**Comment by GrahamTheCoder** [comment]
Thanks for reporting, should be fixed in the next release
