### ISSUE TITLE
event handler converion from c# to vb.net

### ISSUE THREAD

**Issue by hmzlam** [icsharpcode/CodeConverter#705]
why you are converting

control..click += eventhandler to the same line rather than

addhandler click,eventhandler

**Comment by GrahamTheCoder** [comment]
If you are converting that line without any context (e.g. In the Web converter), then the system can't know for sure if it's an event or an Integer. So it's probably converted the same as:
control.number += somenumber

For best results, convert as much of your program as possible. The visual studio extension allows you to use your project context even when only converting a single line.

**Comment by GrahamTheCoder** [comment]
Closing since there's nothing better than can be done with no context. Feel free to reopen with further ideas
