### ISSUE TITLE
Where did the snippet converter with more languages go?

### ISSUE THREAD

**Issue by poikilos** [icsharpcode/CodeConverter#709]
Hello,

Where did the old converter with more languages go? DeveloperFusion's C# to Code converter is down too.

I wrote a comprehensive tool to help convert (non-GUI aspects) from IronPython to vanilla Python as the primary feature of the following project: https://github.com/poikilos/PythonCodeTranslators

The snippet converter with more languages was formerly at http://codeconverter.sharpdevelop.net/SnippetConverter.aspx

I had used it to successfully convert projects. The way I did it was by using the snippet converter than then running my tool ([python_remove_dotnet.py](https://github.com/poikilos/pycodetool/blob/master/pycodetool/python_remove_dotnet.py), which uses my library in the same project) on the output of the resulting IronPython (or whatever .NET dependent Python that the output was).

**Comment by GrahamTheCoder** [comment]
Sorry, that predated my time on the project, and indeed, the existence of this repository (which was a total rewrite to use roslyn).
@christophwille may have more information about the previous code that existed there

**Comment by christophwille** [comment]
The old converter died together with SharpDevelop - sort of. We filleted the best parts into separate projects, however, as for the code converter, it was reduced to one language pair because of the switch from NRefactory to Roslyn. And we didn't keep the old converter online for too long simply because it was dead and would not get any more fixing.

**Comment by poikilos** [comment]
Thanks for the responses. I see.

For others finding this issue, I will tell you how I resolved this. I downloaded SharpDevelop 4.4 and used that. I couldn't open the SLN because the project was in an old format, so I simply made a new project and added all of the .cs files. Then I clicked "Project" (in the menu bar), "Convert", "From C# to Python". The output looked about the same as the online converter had done before. Therefore I ran `python python_remove_dotnet.py $source_file $destination_file $log_file` from my [pycodetool](https://github.com/poikilos/pycodetool) on each file to remove (most of the) IronPython and the output was a good starting point for completion by hand.

**Comment by GrahamTheCoder** [comment]
Thanks for the question, I'll close this since no further action is needed

**Comment by poikilos** [comment]
@christophwille Is the fully-featured NRefactory-based code converter source code available in any form?

**Comment by christophwille** [comment]
Somewhere for sure, but I can't remember from the top of my head which repo might have that code.
