### ISSUE TITLE
VB -> C#: Compiler Error CS0826 (no best type found for implicitly typed array)

### ISSUE THREAD

**Issue by Chiel92** [icsharpcode/CodeConverter#713]
I get this error a lot in all kinds of situations. It seems to me that the C# code should use an explicit type as default, and only if we are sure that the type can be derived maybe use an implicit type.

### Input code
```vbnet
{}
```

### Erroneous output
```C#
new [] {}
```

### Expected output
```C#
new ExplicitType[] {}
```

### Details
* Product in use: VS extension
![image](https://user-images.githubusercontent.com/1030961/112750501-3f695c00-8fc9-11eb-9426-116e769e5306.png)

**Comment by GrahamTheCoder** [comment]
Thanks for the report. `{}` is treated slightly differently in different contexts, could you give at least the whole statement?

For example:
```vbnet
Public Class C
    Public Sub M()
        M({})
    End Sub

    Public Sub M(x As Integer())
        Dim y As CompletelyMadeUpType() = {}
    End Sub
End Class
```
(correctly as far as I can see) converts to
```csharp
using System;

public partial class C
{
    public void M()
    {
        M(Array.Empty<int>());
    }

    public void M(int[] x)
    {
        var y = Array.Empty<CompletelyMadeUpType>();
    }
}
```

**Comment by Chiel92** [comment]
```vb.net
If Validate(name, par, {"foo"}, {}, Stuff) Then
'...
End If
```

with the following definition

```vb.net
Private Function Validate(x As String, y As IEnumerable(Of String), z As IEnumerable(Of String), w As IEnumerable(Of Int16), Errors As String) As Boolean
'...
End Function
```

**Comment by GrahamTheCoder** [comment]
Thanks!

**Comment by Chiel92** [comment]
Thanks!
