### ISSUE TITLE
Include erroneous/skipped code in TODO: Error

### ISSUE THREAD

**Issue by LeeMSilver** [icsharpcode/CodeConverter#715]
**Is your feature request related to a problem? Please describe.**
1) When converting VB-C# pre-processor directives are flagged as 'TODO: ERROR skipped ...'. In order to fix these it would speed things up if the skipped text were included as part of the TODO

2) As part of the converion the file 'my project\MyNamespace.Static.1.Designer.cs' is created. Since there is no similarly named .vb-file I don't know the source of the generated file (not a problem by itself) and without knowing the context of 'TODO: ERROR skipped ...' (there are many of them), they can only be fixed by a best-guess approach.

**Describe the solution you'd like**
The skipped text to included as part of the 'TODO: ERROR skipped ...' starting on a new-line.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by GrahamTheCoder** [comment]
Hi. Thanks for the suggestion. Good news: I've recently made exactly this change, so it'll ship with the next release
https://github.com/icsharpcode/CodeConverter/blob/master/CHANGELOG.md#vb---c
