### ISSUE TITLE
VB -> C#: Wrong conversion of With block

### ISSUE THREAD

**Issue by dfbag7** [icsharpcode/CodeConverter#716]
### Input code
```vbnet
Module Module1

    Structure Struct1
        Public String1 As String
    End Structure

    Sub Main()
        Dim s(2) As Struct1
        s(0).String1 = "Hello0"
        s(1).String1 = "Hello1"
        s(2).String1 = "Hello2"

        With s(1) 
            .String1 = "World"
        End With

        Console.WriteLine(s(0).String1)
        Console.WriteLine(s(1).String1)
        Console.WriteLine(s(2).String1)

    End Sub

End Module
```
The VB.NET code above outputs three lines as follows:
```
Hello0
World
Hello2
```

That is, the assignment made inside the `With` block is done correctly.

### Erroneous output
That VB.NET code is converted to the following C# code:

```C#
using System;

namespace VBtoCS_WithStruct
{
    static class Module1
    {
        public struct Struct1
        {
            public string String1;
        }

        public static void Main()
        {
            var s = new Struct1[3];
            s[0].String1 = "Hello0";
            s[1].String1 = "Hello1";
            s[2].String1 = "Hello2";
            {
                var withBlock = s[1];
                withBlock.String1 = "World";
            }

            Console.WriteLine(s[0].String1);
            Console.WriteLine(s[1].String1);
            Console.WriteLine(s[2].String1);
        }
    }
}
```

### Expected output
The expected output is
```
Hello0
World
Hello2
```
but the actual output is
```
Hello0
Hello1
Hello2
```
That is, the assignment in the converted `With` block does not work properly.

### Details
* Product in use: _VS extension_
* Version in use: _8.2.2.0_
* Did you see it working in a previous version, which? _I did not test it on previous versions_
* I believe that the root cause of the issue is that the way `With` blocks converted does not work when the `With` variable is `Structure`, which is not a reference type. So, this statement in the C# code `var withBlock = s[1];` actually creates a copy of the array element, then the copy is changed, but the original element of the array is never updated.

**Comment by GrahamTheCoder** [comment]
Thanks for the full info, and sorry for the delay in responding. I'm going to consolidate it with this issue: https://github.com/icsharpcode/CodeConverter/issues/634
