### ISSUE TITLE
VB -> C#: backslash escaping end of text string quote mark

### ISSUE THREAD

**Issue by TrevorMullen** [icsharpcode/CodeConverter#724]
### Input code
```vbnet
some example code here to reproduce the issue
```
        strSaveDocPath = "N:\ScannedDocs\"
        DriveStatus.DTest()

### Erroneous output
```C#
```
Everything after the first line is considered to be part of the quoted text (in the source window, it's red)
Later, in the source box, any text strings in double quotes is highlighted in black, telling us it is being processed as code.

To work around the issue, I changed the final \" to be \\"
Then, after conversion, I had to remove the extra \ from each location.

### Expected output
```C#
the output you expected.
```
        strSaveDocPath = @"N:\ScannedDocs\";  
        DriveStatus.DTest();

### Details
* Product in use: (https://codeconverter.icsharpcode.net)
* Version in use: web May-2021
* Did you see it working in a previous version, which? no.
* Any other relevant information to the issue, or your interest in contributing a fix.

It looks to me like the parser is using the \ to escape the " and thus thinks it is still parsing a text string...
This seems to be confirmed by the later text being black.

Not sure how I'd go helping to fix this, but I'm interested...
Trevor.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. In Visual Basic, everything is a verbatim string. When converting to C# the converter attempts to avoid unnecessarily adding an @ to make it a verbatim string.
If you add a test case and put a breakpoint around here you'll probably see what's happening. 

https://github.com/icsharpcode/CodeConverter/blob/1817d3a504dbd04c0bb63b225d1aa3dbb1c2bb96/CodeConverter/CSharp/LiteralConversions.cs#L95

Feel free to PR any progress even if it doesn't fully work and let me know if you want some more hints ☺

**Comment by BrianFreemanAtlanta** [comment]
I believe this is a display UI issue for the web tool, not a conversion issue. When I put the code:
```
 strSaveDocPath = @"N:\ScannedDocs\";  
    DriveStatus.DTest();
```
into the web convertor or the VS Studio plugin I get the proper conversion of:
```
        string strSavedDocPath = @"N:\ScannedDocs\";
        DriveStatus.DTest();
```
I did note the display issue for the syntax highlighter. When the code is added to the web page this is how it is displayed:
![image](https://user-images.githubusercontent.com/7062409/120083873-d91cba80-c099-11eb-88fc-acce76bae029.png)
You can see the syntax highlighter leaves the second line `DriveStatus.DTest()` in red as if it's part of the string.
I researched and found that monaco-editor/react is on version 4.1.3 where the web tool currently uses version 3.6.3. I tested doing a non-breaking upgrade to 3.8.3 and that resolves the issue. Here is what it looks line in version 3.8.3.
![image](https://user-images.githubusercontent.com/7062409/120130419-20877180-c194-11eb-91c8-627a03f2a7a5.png)

I also did an "npm upgrade" on the project which bumped the version of the following packages:
- axios 0.20.0 to 0.20.1
- bootstrap 4.1.3 to 4.6.0
- react 16.13.1 to 16.14.0
- react-dom 16.13.1 to 16.14.0
- react-scripts 3.4.3 to 3.4.4
- react-strap 8.4.1 to 8.9.0
- ajv 6.12.4 to 6.12.6
- eslint-plugin-import 2.22.0 to 2.23.4
- eslint-plugin-jsx-a11y 6.3.1 to 6.4.1
- eslint-plugin-react 7.24.0
- typescript 3.9.7 to 3.9.9

I also did an npm audit fix which bumped dependency versions and cleared most vulnerabilities. To resolve the final vulnerability it suggests upgrading react-scripts to version 4.0.3 which would require more testing.

@GrahamTheCoder how would you like to proceed? 
Do a pull requesting as-is (bumping all non-breaking dependencies to latest)?
Just upgrade monaco-editor/react and monaco-editor to latest non-breaking?
Resolve vulnerability (upgrade react-scripts) and test
Upgrade monaco-editor/react to latest version (4.1.3) - requires code changes (removed `ControlledEditor` & `DidMount` ) both of which are used in the project.

**Comment by GrahamTheCoder** [comment]
Thanks for the investigation @BrianFreemanAtlanta!
I'd be very happy to accept a PR upgrading any existing dependencies as far as you like (the more, and further the merrier) so long as the UI still works. For the one that requires code changes, perhaps do that bit as a separate PR on top if it's a bit more involved  and might need more tweaks
