### ISSUE TITLE
VB -> C#: After converting the code in Visual studio 2019, all the code is displaying in one line

### ISSUE THREAD

**Issue by ajaybabuthota** [icsharpcode/CodeConverter#726]
After converting Vb.net code to C#, The entire converted code is displaying in one line with no new lines or spaces. 
Example: usingSystem;usingSystem.Data;usingMicrosoft.VisualBasic;usingSystem.Data;usingSystem.Runtime.InteropServices;usingSystem.Windows.Forms

**Comment by ajaybabuthota** [comment]
This issue is due to the settings in Visual studio.

**Comment by GrahamTheCoder** [comment]
If you know which setting, do post here in case others see the same issue. Thanks!
