### ISSUE TITLE
VB -> C#: Long should be int

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#728]
### Input code
```vbnet
Dim strEingelesenesRightTrimLength As Long
strEingelesenesRightTrimLength = 4
If strEingelesenesRightTrimLength < 0 Then
    strEingelesenesRightTrimLength = 0
End If
```

### Erroneous output
```C#
long strEingelesenesRightTrimLength;
strEingelesenesRightTrimLength = 4L;
if (strEingelesenesRightTrimLength < 0L)
{
    strEingelesenesRightTrimLength = 0L;
}
```

### Expected output
```C#
int strEingelesenesRightTrimLength;
strEingelesenesRightTrimLength = 4;
if (strEingelesenesRightTrimLength < 0)
{
    strEingelesenesRightTrimLength = 0;
}
```

Why?
`long` in VB6 is 4 bytes, but `long` in C# is 8 bytes.
`long` from VB6 should be converted to `int` (4 bytes) in C#.

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: e.g. latest web
* Did you see it working in a previous version, which? Don't know
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by Saibamen** [comment]
This same for `Integer`:

`Integer` from VB6 (2 bytes) should be converted to `short`

**Comment by GrahamTheCoder** [comment]
Sorry, while it will "sort of" work on a bunch of cases, the converter isn't designed to handle vb6. I'd suggest upgrading vb6 to VB.net using the Microsoft tool in visual studio, then applying this converter from VB.net to c#
