### ISSUE TITLE
VB -> C#: Public type to public class + fix `SkippedTokensTrivia`

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#730]
### Input code
```vbnet
Public Type ST_Voreinstellung
  VoreinstellungDurchgefuehrt As Boolean
  Variante  As String
  VarianteOhneLeerstellen As String
  Breite As Double
  Hoehe As Double
  Menge As Double
  PAunten As Boolean
  GewebeartUnten As String
  KatzenKlappe As String
End Type
```

### Erroneous output
```C#
public object Type; /* TODO ERROR: Skipped SkippedTokensTrivia
ST_Voreinstellung*/
  VoreinstellungDurchgefuehrt();
  Variante();
  VarianteOhneLeerstellen();
  Breite();
  Hoehe();
  Menge();
  PAunten();
  GewebeartUnten();
  KatzenKlappe();
  Environment.Exit(0); /* TODO ERROR: Skipped SkippedTokensTrivia
Type*/
```

### Expected output
```C#
public class ST_Voreinstellung
{
    public bool VoreinstellungDurchgefuehrt;
    public string Variante;
    public string VarianteOhneLeerstellen;
    public double Breite;
    public double Hoehe;
    public double Menge;
    public bool PAunten;
    public string GewebeartUnten;
    public string KatzenKlappe;
}
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: web
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Sorry I missed this one. Same answer as #728. VBA/VB6 are not supported. Use the upgrade tools to get to VB.NET, then convert to C#.

Looks from this doc page like upgrading is just a case of saying "Structure" instead of "Type": https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30802
