### ISSUE TITLE
VB -> C#: Converter takes the property name from interface instead of the concrete class.

### ISSUE THREAD

**Issue by Yozer** [icsharpcode/CodeConverter#731]
### Input code
Here is the code: https://github.com/Yozer/VBConverterBug
Converting project ```ToConvert``` results in code that doesn't compile.

### Erroneous output
```C#
            var test = new Class1() { InterfaceProperty = "xxx" };
            Console.WriteLine(test.InterfaceProperty);
```

### Expected output
```C#
            var test = new Class1() { OtherProperty = "xxx" };
            Console.WriteLine(test.OtherProperty);
```

### Details
* Product in use: VS extension
* Version in use: 8.2.4
* Did you see it working in a previous version? No
* Any other relevant information to the issue, or your interest in contributing a fix.

Looks like the converter takes the property name from the interface instead of the concrete class.

**Comment by Yozer** [comment]
I'm a newbie when it comes to Roslyn and analyzers but would that fix make sense? I tried to convert quite large vb.net winforms project and it worked.
https://github.com/Yozer/CodeConverter/commit/c087b3f8480359910ec054b31162246dada9d3bc

**Comment by GrahamTheCoder** [comment]
Thanks for the report, I'll try to have a look this weekend

**Comment by Yozer** [comment]
I don't think my fix is correct.
It works fine for me because all my interfaces and their implementations are in another project that is not being converted.
For another case (when we're converting usages, interfaces & implementations) it incorrectly renames methods.

**Comment by GrahamTheCoder** [comment]
Ah yes, I've finally had a chance to havea  brief look at this. The code assumes that the symbol referenced is being converted, and hence normalized everything as required by C#. But if the referenc*ee* isn't converted, it won't match up. So perhaps before the ".Last()" we need `TakeWhile(t => assembliesBeingConverted.Contains(t.ContainingAssembly))` - we'd need to pass assembliesBeingConverted into the converter from higher up obviously.
Happy to accept a PR along those lines if you're interested in contributing?

**Comment by Yozer** [comment]
https://github.com/icsharpcode/CodeConverter/pull/732
I had to bubble down the ```assembliesBeingConverted```.
All tests are green.

Is it possible to write a test where part of the VB code is a different assembly?

**Comment by GrahamTheCoder** [comment]
If you remove the "Skip" on this test, it should run locally: https://github.com/icsharpcode/CodeConverter/blob/master/Tests/CSharp/MultiFileSolutionAndProjectTests.cs#L22
(Apologies -  A build server change broke it a while ago and I haven't had time to investigate a fix for it yet).
There's a source solution which you could ensure has the vb project referencing the c# project then create a test case in
