### ISSUE TITLE
VB -> C#: Error compiling Linq with early Select

### ISSUE THREAD

**Issue by jhony1104** [icsharpcode/CodeConverter#736]
### VB.Net input code
```vbnet
Dim query = From t in Test
            Select t.foo
            Where t.Id = 123
```

### Erroneous output
```C#
var query = from t in Test
            select t.foo;
```

### Expected output
```C#
var query = from t in Test
            where t.Id = 123
            select t.foo;
```

### Details
* Product in use: codeconverter.icsharpcode.net and VS extension
* Version in use: current codeconverter.icsharpcode.net
* Did you see it working in a previous version, which? no (first time user)

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I hadn't realised that Where could come after Select.

**Comment by GrahamTheCoder** [comment]
I couldn't get your example to compile because `t` is out of scope after the Select, but if I replace it with a valid condition I can repro 👍
