### ISSUE TITLE
vb-->C# designer components is never assigned to, and will always have its default value full

### ISSUE THREAD

**Issue by jayobrien** [icsharpcode/CodeConverter#739]
I have converted extensive VB.net code to C#.   There are multiple warnings in designer.cs that Field 'XXX.components' is never assigned to, and will always have its default value null.    Where these occur, there is a comment above // Required by the Windows Form Designer

An example of the warning would be the line private IContainer components;

It also shows up in DataGridViewTextTextBoxColumn

The code runs with no problem.

**Comment by GrahamTheCoder** [comment]
Glad to hear it worked. In the VB code, was the field ever assigned to?

**Comment by jayobrien** [comment]
'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

is the code in vb.net that corresponds to 

  // Required by the Windows Form Designer
        private IContainer components;

**Comment by GrahamTheCoder** [comment]
If there wasn't any other code using `components` is VB, then that's a faithful conversion and there's no problem.
Designer files are supposed to be autogenerated anyway, so if you always open the form, then press save and it might regenerate - possibly without that property since C#'s winforms designer is slightly different.

**Comment by jayobrien** [comment]
It made sense that I needed to open my form and save it and the form would be redesigned and I wouldn't have this warning.   I did this and it didn't work.   I did it again, slightly changing the form and I still receive the warning.

**Comment by GrahamTheCoder** [comment]
You can also try manually removing that field of course if the warning bothers you

**Comment by jayobrien** [comment]
A lot of the warnings are on specific cells of datagridview.   Some bound, some not.   I just suppressed the warning 0649 in errors and warnings.   Thank you for trying to help.
