### ISSUE TITLE
VB -> C#: MySettings not converted correctly

### ISSUE THREAD

**Issue by jayobrien** [icsharpcode/CodeConverter#740]
### VB.Net input code
```vbnet
If relevant, please enter some example VB.NET code here to reproduce the issue, or the steps taken to cause the issue.
```

### Erroneous output
```C#
If relevant, the incorrectly converted output, or an exception with stack trace.
```

### Expected output
```C#
If relevant, the output you expected, or a description of what you expected.
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by jayobrien** [comment]
While the code appears okay, my report viewers appear to have dropped their connection string.   When I tried to preview the data in the TableAdapter, I received an error "Unable to find connection 'XXXConnectionString' for object MySettings.   I don't know where to find the "MySettings" connection string.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I suspect this is a MySettings specific issue (I think there's a settings file called that inside the Properties folder usually). I've never seen an app actually use that feature, so I've never tested it, I'll see if the code converter can be tested/improved here at some point.

In terms of solving the immediate issue for your code base:
* First I'd suggest trying to find the old connection string. If it isn't where I suggested, try using a tool (I'm a fan of GrepWin) to search the text of all files in the solution directory for "ConnectionString", and it'll probably turn up.
* Once found, I'd suggest moving it (and any other settings) elsewhere, for example into App.config, Web.config or appsettings.json if you're using a more recent version of dot net.
* Obviously if it's only a couple, you can hardcode them.

Hope that helps 😃

**Comment by jayobrien** [comment]
Thank you.    In my search for the "MySettings", I went to the dataset and opened it with the source code text editor.    Looking at the old code and the new code, I found that an extra line had been added (the third below)
        <Connections>
          <Connection AppSettingsObjectName="MySettings" AppSettingsPropertyName="MasterDataConnectionString" IsAppSettingsProperty="true" Modifier="Assembly" Name="MasterDataConnectionString (MySettings)" PropertyReference="ApplicationSettings.CattleMaster.My.MySettings.GlobalReference.Default.MasterDataConnectionString" Provider="System.Data.OleDb" />
          <Connection AppSettingsObjectName="MySettings" AppSettingsPropertyName="MasterDataConnectionString1" IsAppSettingsProperty="true" Modifier="Assembly" Name="MasterDataConnectionString1 (MySettings)" PropertyReference="ApplicationSettings.CattleMaster.My.MySettings.GlobalReference.Default.MasterDataConnectionString1" Provider="System.Data.OleDb" />
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="MasterDataConnectionString" ConnectionStringObject="" IsAppSettingsProperty="true" Modifier="Assembly" Name="MasterDataConnectionString (Settings)" PropertyReference="ApplicationSettings.CattleMaster.Properties.Settings.GlobalReference.Default.MasterDataConnectionString" Provider="System.Data.OleDb" />
        </Connections>

The easiest solution seemed to be to delete the "Settings" line.   This gave me 360 errors as this line was obviously used.  

I tried to delete the blank connectionStringObject, but that didn't do anything.

I still think not being able to preview data is a clue.    How I found all of this out was that I was adding a column to a datagridview.   I was able to do it on the old VB.net program, but in the C# program, it is picking up the wrong field.   I think I can fix that, but the underlying issue worries me.   

I am working through the whole program with the ultimate goal of operating only C#.

Again, the conversion program was a monster help.   Thank you again.

**Comment by jayobrien** [comment]
<Connections>
          <Connection AppSettingsObjectName="MySettings" AppSettingsPropertyName="MasterDataConnectionString" IsAppSettingsProperty="true" Modifier="Assembly" Name="MasterDataConnectionString (MySettings)" PropertyReference="ApplicationSettings.CattleMaster.My.MySettings.GlobalReference.Default.MasterDataConnectionString" Provider="System.Data.OleDb" />
          <Connection AppSettingsObjectName="MySettings" AppSettingsPropertyName="MasterDataConnectionString1" IsAppSettingsProperty="true" Modifier="Assembly" Name="MasterDataConnectionString1 (MySettings)" PropertyReference="ApplicationSettings.CattleMaster.My.MySettings.GlobalReference.Default.MasterDataConnectionString1" Provider="System.Data.OleDb" />
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="MasterDataConnectionString" ConnectionStringObject="" IsAppSettingsProperty="true" Modifier="Assembly" Name="MasterDataConnectionString (Settings)" PropertyReference="ApplicationSettings.CattleMaster.Properties.Settings.GlobalReference.Default.MasterDataConnectionString" Provider="System.Data.OleDb" />
        </Connections>

It appears the lines were not added from the code

**Comment by jayobrien** [comment]
I may not have given enough information.    Under Settings in properties folder, it gives the name, the type as (Connection string), the scope as Application and Value as Provider=Microsoft.ACE.OLEDB.12.0;Data Source=S:\Data\MasterData.accdb.    I can not see anything that tells me whether this is "MySettings" or "Settings"

**Comment by jayobrien** [comment]
What I ended up doing is 
1.  open the xsd file
2.  individually deleting each table
3.  dragging them back from my Server Explorer 
4. right click on the table and click on configure step through

**Comment by jayobrien** [comment]
Having successfully run on the programs converted from vb.net to c#, I decided to tweak them and remove all “using Microsoft.VisualBasic”.   I did this successfully, except in MyNamespace.Static.1.Designer.CS. There are 2 references to MyGroupCollection.
[MyGroupCollection("System.Windows.Forms.Form", "Create__Instance__", "Dispose__Instance__", "My.MyProject.Forms")]
[MyGroupCollection("System.Web.Services.Protocols.SoapHttpClientProtocol", "Create__Instance__", "Dispose__Instance__", "")]
The errors are "...MyGroupCollection could not be found..." and "MyGroupCollectionAttribute could not be found". What do I do about these?

What is the function of MyNamespace.Static.1.Designer.CS?

Thank you guys, again.   Your conversion program was an incredible help

**Comment by GrahamTheCoder** [comment]
The file is the converted version of what the VB compiler creates during compilation. I think the attribute is just used on the template of that file to [tell the compiler where to fill in the properties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.mygroupcollectionattribute?view=net-6.0). Since they've already been filled in by this point, and you'll never run the VB compiler on that file, I think you can just remove those 2 attributes.

**Comment by jayobrien** [comment]
Thanks
