### ISSUE TITLE
VB -> C#:  Report definition for report has not been specified

### ISSUE THREAD

**Issue by jayobrien** [icsharpcode/CodeConverter#742]
When going to print a report from a report viewer with a rdlc report, there is an error Report definition for report 'xxx' has not been specified.    I opened the rdlc form and it appeared the links were broken.   I refreshed each table and they appear to be working; however, the error continued.    

I went to the form that has the report viewer and looked at the table adapters and they were functioning.   I clicked on the reportviewer control and it was calling the correct rdlc.   I clicked on choose data sources and it gave me no options and did not allow me to enter any.  I clicked on rebind data sources, but still couldn't.   The only work around was to delete the report viewer and reinstall.   This worked, but I have a lot of reports; so, it is a pain.

**Comment by GrahamTheCoder** [comment]
Sorry to hear you're having trouble with your reports. Now that you have one fixed, I'd suggest doing a diff of it broken vs fixed so you can see what the key difference is. That way you might be able to use a Find/Replace to fix up the whole lot in one go.

It could just be that it's related to your connection string issue, or it could be a missing ReportPath (or the file isn't in the place ReportPath says). e.g. https://stackoverflow.com/questions/18986829/the-report-definition-for-report-xxx-has-not-been-specified

I've never heard of a VB RDLC report before, so you'll know better than me what to do. If you do get a small repro of the issue, please attach it here so I or someone else can improve the converter for future users.

Thanks!

**Comment by jayobrien** [comment]
I'm not sure of what you mean by a small repro of the issues, but what it appears to me is that the report viewer is dropping the Datasources and would not reconnect.   I simply deleted the report viewer and added a new one from toolbox.   When I picked the RDLC, it gave me the datasources and then I rebound the datasources.    After I did them all, I wondered if I could have just changed the rdlc to another and then back to the original one.   This would be a lot easier, but I had already done all of my reports.

Thank you again for a converter that works incredibly well.   

As I test all of my programs, I will let you know if there are any other issues.

**Comment by GrahamTheCoder** [comment]
Sorry, I missed replying to this. "repro" is short for reproduction. It means a way to reproduce/recreate the issue.
As you've probably found in your own programming, it's hard to fix a problem when someone just says "title bar is broken".

For the code converter it's usually very easy to specify a small bit of code in isolation. See example:
https://github.com/icsharpcode/CodeConverter/issues/701

However, in other cases (like this one) that might need multiple files, people have zipped up a new project with the minimum code to cause the problem. Or alternatively, copied their project and deleted everything unrelated to the issue. This avoids them sharing any secret source code and makes it easy for me to debug, test and fix the issue without spending hours trying to get to the state that someone else already has.

Hope that helps, I'll close this issue until it has a repro.
