### ISSUE TITLE
VB -> C#: Produces different output result 

### ISSUE THREAD

**Issue by Prabhakantha** [icsharpcode/CodeConverter#745]
### VB.Net input code
```vbnet
Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

        Dim somestring = "2420sddfsw32346010801AKL001AS"
        Dim someValue = ""
        Dim someDigit As Long = 98

        someValue = Chr(someDigit + 50)
        somestring = somestring & someValue & "œ"

        MessageBox.Show(somestring)

End Sub


```
**Output :**  2420sddfsw32346010801AKL001AS”œ

### Erroneous output
```C#
 private void Form1_Load(object sender, EventArgs e)
 {
            string somestring = "2420sddfsw32346010801AKL001AS";
            string someValue = "";
            long someDigit = 98L;
            someValue = Conversions.ToString((char)(someDigit + 50L));
            somestring = somestring + someValue + "œ";
            MessageBox.Show(somestring);
 }


```
**Output :**  2420sddfsw32346010801AKL001ASœ

### Expected output
```C#
 private void Form1_Load(object sender, EventArgs e)
 {
            string somestring = "2420sddfsw32346010801AKL001AS";
            string someValue = "";
            long someDigit = 98L;
            someValue = Strings.Chr((int)(someDigit + 50)).ToString(); 
            somestring = somestring + someValue + "œ";
            MessageBox.Show(somestring);
 }
```

### Details
* Product in use: VS extension 
* Version in use: 8.3.0.0
* Did you see it working in a previous version, which? No
* This is particularly problematic as the conversion produces no error, and the output compiles, but the behavior of the program changes.

**Comment by GrahamTheCoder** [comment]
Thanks for the report, I'll try to reproduce the issue

**Comment by GrahamTheCoder** [comment]
I see the problem. `Chr` has been converted to `(char)`. This is correct for characters in the range 0-127, but after that the function `Chr` uses the current culture's code page, whereas the underlying char object is the unicode ordinal. I'll see what I can do

**Comment by jconnop** [comment]
Thanks @GrahamTheCoder !

**Comment by Prabhakantha** [comment]
Thanks @GrahamTheCoder
