### ISSUE TITLE
VB -> C#: Exclamation Point (Bang) Operator for `IDataReader`

### ISSUE THREAD

**Issue by MaxKlotz** [icsharpcode/CodeConverter#765]
### VB.Net input code
```vbnet
Public Sub GetByName(dataReader As IDataReader)
  Dim foo As Object
  foo = dataReader!foo
End Sub
```

### Erroneous output
```C#
public void GetByName(IDataReader dataReader)
{
  object foo;
  foo = dataReader.Item;
}
```

### Expected output
```C#
public void GetByName(IDataReader dataReader)
{
  object foo;
  foo = dataReader["foo"];
}
```

### Details
* Product in use: VS extension
* Version in use: 8.4.0.0
* The [ExclamationMark](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/special-characters-in-code#exclamation-point--operator) operatior is handled wrong

**Comment by GrahamTheCoder** [comment]
Thanks for the report. This was the original commit that dealt with this syntax which should be a good starting point for tweaking to fix this:
https://github.com/icsharpcode/CodeConverter/commit/745007ae61b46c3a8895ae00be51346b9dac77e4

**Comment by GrahamTheCoder** [comment]
Fixef by d2456b1b6cde66fe41427efcb29aa418a9e18e2c

**Comment by MaxKlotz** [comment]
You made my life a whole lot easier!
Thank you ♥
