### ISSUE TITLE
VB -> C#:Enable the extension on VS 2017 cause crashing

### ISSUE THREAD

**Issue by Hanadi-Bd** [icsharpcode/CodeConverter#766]
Hello,

I'm facing an issue when enabling the extension on VS 2017, it will be crashed and closed once I've open any project or create a new one.

### Details
* Product in use: VS 2017 extension 
* Version in use: V8.4.0.0
* Did you see it working in a previous version, which? Yes, unfortunately, can't remember

Kindly advice.
BR

**Comment by Hanadi-Bd** [comment]
I've install .NET Core SDK 2.2.110 and the issue fixed.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. If you still have the  [Visual Studio Activity log](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019#to-examine-the-activity-log) from the crash please attach it in case I can either fix the issue or document requirements.
