### ISSUE TITLE
VB Delegate function conversion error 

### ISSUE THREAD

**Issue by acrigney** [icsharpcode/CodeConverter#771]
Awesome product guys, a really great job thanks heaps!

I have had a few simple errors but I thought you might be interested in this one.
This did not convert
 Public Delegate Function Operation(Of T)() As T
It should have come across to C# as 
public delegate T Operation<T>();

The
### Erroneous output

public delegate Operation<T>.T Operation<T>();

version used
C# -> VB
[8.4.0] - 2021-09-05

**Comment by GrahamTheCoder** [comment]
Thanks for the report, glad it's helpful!
The error looks likely to be an issue with the "Expand" pre-step in roslyn. Should be an easy workaround hopefully

**Comment by acrigney** [comment]
Great stuff thanks mate, I would have thought nobody is doing any VB.NET
these days, you must do this for fun? I just love C# and it seems that the
performance is so close to C++? Actually when I looked into that a while
ago Microsoft would not let you publish any results on that.

**Comment by GrahamTheCoder** [comment]
The fix should hopefully be released quite soon

Fortunately, not that many people are using VB.NET for serious projects nowadays, but according to the last stackoverflow survey where I saw it included, the various forms of visual basic occupy three of the top five most dreaded languages [from this article](https://visualstudiomagazine.com/articles/2018/03/13/stack-overflow-survey.aspx):
![image](https://user-images.githubusercontent.com/2490482/135721839-ccdc44f6-b8b8-47b6-b069-4ec78cf881b0.png)

When I ended up needing to pick up someone's legacy VB.NET code, it seemed crazy to me that there wasn't a top quality converter available I could find (even paid for ones seemed hopeless when I tried them). So it's mainly to help the world escape from VB, but that's not to say it's never fun too!
