### ISSUE TITLE
Name qualification failed for this file. System.InvalidCastException

### ISSUE THREAD

**Issue by ozgunlu** [icsharpcode/CodeConverter#773]
I got an error when i try to convert vb 2 c#.. 

Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax'.

**Comment by GrahamTheCoder** [comment]
Hi there, thanks for the report. Could you post the whole error with stack trace please? It's a very generic error message that can happen anywhere
