### ISSUE TITLE
VB -> C#: Missing event wiring for overridden members

### ISSUE THREAD

**Issue by plalonde4321** [icsharpcode/CodeConverter#774]
### VB.Net input code

```vbnet
Private Sub btn2_Click(sender As Object, e As EventArgs) Handles btn2.Click
        lblMsg.Text = "Copying data From clipboard..."
        lblMsg.Refresh()
        Utils.ClipboardToDGV(uGrid.dgvData, True)
        lblMsg.Text = CStr(uGrid.dgvData.Rows.Count) & " rows are ready to upload."
        lblMsg.Refresh()

        btn5.Visible = True
    End Sub
```

### Erroneous output
No event wiring. Function is converted correctly but event handler function is not wired to btn2.Click event

### Expected output
Event handler function should be wired to btn2.Click event

### Details
* Product in use: VS extension
* Version in use: 2.11.106.19330
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

Problem occurs on forms that inherit base form which has the definition of btn2
In the base form, vb.net code had a public Button btn2, but in the c# version it has a private Button _btn2 and a getter/setter called btn2

The designer code for child forms are referencing in some cases the private class member, e.g. _btn2, which causes an error since _btn2 is private, and in other cases the public member, e.g. btn3. The modifier issue is minor, the main problem is the wiring of events.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. The version number you mentioned would be pretty ancient, so do check that, but I'm guessing that's just a mixup.

I think we already have some tests around events on fields from a base class but I'll try to create a repro when I get a chance, perhaps this weekend.
Could you post the declaration of btn2?

**Comment by plalonde4321** [comment]
Any ETA on when this will be fixed? Thanks!

**Comment by GrahamTheCoder** [comment]
The best I can say is "not in the next week". I'll try to find time to at least attempt it over Christmas, but may have to delay it if it's turning out too big. I'll bump it up my list a bit since it seems you're waiting for it, but there's another big issue above it - any particular time you're planning to do the conversion that it'd be handy to have this by?

**Comment by plalonde4321** [comment]
Thanks! The sooner the better to do the conversion, trying to get rid of vb.net and have all C# for our apps but I understand there might be other priorities to tackle and it's not causing problems per say. If it could get done before end of Q1 2022 that would be great! This is a great tool by the way!

**Comment by GrahamTheCoder** [comment]
I started spiking a fix for this recently. It's quite a tricky set of constraints but I'm reasonably confident in the solution. I'll try to complete it next week but can't promise anything and it'll still have some edge cases that break I'm sure

**Comment by GrahamTheCoder** [comment]
I've made some decent progress on the small test case now. I'll try it on some real apps tomorrow hopefully and refine it. If you're willing to try out a prerelease build from the build system (or build it locally and try it), let me know and I can give some hints on doing so if it's not obvious (in particular something a bit odd has happened with the local debug options attaching a debugger when building from source, so it's best to just build it then install the output and restart)
