### ISSUE TITLE
Can't open solution with extension enable, sln works when disabled

### ISSUE THREAD

**Issue by eschneider999** [icsharpcode/CodeConverter#775]
I believe this is the error. I attached to vs and I see this error:

System.ExecutionEngineException
  HResult=0x80131506
  Message=Exception of type 'System.ExecutionEngineException' was thrown.

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by eschneider999** [comment]
turn word wrap off

**Comment by WolvenRA** [comment]
I have the exact same problem after installing CodeConverter.  I'm using VS2017 version 15.9.39.  The error i got when trying to load the solution was "Unknown Hard Error".  Not very helpful.  After uninstalling CodeConverter, I could open the solution with no errors.
