### ISSUE TITLE
Preserve line breaks when coding inline strings

### ISSUE THREAD

**Issue by docfresh** [icsharpcode/CodeConverter#790]
**Is your feature request related to a problem? Please describe.**
My VB code was formatted multiline, but got converted to one line.

**Describe the solution you'd like**
Preserve the linebreaks in the definition of a string in VB, when converting to C#.

**Describe alternatives you've considered**
none

**Additional context**

This code

![image](https://user-images.githubusercontent.com/8064022/142972028-c01c4a59-845d-4940-a4f0-df8aab5ce1de.png)

into this

![image](https://user-images.githubusercontent.com/8064022/142972045-94fd536e-bd46-41bd-bb5a-a33a51866ac6.png)

Much harder to read.

**Comment by GrahamTheCoder** [comment]
Thanks for the report, I'll consolidate it with https://github.com/icsharpcode/CodeConverter/issues/358 - I'll update the title of that so it's easier to find
