### ISSUE TITLE
FileNotFoundException: 'Microsoft.Bcl.AsyncInerfaces' 

### ISSUE THREAD

**Issue by sillyuh** [icsharpcode/CodeConverter#797]
Trying to convert entire VB project to C#

### Error message shown
![image](https://user-images.githubusercontent.com/95448571/144509257-f19944e8-87d9-495d-a316-052bdf4d3cfc.png)

### Details
VS2017 Version 15.9.41 
.Net Framework Version 4.8.04084

Just downloaded today and tried sharing with my team, then ran into this error while trying to convert an entire project using the tool. 
I tried search through open and closed issues, but couldn't find exactly this error. I do have the files it's not finding in the bin folder...

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Sorry about the issue. I've had a few such FileNotFoundException reports from VS2017 users recently. I'm afraid I'm really struggling to keep the tool working in every combination of installation features + addons from back then. 
E.g. https://github.com/icsharpcode/CodeConverter/issues/755#issuecomment-913401788

I'm afraid I'm likely to drop support for it very soon, but if possible I would like to get one last version out that works for as many people as possible before I do.

I did add a setting in Tools->Options->Code Converter to load assemblies regardless of version - which you could try. But from the error message I think it's probably enabled already.

It may be worth installing VS2022 community edition just to try and get this conversion done, or try the command line tool. Out of interest, can I ask what's keeping you on 2017?

If you'd like to help me try to debug the issue, I'll need to know what (if any) assembly version of that assembly is loaded (and where from). You can attach a second vs instance to the one with the error and open up Debug->Windows->Modules to find that.

**Comment by sillyuh** [comment]
well..... I wasn't able to get it working by disabling the ADL extension or a couple of others, however, I did try it in VS2019 and had no issues. 

for your interest - I work at a uni that is still a little old school. we're still upgrading projects from VS2010 :D thanks for your rapid response!

**Comment by GrahamTheCoder** [comment]
I see, what a pain! Glad to hear it converts now at least, do let me know of any issues/oddities in the resulting code, good luck ☺
