### ISSUE TITLE
C# -> VB error with step <0

### ISSUE THREAD

**Issue by marco402** [icsharpcode/CodeConverter#798]
CodeC#:
 for (int m=nbMessage;m>0;m--)

CodeConverter:
For m As Integer = nbMessage To 0 + 1

Code VBNET
For m As Integer = nbMessage To 1 Step -1

Marc

**Comment by GrahamTheCoder** [comment]
I could not reproduce the issue shown. There are existing tests which demonstrate the `Step -1` is correctly added. I've added an extra test that even more closely matches your example.

It's possible you were using a very old version of the converter (e.g. the one Telerik hosts). If you are still seeing this issue, please try to provide some example code that reproduces the issue on the latest version: https://codeconverter.icsharpcode.net/

e.g.
https://github.com/icsharpcode/CodeConverter/blob/475e6fb/Tests/VB/StatementTests.cs#L809-L818
