### ISSUE TITLE
Code conversion breaks within one minute with a big object reference error dialog.

### ISSUE THREAD

**Issue by Panchraj** [icsharpcode/CodeConverter#804]
### Steps to reproduce
1. Right click on my VB.net Project named OFMEngine.
2. it displays below info in output window.
    Building solution prior to conversion for maximum accuracy...
    Converting OFMEngine...
3. Then it display a big dialog error having below information.

### Error message shown
---------------------------
Code converter 8.4.3 - Visual Studio 16.11.31911.196
---------------------------
An error has occurred during conversion - press Ctrl+C to copy the details: System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.CodeConverter.CSharp.ProjectMergedDeclarationExtensions.<ReadVbEmbeddedResources>d__2.MoveNext()

detailed error is attached.
[VB to Csharp Conversion error.txt](https://github.com/icsharpcode/CodeConverter/files/7784883/VB.to.Csharp.Conversion.error.txt)

**Comment by GrahamTheCoder** [comment]
Thanks for the report, I'll try to figure out what is null. I may need more info about the project file to verify any fix

**Comment by Panchraj** [comment]
Project file is attached.
[OFMEngine.txt](https://github.com/icsharpcode/CodeConverter/files/7787227/OFMEngine.txt)

**Comment by GrahamTheCoder** [comment]
Thanks, I'll try to take a look soon

**Comment by Panchraj** [comment]
Thanks for resolving the issue on high priority basis.
I am using the code converter as visual studio extension.
So kindly update the same.

**Comment by GrahamTheCoder** [comment]
The code will go out in the next release (probably in the next week or two). In the meantime if you need the fix, you can uninstall the current extension, and install the CI build (the VSIX) from the bottom of this page: https://github.com/icsharpcode/CodeConverter/actions/runs/1640619541
Let me know if it works for you, thanks!

**Comment by Panchraj** [comment]
Now its working fine. Thanks a lot.

**Comment by GrahamTheCoder** [comment]
Great, thanks!
