### ISSUE TITLE
VB -> C#: DateTime should be explicitly converted to string within concatenation

### ISSUE THREAD

**Issue by Yozer** [icsharpcode/CodeConverter#806]
### VB.Net input code
```vbnet
Dim x = #2022-01-01# & " 15:00"
```
x has value of ```2022-01-01 15:00```

### Erroneous output
```C#
string x = DateTime.Parse("2022-01-01") + " 15:00"
```

x will have value of ```2022-01-01 00:00:00 15:00``` (depending on the culture)

### Expected output
```C#
string x = Conversions.ToString(DateTime.Parse("2022-01-01")) + " 15:00"
```

### Details
* Product in use: **VS extension**
* Version in use: **8.4.3.0**
* Did you see it working in a previous version, which? Probably worked before fixing #508 
* Any other relevant information to the issue, or your interest in contributing a fix.
Incorrect value of the string can change application logic in an unexpected way. 
Fix:
#807 

https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/functions/return-values-for-the-cstr-function#cstr-and-date
CStr will strip time or date if it has _neutral value_.

**Comment by GrahamTheCoder** [comment]
Thanks, hopefully we can just make date times  always keep CStr. Though if it's definitely just this case that differs we could check for a compile time constant value known and omit if the time isn't neutral
