### ISSUE TITLE
Vs Extension should NOT build entire solution prior to conversion

### ISSUE THREAD

**Issue by fitdev** [icsharpcode/CodeConverter#816]
### Steps to reproduce
1. Right-click on the vb project in Solution Explorer
2. Click on Convert to C#

### What happens:
Entire solution is being built.

### What should happen:
Only the project should be built along with its dependencies. Why? In my case I had a solution with 80+ projects, only 20 of which were related to the project being converted, which moreover was up to date anyways. So the conversion process triggered entire solution rebuilt which was completely unnecessary, and moreover may screw up various things when you do not expect certain projects to be built.

**Comment by GrahamTheCoder** [comment]
Sounds reasonable to me. I'll see if I can make converting a single project/document only build the project in question

**Comment by fitdev** [comment]
Thank you for looking into this. If this is too hard, at the least show a warning / messagebox asking whether extension should rebuild the whole solution, or the user would do it manually before attempting the conversion.

**Comment by GrahamTheCoder** [comment]
My first attempt to improve this was released this morning, please let me know if updating to [8.4.5.0](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter) improves things for you (or indeed causes any new issues!)

**Comment by fitdev** [comment]
Just tested the new version. It worked really well this time - no solution rebuild was triggered! Thanks for your work!

**Comment by GrahamTheCoder** [comment]
Great, thanks for letting me know!
