### ISSUE TITLE
VB -> C#. No option in visual studio and command line showing weird message

### ISSUE THREAD

**Issue by leoxama** [icsharpcode/CodeConverter#845]
### Steps to reproduce
1. I have Installed CodeConverter in every way possible
2. launched on my project and tested on a basic hello world project with no result

### Message shown in the console app
Using .NET Framework MSBuild from D:\Programs\Visual Studio\MSBuild\Current\Bin\MSBuild.exe

### Details
* It shows this message without actually performing any operation
* .NET 6.0

**Comment by leoxama** [comment]
I fixed the issue by using the --core-only option. I suppose it is linked to the fact that I have .NET Framework installed but my project is using .NET 6.0. This leads to an error returned by  `RunNetFrameworkExeAsync`.

**Comment by GrahamTheCoder** [comment]
Thanks for letting us know the workaround. Do you know what error was returned by `RunNetFrameworkExeAsync`?
You said you have .NET Framework installed, so it should have been able to run that in theory.

**Comment by GrahamTheCoder** [comment]
The command line issue should be resolved in the next release
