### ISSUE TITLE
VB -> C#: break refers to wrong one of nested blocks

### ISSUE THREAD

**Issue by PeterSwinkels** [icsharpcode/CodeConverter#846]
### VB.Net input code
```vbnet
Exit DO and Exit For

### Erroneous output
```C#
Always outputs "break". Even when for and do loops are nested.

### Expected output
```C#
The proper way of exiting a loop or a warning.

### Details
None.

**Comment by GrahamTheCoder** [comment]
Hi Peter, thanks for getting in touch. This is an area we've improved in the last 2 months. Could you give an example snippet of code that shows the problem when entered into https://codeconverter.icsharpcode.net/ (which always runs on the latest version of our converter library). If your case works there, I'd suggest using the latest version of the VS extension, website or command line (further details [on the readme](https://github.com/icsharpcode/CodeConverter/blob/master/README.md#code-converter--) rather than the older versions embedded in 3rd party sites.

To demonstrate, here's an example of some code which I believe does work correctly:

```vbnet
Imports System.Collections.Generic

Public Class VisualBasicClass
    Public Shared Sub Main()
        Dim LstTmp As New List(Of Integer)({1,2,3,4,5})
        Dim i_Total As Integer
        For Each CurVal As Integer In LstTmp
            i_Total += CurVal
            Select Case CurVal
                Case 6
                    Dim b As Integer
                    b = 0
                    Do
                        If b = 2 Then Continue Do
                        If b = 3 Then Exit Do
                        If b = 4 Then Exit Select
                        If b = 5 Then Continue For
                        Exit For
                        b+=1
                    Loop
            End Select
        Next
        System.Console.WriteLine(i_Total.ToString()) 'Prints 15
    End Sub
End Class
````

[Converter](https://codeconverter.icsharpcode.net/) outputs:
```csharp
using System.Collections.Generic;

public partial class VisualBasicClass
{
    public static void Main()
    {
        var LstTmp = new List<int>(new[] { 1, 2, 3, 4, 5 });
        var i_Total = default(int);
        foreach (int CurVal in LstTmp)
        {
            i_Total += CurVal;
            bool exitFor1 = false;
            switch (CurVal)
            {
                case 6:
                    {
                        int b;
                        b = 0;
                        bool exitSelect = false;
                        bool exitFor = false;
                        do
                        {
                            if (b == 2)
                                continue;
                            if (b == 3)
                                break;
                            if (b == 4)
                            {
                                exitSelect = true;
                                break;
                            }

                            if (b == 5)
                                continue;
                            exitFor1 = exitFor = true;
                            break;
                            b += 1;
                        }
                        while (true);
                        if (exitSelect)
                        {
                            break;
                        }

                        if (exitFor)
                        {
                            break;
                        }

                        break;
                    }
            }

            if (exitFor1)
            {
                break;
            }
        }

        System.Console.WriteLine(i_Total.ToString()); // Prints 15
    }
}
```

Thanks,
Graham.

**Comment by GrahamTheCoder** [comment]
Closing this until there's a repro

**Comment by PeterSwinkels** [comment]
Repro? Didn’t I send an example?

Peter Swinkels

On 11 Mar 2022, at 17:09, GrahamTheCoder ***@***.***> wrote:

﻿

Closing this until there's a repro

**Comment by GrahamTheCoder** [comment]
Perhaps your email didn't send or something? The only thing I see is
> Always outputs "break". Even when for and do loops are nested.

But as you can see in my more detailed message above, the complex example I tried when trying to repro works flawlessly. Please let me know if you find an example that doesn't work on https://codeconverter.icsharpcode.net/ or using the latest version of the VS Extension.

**Comment by PeterSwinkels** [comment]
Try converting the following code:

Do
For x As Integer = 0 To 10
Exit Do
Next x
Loop

The Exit Do statement is converted to a break statement.

On 12 Mar 2022, at 18:05, GrahamTheCoder ***@***.***> wrote:

﻿

Perhaps your email didn't send or something? The only thing I see is

Always outputs "break". Even when for and do loops are nested.

But as you can see in my more detailed message above, the complex example I tried when trying to repro works flawlessly. Please let me know if you find an example that doesn't work on https://codeconverter.icsharpcode.net/ or using the latest version of the VS Extension.

**Comment by GrahamTheCoder** [comment]
Sorry Peter, it seems like we're having trouble communicating. When I paste the example you gave into https://codeconverter.icsharpcode.net/ the result is correct:

```csharp
{
    do
    {
        bool exitDo = false;
        for (int x = 0; x <= 10; x++)
        {
            exitDo = true;
            break;
        }

        if (exitDo)
        {
            break;
        }
    }
    while (true);
}
```

Please update to the latest version of the VS extension or command line, or use https://codeconverter.icsharpcode.net/ 
Thanks,
Graham.

**Comment by PeterSwinkels** [comment]
No problem. I am using https://converter.telerik.com/ but I believe you said it was outdated, right? Why is it still online if so?

On 13 Mar 2022, at 17:31, GrahamTheCoder ***@***.***> wrote:

﻿

Sorry Peter, it seems like we're having trouble communicating. When I paste the example you gave into https://codeconverter.icsharpcode.net/ the result is correct:

{
    do
    {
        bool exitDo = false;
        for (int x = 0; x <= 10; x++)
        {
            exitDo = true;
            break;
        }

        if (exitDo)
        {
            break;
        }
    }
    while (true);
}

Please update to the latest version of the VS extension or command line, or use https://codeconverter.icsharpcode.net/
Thanks,
Graham.

**Comment by PeterSwinkels** [comment]
do
for x as integer = 0 to 10
exit do
next x
loop

produces:

{
    do
    {
        for (int x = 0; x <= 10; x++)
            break;
    }
    while (true);
}


On 8 Mar 2022, at 23:33, GrahamTheCoder ***@***.***> wrote:

﻿

Hi Peter, thanks for getting in touch. This is an area we've improved in the last 2 months. Could you give an example snippet of code that shows the problem when entered into https://codeconverter.icsharpcode.net/ (which always runs on the latest version of our converter library). If your case works there, I'd suggest using the latest version of the VS extension, website or command line (further details on the readme<https://github.com/icsharpcode/CodeConverter/blob/master/README.md#code-converter--> rather than the older versions embedded in 3rd party sites.

To demonstrate, here's an example of some code which I believe does work correctly:

Imports System.Collections.Generic

Public Class VisualBasicClass
    Public Shared Sub Main()
        Dim LstTmp As New List(Of Integer)({1,2,3,4,5})
        Dim i_Total As Integer
        For Each CurVal As Integer In LstTmp
            i_Total += CurVal
            Select Case CurVal
                Case 6
                    Dim b As Integer
                    b = 0
                    Do
                        If b = 2 Then Continue Do
                        If b = 3 Then Exit Do
                        If b = 4 Then Exit Select
                        If b = 5 Then Continue For
                        Exit For
                        b+=1
                    Loop
            End Select
        Next
        System.Console.WriteLine(i_Total.ToString()) 'Prints 15
    End Sub
End Class

Converter<https://codeconverter.icsharpcode.net/> outputs:

using System.Collections.Generic;

public partial class VisualBasicClass
{
    public static void Main()
    {
        var LstTmp = new List<int>(new[] { 1, 2, 3, 4, 5 });
        var i_Total = default(int);
        foreach (int CurVal in LstTmp)
        {
            i_Total += CurVal;
            bool exitFor1 = false;
            switch (CurVal)
            {
                case 6:
                    {
                        int b;
                        b = 0;
                        bool exitSelect = false;
                        bool exitFor = false;
                        do
                        {
                            if (b == 2)
                                continue;
                            if (b == 3)
                                break;
                            if (b == 4)
                            {
                                exitSelect = true;
                                break;
                            }

                            if (b == 5)
                                continue;
                            exitFor1 = exitFor = true;
                            break;
                            b += 1;
                        }
                        while (true);
                        if (exitSelect)
                        {
                            break;
                        }

                        if (exitFor)
                        {
                            break;
                        }

                        break;
                    }
            }

            if (exitFor1)
            {
                break;
            }
        }

        System.Console.WriteLine(i_Total.ToString()); // Prints 15
    }
}

Thanks,
Graham.

**Comment by GrahamTheCoder** [comment]
If I put the code you gave into https://icsharpcode.github.io/CodeConverter/
This is the result
```csharp
{

    do
    {
        bool exitDo = false;
        for (int x = 0; x <= 10; x++)
        {
            exitDo = true;
            break;
        }

        if (exitDo)
        {
            break;
        }
    }
    while (true);
}
```

I don't have any influence over Telerik. Their website just makes use of this open source library which I maintain. All the best.

**Comment by PeterSwinkels** [comment]
Be that as it may, I completely forgot about this. Unsubscribed. Good luck.
