### ISSUE TITLE
Add timestamp for start and finish of project conversion

### ISSUE THREAD

**Issue by jrmoreno1** [icsharpcode/CodeConverter#848]
Converting a large project takes a lot of time and may need to be done multiple times (changing things in the unconverted project to make the conversion work, reconverting an active project multiple times before being ready to commit to new language) 

It would be great if the "Converting MyVbProject ..." message said "Begin converting MyVbProject at hh:mm..."

**Comment by GrahamTheCoder** [comment]
Closing as fixed - thanks!
