### ISSUE TITLE
VB -> C#: Double.TryParse into Decimal target results in silently altered behaviour

### ISSUE THREAD

**Issue by jconnop** [icsharpcode/CodeConverter#856]
### VB.Net input code
```vbnet
Module Module1

    Sub Main()
        Dim decimalTarget As Decimal
        Double.TryParse("123", decimalTarget)
    End Sub

End Module
```

### Erroneous output
```C#
namespace ConsoleApp1
{
    static class Module1
    {
        public static void Main()
        {
            var decimalTarget = default(decimal);
            double argresult = (double)decimalTarget;
            double.TryParse("123", out argresult);
        }
    }
}
```

### Expected output
```C#
namespace ConsoleApp1
{
    static class Module1
    {
        public static void Main()
        {
                decimal decimalTarget;
                double.TryParse("123", out var doubleTarget);
                decimalTarget = Convert.ToDecimal(doubleTarget);
        }
    }
}
```

or (leaves an obvious error to resolve)

```C#
namespace ConsoleApp1
{
    static class Module1
    {
        public static void Main()
        {
                decimal decimalTarget;
                double.TryParse("123", out decimalTarget);
        }
    }
}
```

### Details
* Product in use: e.g. VS extension. Website produces approximately the 2nd expected output.
* Version in use: 8.4.7.0
* Did you see it working in a previous version, which? No
* Input is a VB Console project targetting .NET Framework 4.7.2
* Producing the 2nd expected output, which the website version does and is a compiler error, is fine because it would be noticed after the conversion. The current output appears to be a successful conversion with no errors, but silently drops the parsed value resulting in behaviour change.

**Comment by GrahamTheCoder** [comment]
Thanks for the full report. I think I understand the general issue. The Web and Extension versions behaving differently is an extra oddity to investigate.

**Comment by jconnop** [comment]
@GrahamTheCoder 

I've gotten as far as determining that if ExpressionNodeVisitor.NeedsVariableForArgument returns RefConversion.PreAndPostAssignment for the specific problematic argument, it results in:

```C#
            var decimalTarget = default(decimal);
            double argresult = (double)decimalTarget;
            double.TryParse("123", out argresult);
            decimalTarget = (decimal)argresult;
```

which seems reasonable.

I'm not familiar enough with the surrounding code to know which conditions should be checked to return the value specifically for this problematic case without breaking anything else.

**Comment by GrahamTheCoder** [comment]
Yeah that sounds about right. For out parameters it may not be needed when the type mismatch is a widening conversion. Though I assume it should apply to ref parameters too?

**Comment by jconnop** [comment]
Absolutely should apply to ref params too, good point.

I agree that conceptually it shouldn't be needed for out params when there is a widening conversion, however in practice this doesn't compile:
```C#
    long longTarget;
    int.TryParse("123", out longTarget);
```
so in practice the only thing which could be omitted for the widening conversion is the final cast. I'm guesisng the simplification phase may remove this since Roslyn will identify as an unnecessary cast.

I'll have a go at a PR for this in the near future.
