### ISSUE TITLE
VB -> C#: Preprocessor directives are not converted

### ISSUE THREAD

**Issue by Yozer** [icsharpcode/CodeConverter#863]
### VB.Net input code
```vbnet
#If Debug
        Console.WriteLine("A")
#Else
        Console.WriteLine("B")
#End If
```

### Erroneous output
```C#
/* TODO ERROR: Skipped IfDirectiveTrivia
#If Debug
*/
Console.WriteLine("A");
/* TODO ERROR: Skipped ElseDirectiveTrivia
#Else
*//* TODO ERROR: Skipped DisabledTextTrivia
        Console.WriteLine("B")
*//* TODO ERROR: Skipped EndIfDirectiveTrivia
#End If
*/
```

### Expected output
```C#
#if DEBUG
    Console.WriteLine("A");
#else
    Console.WriteLine("B");
#endif
```

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash 69a16a7bb0af66c511c2493d4e5e771f90bff439
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Yep this is a tricky one. Though obviously the current situation could definitely be improved. I'll dedupe with this one https://github.com/icsharpcode/CodeConverter/issues/15#issuecomment-374409309

**Comment by GrahamTheCoder** [comment]
In terms of the directive itself, a bit of replacement might work, but for the contents proper parsing is needed. Might be easiest initially to use the top level conversion api on the text, which already detects various types of snippet. I'll find a link
