### ISSUE TITLE
Bug when converting multi-function calls to function with ref parameter

### ISSUE THREAD

**Issue by blackboxjt** [icsharpcode/CodeConverter#876]
The converter, when attempting to convert code that could hit Visual Studio Compiler Error CS0206 (A property or indexer may not be passed as an out or ref parameter, https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0206), it smartly refactored code, but did not put correct function (bolded) in resultant code.
**hs7303856635d84b49b041320d14e11afc()** should be **localInlineAssignHelper()** instead

VB.NET Code block:

> 				' Create a new color matrix and set the alpha value to 0.5
> 				Dim alphaMatrix As New ColorMatrix()
> 				alphaMatrix.Matrix00 = InlineAssignHelper(alphaMatrix.Matrix11, InlineAssignHelper(alphaMatrix.Matrix22, InlineAssignHelper(alphaMatrix.Matrix44, 1)))
> 				alphaMatrix.Matrix33 = Me._StyleProvider.Opacity

Converted C# Code block:

>                 // Create a new color matrix and set the alpha value to 0.5
>                 var alphaMatrix = new ColorMatrix();
>                 float localInlineAssignHelper() { float argtarget = alphaMatrix.Matrix44; var ret = InlineAssignHelper(ref argtarget, 1f); alphaMatrix.Matrix44 = argtarget; return ret; }
> 
>                 float localInlineAssignHelper1() { float argtarget = alphaMatrix.Matrix22; var ret = InlineAssignHelper(ref argtarget, hs7303856635d84b49b041320d14e11afc()); alphaMatrix.Matrix22 = argtarget; return ret; }
> 
>                 float argtarget = alphaMatrix.Matrix11;
>                 alphaMatrix.Matrix00 = InlineAssignHelper(ref argtarget, localInlineAssignHelper1());
>                 alphaMatrix.Matrix11 = argtarget;
>                 alphaMatrix.Matrix33 = _StyleProvider.Opacity;

**Comment by GrahamTheCoder** [comment]
Apologies for not replying here. I didn't have time to construct a self-contained repro at the time and then forgot about it. I've just pushed a fix to master which will be released in the near future. Thanks for reporting!
