### ISSUE TITLE
C# -> VB: WinUI3 Desktop code conversion issues

### ISSUE THREAD

**Issue by rrvenki** [icsharpcode/CodeConverter#900]
A working code (generated with standard template) in C#, if converted to VB below are the issues.
1. As expected - post converting CS to VB there appears no option to reload the project. We've to manually close VS2022 and open solution again.
2. The VB code requires me retarget to .NET 5.0 instead of .NET 6.0 (which i have installed while .NET 5.0 is not)
3.  Error	BC30560	'DesignerGeneratedAttribute' is ambiguous in the namespace 'Microsoft.VisualBasic.CompilerServices'.	LpwMay	C:\Users\xxxxxxxxx\source\repos\LpwMay\LpwMay\LpwMay\obj\x86\Debug\net5.0-windows10.0.19041\App.g.i.vb

* Template used is C# WinUI3 Desktop App.
* If TemplateStudio is used, The app in C# can use Windows.Storage for file handling. If converted to VB, we cannot use Windows.Storage and no clue what to use for file access.

**Comment by GrahamTheCoder** [comment]
The first two sound like project file conversion issues. Something to do with sdk and target framework settings in case that helps. 

When I get a chance to repro I'll hopefully understand better what's going on with the others.

I can't really advise on how to use VB for a modern app (that it sounds like you're just starting). In fact I'd strongly caution against doing so. From the readme:

> Visual Basic .NET is slowly dying. It has support for some project types on .NET 5, but won't be getting new features according to the [.NET Team Blog](https://devblogs.microsoft.com/vbteam/visual-basic-support-planned-for-net-5-0/).

If you only know VB, I'd suggest that the VB to c# (online) converter can be a great tool to accelerate learning c# - by writing something in VB that you don't see how to do in C# and then matching up bits of input and output (note that some patterns are slightly awkward to replicate so it aims for equivalent behaviour, not "good code").

Sorry if that doesn't help much, thanks for the report

**Comment by rrvenki** [comment]
1. For a sake of knowledge, i was trying to work on a WinUI3 CS code generated by Windows Template Studio targeting UWP and another targeting desktop. In initial versions of the converter the code generated in VB worked (almost... but with few minor changes). No additional code added/written other than template generated code. So that comes under 1000 lines i believe.
Of late after more Windows 11 updates and VS2022(latest preview) updates, the CS to VB generated code just never works. Again, if the generated VB is converted back to CS it gives even more errors (which is expected to work as it originally worked before any conversion at all). So that shows you've all been testing VB to CS conversions only.
2. I was checking if there is any life in VB (Microsoft version). Your last reply clearly shows the other way. We've other VB implementations for multiplatform by other vendors. The final thing you may do is force them not to use the name Visual Basic. How does it matter.
Thanks for the support. "Siverlighting" term is already used for sunsetting techs. Lets see How VB dies. I'm closing the ticket.
