### ISSUE TITLE
VB -> C#: Mapping trivia from source can override any #error trivia added by Converter

### ISSUE THREAD

**Issue by Yozer** [icsharpcode/CodeConverter#917]
### VB.Net input code
```vbnet
Public Class VisualBasicClass
    Public Class TestClass
        Public Property A As Integer
        Public Property B As integer
    End class
   Public Sub New()
        Dim y As  New TestClass() With { .A = 1, .B = .A 
        }
   End Sub
End Class
```

### Erroneous output
```C#
public VisualBasicClass()
{
    var y = new TestClass()
    {
        A = 1,// test
        B = default
    };
}
```

### Expected output
```C#
public VisualBasicClass()
{
    var y = new TestClass()
    {
        A = 1,// test
        B = default
        #error bla bla, can't convert this code
    };
}
```

If you move ```}``` to the same line:
```Dim y As  New TestClass() With { .A = 1, .B = .A }```
then the conversion looks "ok".
It think TriviaMapper will override any trivia added by the converter when there is something other we want to map from the source vb code.
What's worse, you will not get any info about errors in the output window (why dummyNode doesn't have error annotations?)

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by Yozer** [comment]
Worked fine before #880
I guess we could annate error trivia added by the converter and carry it over to C# code?

**Comment by GrahamTheCoder** [comment]
Ah yeah, I think it just overwrites whatever's there, which is pretty bad in the error case!

It'd be possible to just avoid overwriting, but then you'd have to pay attention to balancing the trivia. To get that for free, it may be better in the LineTriviaMapper, to pre-populate trivia collections with any warning/error trivias from the converted tree.
You'd probably need to change them to be converted before going into the collection for consistency.
