### ISSUE TITLE
VB -> C#: error CS8122 when using is null instead of == null

### ISSUE THREAD

**Issue by CardenInsurance** [icsharpcode/CodeConverter#930]
My actual VB.Net code is a complicated LINQ query that gets error CS8122 on a part that says `Where (pd.Record_Type Is Nothing Or pd.Record_Type = "Acreage")` and gets converted to `where (pd.Record_Type is null | pd.Record_Type == "Acreage")` but here is some code that might be easier to reproduce:

### VB.Net input code
```vbnet
Dim x As Object = Nothing
Dim expression As System.Linq.Expression(Of Func(Of Boolean)) = Function() x Is Nothing
```

### Erroneous output
```C#
object x = null;
System.Linq.Expressions.Expression<Func<bool>> expression = () => x is null; // CS8122
```

Visual Studio error:
`CS8122	An expression tree may not contain an 'is' pattern-matching operator.`

### Expected output (replace "is" with "==")
```C#
object x = null;
System.Linq.Expressions.Expression<Func<bool>> expression = () => x == null; // fine
```

### Details
* Product in use: e.g. VS extension
* Version in use: 9.0.2.0

**Comment by GrahamTheCoder** [comment]
Nice repro. Should be possible to check the surrounding expression types. For performance reasons we'll probably want to track when entering an expression so it's easy to check.

**Comment by Yozer** [comment]
Related: #316 
Might be helpful to catch some corner cases:
https://github.com/JosefPihrt/Roslynator/blob/7ba2f29f5090aa13f4dd6b7936af55180b678333/src/CSharp/CSharp/Extensions/SyntaxExtensions.cs#L3114

**Comment by GrahamTheCoder** [comment]
Nice one 😊 Very handy method to use there!
