### ISSUE TITLE
VB -> C#: conversion process stops mid-way on large project over 100 classes

### ISSUE THREAD

**Issue by bpatin** [icsharpcode/CodeConverter#938]
On a large VB project with over 100 files/classes, the conversion process proceeds roughly half-way through the files and then stops with no errors or other indications. This is on a Windows 11 workstation with 64GB memory, and more than 1TB disk space available.

**Comment by GrahamTheCoder** [comment]
Sounds like the same issue as here https://github.com/icsharpcode/CodeConverter/issues/877
So let's consolidate any further discussion there.
It's worth trying with the command line just in case it's any different.
If you manage to reproduce this issue on a solution where you can share the whole codebase, it'd really help. Without that it's very hard to move forward on the issue unfortunately. Thanks!
