### ISSUE TITLE
VB -> C#: `pv` -> `Financial.pv`

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#939]
### VB.Net input code
```vbnet
If pv.my_field = "XX Y/Y" Then
End If

If pv = "XX Y/Y" Then
End If
```

### Erroneous output
```C#
if (Financial.pv.my_field == "XX Y/Y")
{
}

if (Financial.pv == "XX Y/Y")
{
}
```

### Expected output
```C#
if (pv.my_field == "XX Y/Y")
{
}

if (pv == "XX Y/Y")
{
}
```

### Details
* Product in use: [icsharpcode.github.io/CodeConverte](https://icsharpcode.github.io/CodeConverter/)
* Version in use: 9.0.3.0

**Comment by Yozer** [comment]
@Saibamen  Your input code is missing the definition for ```pv``` type and the converter sees it as [Financial.PV](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.financial.pv?view=net-6.0) (builtin function in vb.net).
Please make sure your input code is complete and it's compiling for maximum accuracy as stated in the [wiki](https://github.com/icsharpcode/CodeConverter/wiki#general-advice)
