### ISSUE TITLE
VB -> C#: _Add a short description_

### ISSUE THREAD

**Issue by jakespeed2023** [icsharpcode/CodeConverter#960]
I cannot access the converter.
### Details
* Product in use: e.g. [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
The link on your post works for me. Can you screenshot the error you're seeing please?

**Comment by jakespeed2023** [comment]
***@***.***

Jake Yambao | Programmer Analyst
Marmak
30 Intermodal Drive | Brampton ON L6T 5K1
Office: 905.458.6686 x235
www.marmak.ca
***@***.***
