### ISSUE TITLE
VB -> C#: Explicit type information is lost when converting an initialized array

### ISSUE THREAD

**Issue by HeinziAT** [icsharpcode/CodeConverter#962]
### VB.Net input code
```vbnet
Dim o As Object() = {"a"}
```

### Erroneous output
```C#
var o = new[] { "a" };
```

### Expected output
```C#
var o = new object[] { "a" };
```

### Details
* Product in use: [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/)
* Version in use: 9.0.4.0
* The VB.NET code creates an object array, whereas the C# code creates a string array. This can lead to 
    * compile-time errors (for example, when trying to set `o[0] = 1;` later) or to 
    * run-time errors (for example, when passing this array to a method that expects an object array - this is (unfortunately) not a compile-time error due to C#'s array covariance).

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Should be reasonably easily fixable I think
