### ISSUE TITLE
Resulting C# still calls Microsoft.VisualBasic.Strings.Len

### ISSUE THREAD

**Issue by HamzaAhmedKhan786** [icsharpcode/CodeConverter#964]
### Steps to reproduce
1.  Convert VB file to CSharp.
2.  Must contain If statement with length function defined in it.
3.  Press button to convert.

### Error message shown
NO ERROR MESSAGE.

### Details
VB -> C# 
expected: if ((txtSearch.Text).Length == 0)
Actual: if (Len(txtSearch.Text) == 0) return; ---> (Same as VB)
###Files For the Reference:
[CSharp Code.txt](https://github.com/icsharpcode/CodeConverter/files/10187570/CSharp.Code.txt)
[VB Code.txt](https://github.com/icsharpcode/CodeConverter/files/10185657/VB.Code.txt)

**Comment by HamzaAhmedKhan786** [comment]
Please, let me know as soon as possible. I also checked it here: https://icsharpcode.github.io/CodeConverter but still not converting.
hope for the prompt response.
Thank you!

**Comment by GrahamTheCoder** [comment]
Ah, I've just spotted the issue with the properties at the bottom of the file, so I'll reopen the issue to cover just that part

**Comment by GrahamTheCoder** [comment]
Am I right in thinking your input is actually VB6 rather than VB.NET?
The syntax of the property seems to be disallowed now: https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc30808

**Comment by HamzaAhmedKhan786** [comment]
*Dear Graham,*

There will be no error found, it is just passing it if you write the code
in VB.Net then still you will observe that the LENGTH function will not be
converted in C# it will show the same.
Can you please try it for me and share your experience regarding length
function within the If statement. Basically I am converting the code from
VB6 to VB.Net and then into C#.

Now, I will see the VB6  to VB.Net conversion problem. Can you please check
VB.NET to C#? because I wrote an if statement with len function in VB.Net
but still not converting...
I checked it on your platform here:
https://icsharpcode.github.io/CodeConverter/

Thanks a lot for your prompt response.

*Warm regards,*
*Hamza Ahmed Khan.*

**Comment by HamzaAhmedKhan786** [comment]
*Thank you so much for the help! I saw that.*

For the time being I can use it but in future I will not use using Microsoft
.VisualBasic*; *because there are a lot of applications we(Company) want to
Convert in C# and The Company has decided that all the syntax of the code
will be in C#.
I will try to write some code which will convert if statements with .length
in C# syntax, so you can add directly into your ICSharp code and if you
will do it then just let me know.
I am just a junior developer and have less experience so if sometimes you
don't get what I am saying you can ask. I apologize for that in advance.😊

*Warm Regards,*
*Khan*

**Comment by GrahamTheCoder** [comment]
The converter's main purpose is to create some C# which compiles and behaves the same as the VB.NET did.
After that, you will likely want to improve the code by improving its style and removing various references to visual basic libraries - see https://github.com/icsharpcode/CodeConverter/wiki#code-style

Thank you for your offer. It's ok, I've actually already started on a solution for *part* of this problem. I just want to try again to explain this case so you don't add lots of errors to your code accidentally:

```vbnet
Dim str As String = Nothing
Dim L = Len(str) ' L = 0
```

What I think you're proposing:
```csharp
string str = null;
int L = str.Length; //This would throw a NullReferenceException
```

What I *might* add, but am worried it's too messy:
```csharp
string str = null;
int l = str?.Length ?? 0;
```
