### ISSUE TITLE
Need to convert to web application before converting website project

### ISSUE THREAD

**Issue by ortrails** [icsharpcode/CodeConverter#977]
### Steps to reproduce
1. In Visual Studio 2019 open up a Web Application project that contains VB code.
2. Run the "Convert to C#" command
3. See error

### Error message shown
#error Cannot convert ClassBlockSyntax - see comment for details
/* Cannot convert ClassBlockSyntax, CONVERSION ERROR: Object reference not set to an instance of an object. in 'Partial Class index_createM...' at character 206
   at ICSharpCode.CodeConverter.CSharp.HandledEventsAnalyzer.CreateEventContainer(EventContainerSyntax p, SemanticModel semanticModel)
   at ICSharpCode.CodeConverter.CSharp.HandledEventsAnalyzer.<>c__DisplayClass11_0.<HandledEvent>b__2(MethodStatementSyntax _, HandlesClauseItemSyntax e)
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

### Details
* Product in use: VS Extension
* Version in use: 9.1.1.0

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Somewhere in one of the parts of the partial class indicated (index_CreateM....) there must be a Handles clause with an event container that the converter can't find the symbol for.

I suspect it's this line throwing: https://github.com/icsharpcode/CodeConverter/blob/7a4bcd1d66841bc90b145a5b88223b507caae98e/CodeConverter/CSharp/HandledEventsAnalyzer.cs#L105

e.g. In a piece of code that looks like this, the converter needs to find the symbol that `SomeWithEventsFieldOrProp` corresponds to:
```vbnet
Public Sub Eventhandler_Load(sender As Object, e As Global.System.EventArgs) Handles SomeWithEventsFieldOrProp.Load
```

Nearby there's a TODO that sounds related, except I think it's already been done and the comment was just accidentally left, so I'm a bit stumped here. Is it possible to provide any of the source code for those types?

**Comment by ortrails** [comment]
Sure, this is a sample file.
[createMap.aspx.zip](https://github.com/icsharpcode/CodeConverter/files/10374318/createMap.aspx.zip)

**Comment by GrahamTheCoder** [comment]
Thanks, I've reproduced the issue, and will see if I can figure out a fix shortly

**Comment by GrahamTheCoder** [comment]
Ah apologies, I was mistaken, I haven't repro'd it yet

**Comment by ortrails** [comment]
That may be the problem. This is a file I am translating to c# as part of a process of converting website project to web application project. The web application project type has a .designer.cs with definitions for all the web controls, but since the pre-conversion files were vb (not the target c#) they were ignored and no .designer.vb files were generated. I don't know where the definitions are for the website project, probably hidden somewhere in an ASP.Net directory. Would it be worthwhile for me to try to verify this theory?

**Comment by GrahamTheCoder** [comment]
Ah yes, I see, does the converter even provide a convert project option or are you trying to do a file at a time?
If there's no convert project option, nearby files aren't taken into consideration. If that's the case, getting the files all into some kind of vbproj is the trick. They don't need to run in that form, but compiling (or the closer the better) allows the converter to grab the compilation model from the project. So just creating a library style vbproj with the appropriate references may be the thing to do

**Comment by ortrails** [comment]
Yes, that'd be an interesting approach. Kind of a conversion only assembly.

**Comment by GrahamTheCoder** [comment]
Let me know if you have success with the approach. It might be that with an example case where it worked, I could set up the converter could detect the scenario and make a best effort at something similar automatically - not sure how project dependant the setup will be

**Comment by ortrails** [comment]
@GrahamTheCoder version 9.1.2.0 works without error. Here's what I did.
1. In VS 2022 create an empty VB.NET web application.
2. Copy all the files from the old website we want to convert to the new web application folder. Overwrite and replace all. Save. Close VS 2022.
3. Open the new project in VS 2012.
4. Right click the project in Solution Explorer and select "Convert to Web Application". Save and exit VS 2012.
5. Open project again in VS 2022.
6. Right click the project in Solution Explorer and select "Convert to C#".
7. Conversion runs without error!

**Comment by GrahamTheCoder** [comment]
Great that it's worked, I've linked that from the repo wiki in case it helps others

**Comment by ortrails** [comment]
As for the ref vars, seems like if used reflection on the assembly you
could possibly know if the method call needs ref or not. I think the person
who wrote my project's VB code is more fond of ref parameters than the
average person.

**Comment by GrahamTheCoder** [comment]
Sorry I just realised I missed this reply. I'm afraid I've lost track of what issue you're talking about with ref vars it doesn't seem to be mentioned in this thread and the only ByRef in your example (on the ShowPage method) seems to convert fine.
Would you mind opening a separate issue with a repro for any issue you're having with ref parameters if there isn't already one?
Thanks!
