### ISSUE TITLE
Compiler Error CS0820 in C# code to convert in test VB.StatementTests.ArrayInitializationStatementInVarDeclarationAsync

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#985]
### Input code
```csharp
class TestClass
{
    void TestMethod()
    {
        var b = { 1, 2, 3 };
    }
}
```

### Error message shown
* CS0820 Cannot initialize an implicitly-typed variable with an array initializer

### Details
[Source](https://github.com/icsharpcode/CodeConverter/blob/7425b64017b386276ae3315f6a40add43a012130/Tests/VB/StatementTests.cs#L241)

**Comment by GrahamTheCoder** [comment]
Thanks, with one line fixes like this, I'm happy for you to just create a PR directly by the way without an issue first

**Comment by RussellSmith2** [comment]
I created the issue because I saw there were 2 options to fix it.  It wasn't until after I submitted it that I noticed only 1 of the options would work because the other option was used in the test above.

Unfortunately, you picked the option that was used in the test above so no both tests have identical code to test.

Should be:
var b = new[] { 1, 2, 3 };
