### ISSUE TITLE
RoslynCrashPreventer throws NullReferenceException when Microsoft.CodeAnaylsis 4.2.0 is referenced

### ISSUE THREAD

**Issue by anhaehne** [icsharpcode/CodeConverter#986]
### Steps to reproduce
1. Reference Microsoft.CodeAnaylsis 4.2.0 packages
2. Try to convert a VB expression to C# that fails (for example: `Return IIf(inFeld = "" OrElse inFeld = 0.0, Feld(11), inFeld)`)

### Error message shown
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.CodeConverter.Common.RoslynCrashPreventer.DelegatingHandler.ExchangeFatalErrorHandler(Action`1 errorHandler) in CodeConverter-master\CodeConverter\Common\RoslynCrashPreventer.cs:line 55
```

### Details
* Product in use: [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/)
* Version in use: latest main commit (f97ba4493af0222560ad0e9ce7a3fa667c5c59cb)

The type `Microsoft.CodeAnalysis.FatalError` can't be found in the assembly `Microsoft.CodeAnaylsis` for this newer version.

**Comment by GrahamTheCoder** [comment]
Thanks for letting me know about this. I'll just remove the class since I believe the issue it worked around is also fixed in more recent Visual Studio updates.
