### ISSUE TITLE
ToInt32

### ISSUE THREAD

**Issue by nexusdigital10** [icsharpcode/CodeConverter#987]
When I convert vb.net to C# using your extension is using code Conversions.ToInteger() instead of Convert.ToInt32() for ints.

Any way you can change this as I have 1,000s of int that need always to be change on the C# code?

**Comment by GrahamTheCoder** [comment]
Thanks for getting in touch. My comment here should answer your question: https://github.com/icsharpcode/CodeConverter/issues/980#issuecomment-1376427621

Of course if you know the thousands of places don't hit that difference, after conversion, just find replace "Conversions.ToInteger(" with "Convert.ToInt32(" 

I'll close this as a duplicate
