### ISSUE TITLE
VB -> C#:  UWP project still trying to compile as VB

### ISSUE THREAD

**Issue by ibelchamber** [icsharpcode/CodeConverter#988]
I need to covert at least one UWP GUI project in a large solution with 25 projects from VB to C#. I ran the converter, it took about an hour, but it reported no problems and seemed to complete ok. In the solution explorer the project now shows as c#. At a glance, the c# looks good. But I have nearly 100,000 errors.

I started looking at the errors and quickly realised that they are the kind of errors you would get if you have c# code in a vb project, such as:

Error		'#Region' statement must end with a matching '#End Region'
Error		Expected one of 'Dim', 'Const', 'Public', 'Private', 'Protected', 'Friend', 'Shadows', 'ReadOnly' or 'Shared'
Error		'Class' statement must end with a matching 'End Class'

The project started many years ago so perhaps there is more history than normal in the project and configuration files. 
What can I check to make sure the solution / project is correctly recognising / building the converted project as c# ?

Many thanks

**Comment by GrahamTheCoder** [comment]
The most likely cause is that the project type guid [examples](https://www.codeproject.com/Reference/720512/List-of-Visual-Studio-Project-Type-GUIDs) wasn't switched in the solution file. You may be able to remove the project from the solution, then re-add the csproj.
If it's not that, it might be the project file itself still contains things that cause the VB compiler to be invoked.
I'll see if I can find how to create an empty version of the project type you're talking about to try and repro.

**Comment by ibelchamber** [comment]
Thanks, I searched for F184 (the first part of the VB GUID) in the project file but nothing was there. It just looks like something is confused as the errors are listed but not shown in the code window.

I tried making a new project file and coppying the source into it. I think this is working but I'm now getting "Project XXX is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763) / win10-arm64-aot. Project XXX supports: uap10.0.18362 (UAP,Version=v10.0.18362)

So far I have been unable to find anything that relates to 17763 in the entire solution so this looks tricky. I'll carry on battling but any further suggestions welcome,

**Comment by GrahamTheCoder** [comment]
Hmm, if creating a brand new C# UWP project from the wizard in Visual Studio (even with no files related to the conversion) doesn't compile for you then I'm afraid that's outside the scope of what I can help with since I have never used that project type. Hope you manage to sort out your setup!

**Comment by ibelchamber** [comment]
OK but they are entirely different issues, I am working on both but would appreciate any further thoughts on the first which dies not seem to occur in the freshly created c# project, thanks, Ian

**Comment by GrahamTheCoder** [comment]
If it helps, when I first created a project, I got a dialog like this:
![image](https://user-images.githubusercontent.com/2490482/222894393-6638d8af-cc74-4621-ae43-c88cb8fce27a.png)
In the vbproj it then adds this: `<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>`
By diffing the default generated UWP project for VB and C# I can see the two main differences are:
ProjectTypeGuids: `{F184B08F-C81C-45F6-A57F-5ABD9991F28F}` -> `{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}`

`<Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.VisualBasic.targets" />`
gets switched for
  `<Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets" />`

**Comment by GrahamTheCoder** [comment]
So for your case, I expect when you created the new C# project you somehow picked a version you don't have installed (don't know why it would let you do that, but not implausible). So either take the existing converted project and change that import targets path, or in the brand new file, make sure your TargetPlatformMinVersion matches the original project.

There may be other details that need lining up of course too

**Comment by GrahamTheCoder** [comment]
I'll close this for now since the targets issue should be fixed in the next release, but reopen if there are other things UWP things that need fixing, thanks!
