### ISSUE TITLE
VB -> C#: WithEvents replacement causes NullReferenceException

### ISSUE THREAD

**Issue by HeinziAT** [icsharpcode/CodeConverter#991]
### VB.Net input code
```vbnet
Imports System

Public Module Program
    Public Sub Main(args As String())
        Dim c As New SomeClass(New SomeDependency())
        Console.WriteLine("Done")
    End Sub
End Module

Public Class SomeDependency
    Public Event SomeEvent As EventHandler
End Class

Public Class SomeClass
    Private WithEvents _dep As SomeDependency

    Public Sub New(dep)
        _dep = dep
    End Sub

    Private Sub _dep_SomeEvent(sender As Object, e As EventArgs) Handles _dep.SomeEvent
        ' Do Something
    End Sub
End Class
```

### Erroneous output
```C#
using System;
using System.Runtime.CompilerServices;

public static partial class Program
{
    public static void Main(string[] args)
    {
        var c = new SomeClass(new SomeDependency());
        Console.WriteLine("Done");
    }
}

public partial class SomeDependency
{
    public event EventHandler SomeEvent;
}

public partial class SomeClass
{
    private SomeDependency __dep;

    private SomeDependency _dep
    {
        [MethodImpl(MethodImplOptions.Synchronized)]
        get
        {
            return __dep;
        }

        [MethodImpl(MethodImplOptions.Synchronized)]
        set
        {
            if (__dep != null)
            {
                __dep.SomeEvent -= _dep_SomeEvent;
            }

            __dep = value;
            if (__dep != null)
            {
                __dep.SomeEvent += _dep_SomeEvent;
            }
        }
    }

    public SomeClass(object dep)
    {
        _dep.SomeEvent += _dep_SomeEvent;
        _dep = (SomeDependency)dep;
    }

    private void _dep_SomeEvent(object sender, EventArgs e)
    {
        // Do Something
    }
}
```

The VB code prints "Done", whereas the C# code throws a NullReferenceException in the first line of the constructor of SomeClass, since `_dep` has not been initialized yet.

### Expected output
The SomeClass constructor should not contain the line `_dep.SomeEvent += _dep_SomeEvent;`. This line only makes sense if `_dep` has an initializer.

### Details
* Product in use: [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/)
* Version in use: 9.1.3.0

**Comment by GrahamTheCoder** [comment]
Related to #967 - presumably event subscriptions should be at the bottom of the constructor. Though I can imagine an edge case where someone fires an event in the constructor which it might be worth checking the behaviour of in VB.

**Comment by GrahamTheCoder** [comment]
Ah yes, I see what you mean. When implementing #968 I do remember thinking "why on earth do we just drop these event subscriptions on the floor in most cases?" and hence added them in all cases. But you're right, it's because usually the property is used, and it's only a few special cases where they need to be explicitly added. e.g. In Winforms in InitializeComponent, and in WPF after InitializeComponent.

**Comment by jrmoreno1** [comment]
FWIW I recently saw the same problem for an asp.net application.

**Comment by GrahamTheCoder** [comment]
Busy few months ut finally got back to looking at this. I think I've moved it a step in the right direction in the version in master right now. I'll wait a little before releasing in case you or anyone else spots an issue with it since there are quite a lot of situations to consider
