### ISSUE TITLE
VB -> C#: CType(Nothing, <Nullable>?) returns default instead of null

### ISSUE THREAD

**Issue by cysieks** [icsharpcode/CodeConverter#994]
### VB.Net input code
```vbnet
Imports System

Public Class VisualBasicClass
    Dim SomeDate As String = "2022-01-01"
    Dim SomeDateDateParsed As Date? = If(String.IsNullOrEmpty(SomeDate), CType(Nothing, Date?), DateTime.Parse(SomeDate))
    Dim SomeDateDateNothing As Date? = If(String.IsNullOrEmpty(SomeDate), Nothing, DateTime.Parse(SomeDate))
End Class
```

### Erroneous output
```C#
using System;

public partial class VisualBasicClass
{
    private string SomeDate = "2022-01-01";
    private DateTime? SomeDateDateParsed;
    private DateTime? SomeDateDateNothing;

    public VisualBasicClass()
    {
        SomeDateDateParsed = string.IsNullOrEmpty(SomeDate) ? default : DateTime.Parse(SomeDate);
        SomeDateDateNothing = string.IsNullOrEmpty(SomeDate) ? default : DateTime.Parse(SomeDate);
    }
}
```

### Expected output
```C#
using System;

public partial class VisualBasicClass
{
    private string SomeDate = "2022-01-01";
    private DateTime? SomeDateDateParsed;
    private DateTime? SomeDateDateNothing;

    public VisualBasicClass()
    {
        SomeDateDateParsed = string.IsNullOrEmpty(SomeDate) ? null: DateTime.Parse(SomeDate);
        SomeDateDateNothing = string.IsNullOrEmpty(SomeDate) ? default : DateTime.Parse(SomeDate);
    }
}
```

### Details
* Product in use: both
* Version in use: e.g. 9.1.3.577
* Did you see it working in a previous version, which? No
* Any other relevant information to the issue, or your interest in contributing a fix. I know it's tricky in VB with Nothing, but I think in this scenario it should be null, not default. Please check the fiddle: https://dotnetfiddle.net/PwEL1D

**Comment by GrahamTheCoder** [comment]
We could probably special case `CType(Nothing, AnyType?)` to generate `default(AnyType)`. 

I checked `CType(x, Integer?)` (probably) correctly converts to `((int?) x)`

**Comment by cysieks** [comment]
can we generate `default(AnyType?)`?
The second case looks correct.

**Comment by GrahamTheCoder** [comment]
Yep, apologies, that's what I meant! I've edited my post to say that now.

**Comment by cysieks** [comment]
Exactly :) Thank you

**Comment by cysieks** [comment]
Cool, any chance to update the command line tool? We have it in the pipeline.

**Comment by GrahamTheCoder** [comment]
9.2.1 released
