### ISSUE TITLE
VB to C# Conversion for OnErrorGoToLabelStatement not implemented

### ISSUE THREAD

**Issue by tomphan** [icsharpcode/CodeConverter#996]
### Steps to reproduce
Try to convert this line of code:

`On Error GoTo ERRSEND`

### Error message shown

> CONVERSION ERROR: Conversion for OnErrorGoToLabelStatement not implemented, please report this issue in 'On Error GoTo ERRSEND' at character ...

### Details
* Product in use: VS extension
* Version in use: 9.2.0.0

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I'll consolidate it with
https://github.com/icsharpcode/CodeConverter/issues/426
See there for more detail of interested
