### ISSUE TITLE
VB -> C#: Handling of nested default-initialized loop variables

### ISSUE THREAD

**Issue by philippejer** [icsharpcode/CodeConverter#998]
### VB.Net input code
```vbnet
Class TestClass
    Private Sub TestMethod(someCondition As Boolean)
        For j = 1 To 2
            If someCondition Then
                Dim b As Boolean
                Console.WriteLine(b)
                b = True
            End If
        Next
    End Sub
End Class
```

### Erroneous output
```C#
using System;
          
internal partial class TestClass
{
    private void TestMethod(bool someCondition)
    {
        var b = default(bool);
        for (int j = 1; j <= 2; j++)
        {
            if (someCondition)
            {
                Console.WriteLine(phb9bd034daca847259b64966be09448f5);
                phb9bd034daca847259b64966be09448f5 = true;
            }
        }
    }
}
```

### Expected output
```C#
using System;
          
internal partial class TestClass
{
    private void TestMethod(bool someCondition)
    {
        var b = default(bool);
        for (int j = 1; j <= 2; j++)
        {
            if (someCondition)
            {
                Console.WriteLine(b);
                b = true;
            }
        }
    }
}
```

### Details
* Product in use: Found in VS extension, reproduced in latest master
* Version in use: VS extension 9.2.0.0
* Did you see it working in a previous version, which? Yes, see below.

~I managed to track down the issue to this PR: https://github.com/icsharpcode/CodeConverter/pull/902~

~It appears the issue is that the `value` variable is declared inside an `If` statement but the conversion seems to handle it as a local variable inside a loop.~

~Explicitly initializing the `value` variable on the VB side yields the expected output (as well as removing any of the control flow statements).~

Edited after working on the issue : 
* Miminized the test case.
* #902 is not a regression, the variable must be pulled ouside the loop even if not directly under the loop statement.
It is simply a bug in the implementation of the fix.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. There's code to replace that temporary generated name - not sure why it's not working here.
Let me know if you are interested in trying to fix it, otherwise hopefully I'll get around to it at some point ☺

**Comment by philippejer** [comment]
I've looked at the code, I'll try to see if I can have a clean fix (given my lack of familiarity with the code 😊)

**Comment by GrahamTheCoder** [comment]
Great, feel free to open a draft PR with random work in progress or attempts and ask any questions. There are some hints in the [contributing guidelines] (https://github.com/icsharpcode/CodeConverter/blob/f23e1dfbc171ce451b9606e8e5014c1c26cf7c9b/.github/CONTRIBUTING.md#how-to-get-started-changing-code)
